### ISSUE TITLE
Graph doesn't display opening .gefx file

### ISSUE THREAD

**Issue by dbl001** [gephi/gephi#1094]
org.gephi.io.importer.api.Issue@539f0d00	INFO	
org.gephi.io.importer.api.Issue@1691aec8	INFO	

![screen shot 2015-08-16 at 10 17 27 am](https://cloud.githubusercontent.com/assets/3105499/9294398/1c650994-4401-11e5-84ae-265294db3142.png

**Comment by dbl001** [comment]
java.lang.IllegalArgumentException: The default value type cannot be cast to the type
	at org.gephi.graph.store.TableImpl.checkDefaultValue(TableImpl.java:191)
	at org.gephi.graph.store.TableImpl.addColumn(TableImpl.java:59)
	at org.gephi.io.processor.plugin.AbstractProcessor.flushColumns(AbstractProcessor.java:75)
	at org.gephi.io.processor.plugin.DefaultProcessor.process(DefaultProcessor.java:94)
	at org.gephi.io.importer.impl.ImportControllerImpl.process(ImportControllerImpl.java:279)
	at org.gephi.desktop.importer.DesktopImportControllerUI.finishImport(DesktopImportControllerUI.java:520)
	at org.gephi.desktop.importer.DesktopImportControllerUI.access$100(DesktopImportControllerUI.java:97)
	at org.gephi.desktop.importer.DesktopImportControllerUI$3.run(DesktopImportControllerUI.java:180)
Caused: java.lang.RuntimeException
	at org.gephi.desktop.importer.DesktopImportControllerUI$3.run(DesktopImportControllerUI.java:183)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:273)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by dbl001** [comment]
java.lang.ArithmeticException: / by zero
	at org.gephi.statistics.plugin.Modularity.computeModularity(Modularity.java:498)
	at org.gephi.statistics.plugin.Modularity.execute(Modularity.java:465)
	at org.gephi.statistics.plugin.Modularity.execute(Modularity.java:454)
	at org.gephi.statistics.StatisticsControllerImpl.execute(StatisticsControllerImpl.java:161)
	at org.gephi.statistics.StatisticsControllerImpl$3.run(StatisticsControllerImpl.java:147)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:273)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
