### ISSUE TITLE
Visualizations not working on Mac OS X 10.10.3 with Java 1.6 and Gephi 0.8.2-beta

### ISSUE THREAD

**Issue by elubow** [gephi/gephi#1138]
I've been trying to get anything to show up for a few days when I do a graph visualization and I don't seem to be getting anywhere.

This is what I see when I start it from the command line:
```
$ JAVA_HOME="/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home" ~/Applications/Gephi.app/Contents/Resources/gephi/bin/gephi
Loading native libraries
Current Version is 082
Error while checking latest Gephi version
org.netbeans.core.windows.view.ui.slides.ResizeGestureRecognizer$GlassPane[,0,0,0x0,invalid,hidden,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777217,maximumSize=,minimumSize=,preferredSize=]
javax.swing.JPanel[null.glassPane,0,0,1966x1126,invalid,hidden,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777217,maximumSize=,minimumSize=,preferredSize=]
```

Here is my modified `etc/gephi.conf` file:
```
default_userdir="${HOME}/.${APPNAME}/0.8.2/dev"
default_mac_userdir="${HOME}/Library/Application Support/${APPNAME}/0.8.2/dev"
default_options="-J-Xms256m -J-Xmx1024m -J-Xverify:none -J-Dsun.java2d.noddraw=true -J-Dsun.awt.noerasebackground=true -J-Dnetbeans.indexing.noFileRefresh=true -J-Dplugin.manager.check.interval=EVERY_DAY"
jdkhome="/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home"
#extra_clusters=
```

This is the closest thing to an `ERROR` that I could find in any logs:

```
WARNING [org.openide.filesystems.Ordering]: Not all children in Menu/Window/ marked with the position attribute: [boutemineoualid-gephi-plugins-clustering-label_propagation-LabelPropagationSettingsPanelTopComponent.shadow], but some are: [org-gephi-desktop-clustering-ClusteringTopComponent.shadow, org-gephi-desktop-clustering-ContextTopComponent.shadow, org-gephi-desktop-datalab-DataTableTopComponent.shadow, org-gephi-desktop-filters-FiltersTopComponent.shadow, org-gephi-visualization-component-GraphTopComponent.shadow, org-gephi-desktop-datalab-HierarchyTopComponent.shadow, org-gephi-desktop-layout-LayoutTopComponent.shadow, org-gephi-desktop-partition-PartitionTopComponent.shadow, org-gephi-desktop-preview-PreviewTopComponent.shadow, org-gephi-desktop-preview-PreviewSettingsTopComponent.shadow, org-gephi-desktop-ranking-RankingTopComponent.shadow, org-gephi-desktop-welcome-WelcomeAction.shadow, org-gephi-desktop-statistics-StatisticsTopComponent.shadow, org-gephi-desktop-timeline-TimelineWindowAction.shadow, org-gephi-desktop-streaming-StreamingTopComponent.shadow, Separator3.instance, ConfigureWindow, Separator4.instance, CloseWindowAction.shadow, Separator4_1.instance]
```

I Googled around and came up with nothing. Not sure what else I can post here to be helpful.

**Comment by elubow** [comment]
Actually, I turned on debugging and found this too:

```
SEVERE [org.netbeans.core.modules]
java.lang.NullPointerException
	at org.netbeans.modules.autoupdate.ui.actions.AutoupdateSettings.getSuperIdentity(AutoupdateSettings.java:435)
	at org.netbeans.modules.autoupdate.ui.actions.AutoupdateSettings.generateIdentity(AutoupdateSettings.java:136)
	at org.netbeans.modules.autoupdate.ui.actions.AutoupdateCheckScheduler.signOn(AutoupdateCheckScheduler.java:110)
	at org.netbeans.modules.autoupdate.ui.actions.Installer.restored(Installer.java:63)
	at org.netbeans.core.startup.NbInstaller.loadCode(NbInstaller.java:469)
[catch] at org.netbeans.core.startup.NbInstaller.loadImpl(NbInstaller.java:392)
	at org.netbeans.core.startup.NbInstaller.access$000(NbInstaller.java:103)
	at org.netbeans.core.startup.NbInstaller$1.run(NbInstaller.java:344)
	at org.openide.filesystems.FileUtil$2.run(FileUtil.java:619)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:127)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:607)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:603)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:623)
	at org.netbeans.core.startup.NbInstaller.load(NbInstaller.java:341)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1179)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1002)
	at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:340)
	at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:276)
	at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:296)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:169)
	at org.netbeans.core.startup.Main.start(Main.java:305)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:123)
	at java.lang.Thread.run(Thread.java:695)
WARNING [org.netbeans.core.startup.InstalledFileLocatorImpl]: no such module /Users/elubow/Applications/Gephi.app/Contents/Resources/gephi/gephi/update_tracking/org-gephi-visualization-impl.xml at org.gephi.visualization.opengl.JOGLNativesInstaller.restored(JOGLNativesInstaller.java:71)
```

**Comment by duncdrum** [comment]
have you build from source, do you have netbeans installed?

**Comment by kentwills** [comment]
I actually did something similar: 
if you open up the `/Applications/Gephi.app/Contents/Resources/gephi/bin/gephi` file, you will notice the jdkhome is being set, I just changed the jdk path to my 1.7.79 java and viola it works.

Add this line after line 54 outside of the if statement:
```
jdkhome="/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/"
```
Then you can just double click the icon, no problems.

**Comment by elubow** [comment]
I just attempted to build 0.9 source using Java 1.6 and I think the visualizations work.  But the way I was loading the data in to Gephi was with streaming from Gremlin.  I can't seem to find anywhere in 0.9 where the streaming settings are.

**Comment by mbastian** [comment]
Cool, yeah the 0.9 visualization should work on all versions of Java. For the streaming, aren't you using the Graph Streaming plugin?

**Comment by mbastian** [comment]
Closing as Gephi 0.9+ solves this. Btw the graph streaming plugin has just been updated for 0.9.1.
