### ISSUE TITLE
SVG, PDF export generate 'null pointer' exception

### ISSUE THREAD

**Issue by rbelew** [gephi/gephi#1239]
(my symptoms are similar to issue #1227, but enough different i am submitting a new one.)

First, **ALL** attempts at SVG export fail, and without the little red error glyph (lower right hand corner).  can i get the error log some other way?

first, i can reliably generate an exception when i use certain FONTS:  it works with Ariel but dies on Times.  at least i am able to use the the little red error glyph to get an error log for this one:

    java.nio.charset.UnsupportedCharsetException: Identity-H
    at java.nio.charset.Charset.forName(Charset.java:531)
    at com.itextpdf.text.pdf.PdfEncodings.convertToBytes(PdfEncodings.java:186)
    at com.itextpdf.text.pdf.Type1Font.<init>(Type1Font.java:276)
    at com.itextpdf.text.pdf.BaseFont.createFont(BaseFont.java:690)
    at com.itextpdf.text.pdf.BaseFont.createFont(BaseFont.java:613)
    at com.itextpdf.text.FontFactoryImp.getFont(FontFactoryImp.java:192)
    at com.itextpdf.text.FontFactoryImp.getFont(FontFactoryImp.java:145)
    at com.itextpdf.text.FontFactory.getFont(FontFactory.java:131)
    at com.itextpdf.text.FontFactory.getFont(FontFactory.java:220)
    [catch] at org.gephi.preview.PDFRenderTargetBuilder$PDFRenderTargetImpl.getBaseFont(PDFRenderTargetBuilder.java:190)
    at org.gephi.preview.plugin.renderers.NodeLabelRenderer.renderPDF(NodeLabelRenderer.java:307)
    at org.gephi.preview.plugin.renderers.NodeLabelRenderer.render(NodeLabelRenderer.java:195)
    at org.gephi.preview.PreviewControllerImpl.render(PreviewControllerImpl.java:251)
    at org.gephi.preview.PreviewControllerImpl.render(PreviewControllerImpl.java:208)
    at org.gephi.io.exporter.preview.PDFExporter.execute(PDFExporter.java:132)
    at org.gephi.io.exporter.impl.ExportControllerImpl.exportFile(ExportControllerImpl.java:113)
    at org.gephi.desktop.io.export.DesktopExportController$2.run(DesktopExportController.java:104)
    at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:275)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

this is all using a snap of 0.9:

    Product Version: Gephi 0.9-SNAPSHOT 201510222201
    Java: 1.8.0_66; Java HotSpot(TM) 64-Bit Server VM 25.66-b17
    Runtime: Java(TM) SE Runtime Environment 1.8.0_66-b17
    System: Mac OS X version 10.9.5 running on x86_64; UTF-8; en_US (gephi)

**Comment by mbastian** [comment]
Hi, the exception trace concerns a PDF export. You can get the error with 0.9 by going to Window menu and then Output. That opens up the Log window, where the exception should be written. Also, it might be related to the graphs you're using, do you have the problem with all graphs?

**Comment by rbelew** [comment]
right, the previous dump was from the PDF export.  thanks for your pointer to Output;  the exception log for the SVG export is here:

    [INFO] Total memory 8,589,934,592 
    [INFO] Total physical memory 8,589,934,592 
    [WARNING] Services/AutoupdateType/org_gephi_branding_update_center.instance: url_key attribute deprecated in favor of url 
    [WARNING] Services/AutoupdateType/org_gephi_branding_update_center_1.instance: url_key attribute deprecated in favor of url 
    [INFO] External Changes Refresh on focus gain disabled 
    [INFO] java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
    [INFO] 	at org.gephi.desktop.io.export.DesktopExportController$2.run(DesktopExportController.java:107)
    [INFO] 	at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:275)
    [INFO] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    [INFO] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    [INFO] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    [INFO] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    [INFO] 	at java.lang.Thread.run(Thread.java:745)
    [INFO] Caused by: java.lang.RuntimeException: java.lang.NullPointerException
    [INFO] 	at org.gephi.io.exporter.preview.SVGExporter.execute(SVGExporter.java:113)
    [INFO] 	at org.gephi.io.exporter.impl.ExportControllerImpl.exportFile(ExportControllerImpl.java:134)
    [INFO] 	at org.gephi.desktop.io.export.DesktopExportController$2.run(DesktopExportController.java:104)
    [INFO] 	... 6 more
    [INFO] Caused by: java.lang.NullPointerException
    [INFO] 	at org.gephi.preview.plugin.renderers.NodeLabelRenderer.renderSVG(NodeLabelRenderer.java:288)
    [INFO] 	at org.gephi.preview.plugin.renderers.NodeLabelRenderer.render(NodeLabelRenderer.java:193)
    [INFO] 	at org.gephi.preview.PreviewControllerImpl.render(PreviewControllerImpl.java:251)
    [INFO] 	at org.gephi.preview.PreviewControllerImpl.render(PreviewControllerImpl.java:208)
    [INFO] 	at org.gephi.io.exporter.preview.SVGExporter.execute(SVGExporter.java:95)
    [INFO] 	... 8 more

i've only tried it with one graph so far.

**Comment by mbastian** [comment]
Ok that helps already as I can see the exact line but it would be ideal if I could reproduce the error. Could you share the input file, or a sample here? Thanks.

**Comment by rbelew** [comment]
i'll send you the file, but don't want to post it here. i'm rik AT electronicArtifacts DOT com

**Comment by mbastian** [comment]
Thanks. I can reproduce it.

**Comment by mbastian** [comment]
I fixed it. The PDF & SVG issues were unrelated. The PDF issue was because of the Font registration process, and I fixed something. The SVG issue was because you had an empty label " " and the code wasn't resistant to that. Also fixed.
