### ISSUE TITLE
Edge Rank Color on Weight makes UI goes wrong

### ISSUE THREAD

**Issue by totetmatt** [gephi/gephi#1244]
![bugedgecolor](https://cloud.githubusercontent.com/assets/749891/11938315/6225d9e0-a81a-11e5-83d7-986355e43cad.gif)

![bugedgecolor2](https://cloud.githubusercontent.com/assets/749891/11938397/df71ca9e-a81a-11e5-9ea2-c3d55cb5ed4e.gif)

When using Edge Color on Weight, the Raking tab and the Overview Tab are bugged. 
Then even is Gephi is closed, the process still alive

Config : Win 7 / Java 1.8_60 / Gephi64

Error Detailed : 
java.lang.NullPointerException
	at org.gephi.graph.impl.EdgeImpl$EdgePropertiesImpl.setColor(EdgeImpl.java:466)
	at org.gephi.graph.impl.EdgeImpl.setColor(EdgeImpl.java:371)
	at org.gephi.appearance.plugin.RankingElementColorTransformer.transform(RankingElementColorTransformer.java:66)
	at org.gephi.appearance.FunctionImpl.transform(FunctionImpl.java:98)
	at org.gephi.appearance.AppearanceControllerImpl.transform(AppearanceControllerImpl.java:123)
	at org.gephi.desktop.appearance.AppearanceTopComponent$8.actionPerformed(AppearanceTopComponent.java:411)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by mbastian** [comment]
Thanks for the detailed report, I'm able to reproduce it.

**Comment by mbastian** [comment]
This is due to the fact min(edgeWeight) == max(edgeWeight). In ranking (0.8.2) I think we ignored these columns alltogether. But I think it make sense to keep them but force the ranking to be max value (right-most color or max size).
