### ISSUE TITLE
Gexf liststring attribute type not working

### ISSUE THREAD

**Issue by Pimentoso** [gephi/gephi#1266]
Looks like using a liststring node attribute in a gexf file is broken in Gephi 0.9. 

Also the graph does not get imported if the attribute is default to null.
```
      <attribute id="10" title="tags_list" type="liststring">
        <default>null</default>
      </attribute>
```

Here is an example gexf file that gives error
https://github.com/Yomguithereal/gexf/blob/master/test/resources/liststring.gexf

```
java.lang.IllegalArgumentException: The type should be a wrapped primitive
	at org.gephi.graph.api.AttributeUtils.getPrimitiveType(AttributeUtils.java:412)
	at org.gephi.graph.api.AttributeUtils.getPrimitiveArray(AttributeUtils.java:431)
	at org.gephi.graph.api.AttributeUtils.standardizeValue(AttributeUtils.java:620)
	at org.gephi.graph.impl.TableImpl.addColumn(TableImpl.java:63)
	at org.gephi.io.processor.plugin.AbstractProcessor.flushColumns(AbstractProcessor.java:86)
	at org.gephi.io.processor.plugin.DefaultProcessor.process(DefaultProcessor.java:151)
	at org.gephi.io.processor.plugin.DefaultProcessor.process(DefaultProcessor.java:102)
	at org.gephi.io.importer.impl.ImportControllerImpl.process(ImportControllerImpl.java:292)
	at org.gephi.desktop.importer.DesktopImportControllerUI.finishImport(DesktopImportControllerUI.java:630)
	at org.gephi.desktop.importer.DesktopImportControllerUI.access$200(DesktopImportControllerUI.java:101)
	at org.gephi.desktop.importer.DesktopImportControllerUI$6.run(DesktopImportControllerUI.java:282)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:275)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mbastian** [comment]
Thanks for the report. I can reproduce it and will fix it.

**Comment by mbastian** [comment]
This is fixed since updated the graphstore dependency to 0.5.0
