### ISSUE TITLE
Coloring/Filtering Edges

### ISSUE THREAD

**Issue by JoeViavattine** [gephi/gephi#1267]
Background: I created a simple directed network.  I created a boolean attribute for edges and assigned all edges.
Problem 1: Coloring edges by attribute does not color the edges.  Resetting the colors and then coloring the edges turns all of the edges black (from gray), but doesn't color them based on the pallet.
Problem 2: Filtering the edges based on this attribute does nothing.  All edges remain regardless of which combination of edges are chosen in the filter.
History: I previously had 0.8.2 installed.  I am currently using 0.9.  I have uninstalled 0.8.2.  I am using Windows 7.  And I occasionally get java exceptions.

**Comment by JoeViavattine** [comment]
I have a little more info.  I went back to create another attribute column for the edges.  I was going to use an integer and color by that, but instead I saw that there were two different types of boolean choices.  One said "boolean" and the other said "boolean[]".  The latter had some character(s) after it that looked like a box.  The initial trial used the latter.  Data in the laboratory shows up as [true] and [false].  The new boolean shows up as checkboxes in the laboratory.  When I color by true/false, it now works.  It however still doesn't filter.

**Comment by eduramiba** [comment]
Hi,
Just to clarify, all types with [] are arrays (lists) of that preceding type. So you can write [true, false, true] for example.

As far as I know, array types are not supported in filters or appeareance.

**Comment by JoeViavattine** [comment]
Thanks.  It helps to know that they are arrays and that they are not supported.  Here is a recent exception.  It could very well just be on my end that these functions are not working.  The exceptions only started after the 0.9 install.

java.lang.NullPointerException
	at org.gephi.layout.plugin.forceAtlas.ForceAtlasLayout.goAlgo(ForceAtlasLayout.java:105)
	at org.gephi.layout.LayoutControllerImpl$LayoutRun.run(LayoutControllerImpl.java:185)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:275)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
