### ISSUE TITLE
Java NPE when toggling on / off the visibility of edges

### ISSUE THREAD

**Issue by seinecle** [gephi/gephi#1270]
The trace:

java.lang.NullPointerException
    at javax.swing.JPopupMenu.setVisible(JPopupMenu.java:796)
    at javax.swing.JPopupMenu.menuSelectionChanged(JPopupMenu.java:1483)
    at javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:119)
    at javax.swing.MenuSelectionManager.clearSelectedPath(MenuSelectionManager.java:151)
    at com.jogamp.newt.awt.NewtCanvasAWT$3.run(NewtCanvasAWT.java:260)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by mbastian** [comment]
I can't reproduce this issue. Can you share the exact steps as well as the complete messages.log (you can get it by clicking Window > Output). Thanks.

**Comment by eduramiba** [comment]
Closing old issue
