### ISSUE TITLE
RuntimeException on gephi opening

### ISSUE THREAD

**Issue by totetmatt** [gephi/gephi#1326]
Issue randomly appears when just open Gephi. Makes overview unusable as it's not possible to move and zoom anymore.
```
java.lang.RuntimeException: Waited 5000ms for: <2f3f914e, 21f86ad9>[count 4, qsz 0, owner <AWT-EventQueue-0-Display-.windows_nil-1-EDT-1>] - <DisplayAnimator>
	at jogamp.common.util.locks.RecursiveLockImpl01Unfairish.lock(RecursiveLockImpl01Unfairish.java:198)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:755)
	at org.gephi.visualization.swing.GLAbstractListener.display(GLAbstractListener.java:334)
	at org.gephi.visualization.scheduler.CompatibilityScheduler$1.run(CompatibilityScheduler.java:97)
[catch] at org.gephi.visualization.scheduler.BasicFPSAnimator.run(BasicFPSAnimator.java:34)
```
Seen on Gephi 64, Windows 7

**Comment by lucahost** [comment]
this is the same exception I see in my logs when just starting Gephi on Windows 10 64bit.
The Application freezes and is not recovering.

I cannot start it. Reinstalling did not help.

**Comment by mbastian** [comment]
Thanks for the report. This freeze is coming from the old engine's display loop (`RecursiveLockImpl01Unfairish.lock()` timing out inside `GLWindow.display()`), code that Gephi 0.11 replaced entirely with a new visualization engine implementation.

Could you retry on the latest 0.11.x release? If it still reproduces, please open a fresh issue with your OS/GPU details and the graph size that triggers it. Closing this for now as superseded by the new engine.
