### ISSUE TITLE
Exception when editing array types

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#1338]
```
SEVERE [org.openide.util.Exceptions]
java.lang.NoSuchMethodException: org.gephi.ui.tools.plugin.edit.SingleRowAttributeValueWrapper.getValueString[]()
        at java.lang.Class.getMethod(Class.java:1786)
        at org.openide.nodes.PropertySupport$Reflection.<init>(PropertySupport.java:174)
[catch] at org.gephi.ui.tools.plugin.edit.EditNodes.prepareNodesAttributes(EditNodes.java:142)
        at org.gephi.ui.tools.plugin.edit.EditNodes.getPropertySets(EditNodes.java:103)
        at org.openide.explorer.propertysheet.PropertySheet.setCurrentNode(PropertySheet.java:668)
        at org.openide.explorer.propertysheet.PropertySheet.doSetNodes(PropertySheet.java:467)
        at org.openide.explorer.propertysheet.PropertySheet.access$100(PropertySheet.java:117)
        at org.openide.explorer.propertysheet.PropertySheet$2$1.run(PropertySheet.java:629)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
SEVERE [org.openide.util.Exceptions]
java.lang.NoSuchMethodException: org.gephi.ui.tools.plugin.edit.SingleRowAttributeValueWrapper.getValueString[]()
        at java.lang.Class.getMethod(Class.java:1786)
        at org.openide.nodes.PropertySupport$Reflection.<init>(PropertySupport.java:174)
[catch] at org.gephi.ui.tools.plugin.edit.EditNodes.prepareNodesAttributes(EditNodes.java:142)
        at org.gephi.ui.tools.plugin.edit.EditNodes.getPropertySets(EditNodes.java:103)
        at org.openide.explorer.propertysheet.PropertySheet.needTabs(PropertySheet.java:982)
        at org.openide.explorer.propertysheet.PropertySheet.setCurrentNode(PropertySheet.java:688)
        at org.openide.explorer.propertysheet.PropertySheet.doSetNodes(PropertySheet.java:467)
        at org.openide.explorer.propertysheet.PropertySheet.access$100(PropertySheet.java:117)
        at org.openide.explorer.propertysheet.PropertySheet$2$1.run(PropertySheet.java:629)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
SEVERE [global]
java.lang.NullPointerException: Node org.gephi.ui.tools.plugin.edit.EditNodes[name=] contains null in its getPropertySets() array
        at org.openide.explorer.propertysheet.PropertySheet.needTabs(PropertySheet.java:989)
        at org.openide.explorer.propertysheet.PropertySheet.setCurrentNode(PropertySheet.java:688)
        at org.openide.explorer.propertysheet.PropertySheet.doSetNodes(PropertySheet.java:467)
        at org.openide.explorer.propertysheet.PropertySheet.access$100(PropertySheet.java:117)
        at org.openide.explorer.propertysheet.PropertySheet$2$1.run(PropertySheet.java:629)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by mbastian** [comment]
Seems to only happen with String[]
