### ISSUE TITLE
Exception when right click on double array in Data Laboratory

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#1359]
Ways to reproduce

1. Create random graph
2. Add new double[] column
3. Set one value for a node, ex: [1.0, 2.0]
4. Right click on that cell

```
java.lang.ClassCastException: [D cannot be cast to java.lang.Number
	at org.gephi.datalab.impl.AttributeColumnsControllerImpl.getRowNumbers(AttributeColumnsControllerImpl.java:590)
	at org.gephi.datalab.plugin.manipulators.values.NumberListStatisticsReport.setup(NumberListStatisticsReport.java:69)
	at org.gephi.desktop.datalab.utils.PopupMenuUtils.createSubMenuFromRowColumn(PopupMenuUtils.java:216)
	at org.gephi.desktop.datalab.tables.popup.NodesPopupAdapter.createPopup(NodesPopupAdapter.java:54)
	at org.gephi.desktop.datalab.tables.popup.AbstractPopupAdapter$1.run(AbstractPopupAdapter.java:84)
[catch] at java.lang.Thread.run(Thread.java:745)
```

**Comment by eduramiba** [comment]
This happens because Number[] is not assignable from double[] but it's from Double[]

**Comment by mbastian** [comment]
Oups, that was the wrong issue number, I meant #1338
