### ISSUE TITLE
0.9.1 Dynamic graph: moving timeline bar throws Exception

### ISSUE THREAD

**Issue by derryx** [gephi/gephi#1381]
I am working on a dynamic graph with version 0.9.1 on Windows7 described in an GEXF-format file.

When I enable the timeline, shrink the timeline bar and then move it to the left I get following Exception:

java.lang.IllegalArgumentException: The view doesn't exist
	at org.gephi.graph.impl.GraphViewStore.checkViewExist(GraphViewStore.java:361)
	at org.gephi.graph.impl.ElementImpl.checkViewExist(ElementImpl.java:762)
	at org.gephi.graph.impl.EdgeImpl.getWeight(EdgeImpl.java:170)
	at org.gephi.visualization.bridge.DataBridge.updateWorld(DataBridge.java:195)
	at org.gephi.visualization.opengl.CompatibilityEngine.updateWorld(CompatibilityEngine.java:105)
	at org.gephi.visualization.scheduler.CompatibilityScheduler.updateWorld(CompatibilityScheduler.java:176)
	at org.gephi.visualization.scheduler.CompatibilityScheduler$2.run(CompatibilityScheduler.java:105)
[catch] at org.gephi.visualization.scheduler.BasicFPSAnimator.run(BasicFPSAnimator.java:34)

System:
Produktversion: Gephi 0.9.0 201510222201
Java: 1.8.0_72; Java HotSpot(TM) 64-Bit Server VM 25.72-b15
System: Windows 7 Version 6.1 wird auf amd64 ausgeführt; Cp1252; de_DE (gephi)

Any suggestions?

CU
Thomas

**Comment by derryx** [comment]
Ah. I have not the latest version. I recheck with 0.9.1.

Sorry.

**Comment by vberten** [comment]
Hi,

I've got a very similar problem, with the nightbuild version of Gephi (gephi-0.9.2-20160401.142447-6-windows.exe). Once the exception occurs, the "graphs views" keeps updating, but the "Context" tab, does not.

Full report attached, bellow is the message : 

Thanks,


[gephi-Exception_ThisViewDoesNotExists.txt](https://github.com/gephi/gephi/files/285899/gephi-Exception_ThisViewDoesNotExists.txt)


java.lang.IllegalArgumentException: The view doesn't exist
	at org.gephi.graph.impl.GraphViewStore.checkViewExist(GraphViewStore.java:361)
	at org.gephi.graph.impl.GraphViewStore.createGraphObserver(GraphViewStore.java:213)
	at org.gephi.graph.impl.GraphModelImpl.createGraphObserver(GraphModelImpl.java:346)
	at org.gephi.desktop.context.ContextRefreshThread.initObserver(ContextRefreshThread.java:75)
	at org.gephi.desktop.context.ContextRefreshThread.run(ContextRefreshThread.java:83)
	at java.util.TimerThread.mainLoop(Timer.java:555)
[catch] at java.util.TimerThread.run(Timer.java:505)
