### ISSUE TITLE
RuntimeException during ForceAtlas2

### ISSUE THREAD

**Issue by sheymann** [gephi/gephi#1400]
I run ForceAtlas2 on a large graph of 18k nodes and 760k edges. After a few iterations the display of the graph freezes.

> java.lang.RuntimeException: Waited 5000ms for: <1345ef31, 177a7981>[count 3, qsz 0, owner <AWT-EventQueue-0-Display-.windows_nil-1-EDT-1>] - <DisplayAnimator>
	at jogamp.common.util.locks.RecursiveLockImpl01Unfairish.lock(RecursiveLockImpl01Unfairish.java:198)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:755)
	at org.gephi.visualization.swing.GLAbstractListener.display(GLAbstractListener.java:322)
	at org.gephi.visualization.scheduler.CompatibilityScheduler$1.run(CompatibilityScheduler.java:97)
[catch] at org.gephi.visualization.scheduler.BasicFPSAnimator.run(BasicFPSAnimator.java:34)

**Comment by mbastian** [comment]
Thanks for the report. This freeze is coming from the old engine's display loop (`RecursiveLockImpl01Unfairish.lock()` timing out inside `GLWindow.display()`), code that Gephi 0.11 replaced entirely with a new visualization engine implementation.

Could you retry on the latest 0.11.x release? If it still reproduces, please open a fresh issue with your OS/GPU details and the graph size that triggers it. Closing this for now as superseded by the new engine.
