### ISSUE TITLE
Getting null pointer error when trying to calculate modularity

### ISSUE THREAD

**Issue by demolaiot** [gephi/gephi#1419]
getting the following error

java.lang.NullPointerException
 at org.gephi.statistics.plugin.Modularity$CommunityStructure.removeNodeFrom(Modularity.java:289)
 at org.gephi.statistics.plugin.Modularity$CommunityStructure.moveNodeTo(Modularity.java:342)
 at org.gephi.statistics.plugin.Modularity$CommunityStructure.access$300(Modularity.java:127)
 at org.gephi.statistics.plugin.Modularity.computeModularity(Modularity.java:507)
 at org.gephi.statistics.plugin.Modularity.execute(Modularity.java:467)
 at org.gephi.statistics.plugin.Modularity.execute(Modularity.java:456)
 at org.gephi.statistics.StatisticsControllerImpl.execute(StatisticsControllerImpl.java:162)
 at org.gephi.statistics.StatisticsControllerImpl$3.run(StatisticsControllerImpl.java:149)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)

**Comment by eduramiba** [comment]
This occurrs when there are parallel (duplicated) edges in the network, which is now possible in Gephi since 0.9.0

**Comment by naco-siren** [comment]
@eduramiba Version 0.9.1 still doesn't work.
Any existence of a directed edge that "duplicates" leads to the malfunction of _Modularity_ calculation.

**Comment by eduramiba** [comment]
Hi @naco-siren this fix is not available in 0.9.1 yet. You can try it in latest 0.9.2 nightly build https://github.com/gephi/gephi#nightly-builds

**Comment by naco-siren** [comment]
@eduramiba  Love you >_<

**Comment by darkoc** [comment]
I get the same error in 0.9.1 when using the tookit (from a Java program, not the UI).
The graph is directed so the edges are not really duplicates. 
Interestingly enough, when computing the modularity through the UI in Gephi 0.9.1 on the same graph it works ?!

**Comment by darkoc** [comment]
The modularity doesn't work in tookit 0.9.2-SNAPSHOT either. It is getting stuck in an infinite while loop.

**Comment by eduramiba** [comment]
Hi, the lastest toolkit nightly build is prior to this fix. I just started a new build to refresh it. https://travis-ci.org/gephi/gephi-toolkit/builds/109715048
