### ISSUE TITLE
Can not append file

### ISSUE THREAD

**Issue by friggx** [gephi/gephi#1463]
I open graphml file, then open another one graphml with flug "Append Graph". 
And i get exception. How to create a file which would not receive such errors ?

```
java.lang.IllegalArgumentException: The object class does not match with the column type (java.lang.String)
    at org.gephi.graph.impl.ElementImpl.checkType(ElementImpl.java:783)
    at org.gephi.graph.impl.ElementImpl.setAttribute(ElementImpl.java:324)
    at org.gephi.graph.impl.ElementImpl.setAttribute(ElementImpl.java:315)
    at org.gephi.io.processor.plugin.AbstractProcessor.flushToElementAttributes(AbstractProcessor.java:194)
    at org.gephi.io.processor.plugin.AbstractProcessor.flushToNode(AbstractProcessor.java:154)
    at org.gephi.io.processor.plugin.DefaultProcessor.process(DefaultProcessor.java:169)
    at org.gephi.io.processor.plugin.AppendProcessor.process(AppendProcessor.java:88)
    at org.gephi.io.importer.impl.ImportControllerImpl.process(ImportControllerImpl.java:292)
    at org.gephi.desktop.importer.DesktopImportControllerUI.finishImport(DesktopImportControllerUI.java:638)
    at org.gephi.desktop.importer.DesktopImportControllerUI.finishImport(DesktopImportControllerUI.java:557)
    at org.gephi.desktop.importer.DesktopImportControllerUI.access$100(DesktopImportControllerUI.java:102)
    at org.gephi.desktop.importer.DesktopImportControllerUI$3.run(DesktopImportControllerUI.java:187)
Caused: java.lang.RuntimeException
    at org.gephi.desktop.importer.DesktopImportControllerUI$3.run(DesktopImportControllerUI.java:190)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by friggx** [comment]
I realized that the problem lies in the fact that a new graph although it has the same titles for the NodeColumn, but also has a different id in these columns. Tell me, how you can change the identifier of the Node column ?
I tried to change to work with the container,
`Container container = importController.importFile (file); 
`but I did not find solutions, plz Help

**Comment by friggx** [comment]
I mean how change key id in graphml, when I import file?

**Comment by eduramiba** [comment]
Do you get an exception in latest 0.9.2 snapshot? https://github.com/gephi/gephi#nightly-builds
Graphml keys can provide an 'attr.name' (the title) and and 'id'.
