### ISSUE TITLE
Dynamic graph, execption when playing with timeline (re-opening #1381)

### ISSUE THREAD

**Issue by vberten** [gephi/gephi#1500]
This bug was already mentioned (#1381), marked as closed, but I still have it with the snapshot version of Gephi 0.9.2, and 0.9.1

The exception occurs when playing with the timeline, after a few manipulations. Once the exception occurs, the "graphs views" keeps updating, but the "Context" tab does not.

Full report attached, below is the message :
[gephi-Exception_ThisViewDoesNotExists.txt](https://github.com/gephi/gephi/files/290493/gephi-Exception_ThisViewDoesNotExists.txt)

Thanks,

java.lang.IllegalArgumentException: The view doesn't exist
at org.gephi.graph.impl.GraphViewStore.checkViewExist(GraphViewStore.java:361)
at org.gephi.graph.impl.GraphViewStore.createGraphObserver(GraphViewStore.java:213)
at org.gephi.graph.impl.GraphModelImpl.createGraphObserver(GraphModelImpl.java:346)
at org.gephi.desktop.context.ContextRefreshThread.initObserver(ContextRefreshThread.java:75)
at org.gephi.desktop.context.ContextRefreshThread.run(ContextRefreshThread.java:83)
at java.util.TimerThread.mainLoop(Timer.java:555)
[catch] at java.util.TimerThread.run(Timer.java:505)

**Comment by eduramiba** [comment]
Hi,
This should now work with latest 0.9.2 snapshot.
Can you try please?
