### ISSUE TITLE
NullPointerException on Modularity Statistics with gexf with kind / parallel nodes.

### ISSUE THREAD

**Issue by totetmatt** [gephi/gephi#1526]
Opening a gexf with kind defined on edges : 

Running Modularity raise an error and makes gephi unusable .

java.lang.NullPointerException
    at org.gephi.graph.impl.EdgeStore$UndirectedIterator.hasNext(EdgeStore.java:1771)
    at org.gephi.statistics.plugin.Modularity$CommunityStructure.<init>(Modularity.java:184)
    at org.gephi.statistics.plugin.Modularity.execute(Modularity.java:477)
    at org.gephi.statistics.plugin.Modularity.execute(Modularity.java:469)
    at org.gephi.statistics.StatisticsControllerImpl.execute(StatisticsControllerImpl.java:162)
    at org.gephi.statistics.StatisticsControllerImpl$3.run(StatisticsControllerImpl.java:149)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by eduramiba** [comment]
Looks similar to #1419 Did you install the latest updates?

**Comment by totetmatt** [comment]
Yeap, 0.9.1 "No update available, you're up to date"

**Comment by eduramiba** [comment]
Could you share a sample graph/steps to reproduce this please?

**Comment by eduramiba** [comment]
Confirmed, graphstore getEdges(n1, n2) only would return edgest without a kind. Also, this raises a null pointer exception if there are no edges without kind for the nodes pair.

**Comment by eduramiba** [comment]
Hi, this should be fixed in 0.9.2-SNAPSHOT latest build.
