### ISSUE TITLE
ArrayIndexOutOfBoundsException in AutoLayout.InterpolateDynamicProperty

### ISSUE THREAD

**Issue by stuchl4n3k** [gephi/gephi#1532]
See while loop at the line 335 at https://github.com/gephi/gephi/blob/master/modules/LayoutPlugin/src/main/java/org/gephi/layout/plugin/AutoLayout.java#L335:

``` java
while (thresholds[currentIndex] < ratio && currentIndex < thresholds.length) {
    currentIndex++;
}
```

Please switch the order of those conditions, otherwise it can cause access to `thresholds[thresholds.length]` resulting in:

```
java.lang.ArrayIndexOutOfBoundsException: 2
    at org.gephi.layout.plugin.AutoLayout$InterpolateDynamicProperty.getValue(AutoLayout.java:335)
    at org.gephi.layout.plugin.AutoLayout.setProperties(AutoLayout.java:138)
    at org.gephi.layout.plugin.AutoLayout.execute(AutoLayout.java:124)
```

**Comment by eduramiba** [comment]
Thanks for the report!
