### ISSUE TITLE
NPE with trying to filter by partition with a null value

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#1563]
Ways to reproduce: 
1) Take a graph with partitions, like modularity class
2) Remove one value in data laboratory, the cell is now null
3) Try to filter the graph by the partition column

```
java.lang.NullPointerException
	at org.gephi.ui.filters.plugin.partition.PartitionPanel$PartWrapper.toString(PartitionPanel.java:203)
	at javax.swing.DefaultListCellRenderer.getListCellRendererComponent(DefaultListCellRenderer.java:151)
	at org.gephi.ui.filters.plugin.partition.PartitionPanel$1.getListCellRendererComponent(PartitionPanel.java:92)
```

**Comment by mbastian** [comment]
Fixed in 0.9.1 branch
