### ISSUE TITLE
Range constructor

### ISSUE THREAD

**Issue by HelenaGallego** [gephi/gephi#1600]
When defining a Range with the API in order to filter the graph, the constructor seems to throw an exception saying that the classes are not the same but I have defined the range values with the same class.

This is the code:

Integer low = 3;
Integer high = Integer.MAX_VALUE;         
System.out.println(low.getClass());
System.out.println(high.getClass());
Range range = new Range(low, high);

This is the output that I get:

class java.lang.Integer
class java.lang.Integer
Exception in thread "main" java.lang.IllegalArgumentException: Lower and upper must be the same class
	at org.gephi.filters.api.Range.<init>(Range.java:75)
	at org.gephi.filters.api.Range.<init>(Range.java:82)
	at org.gephi.filters.api.Range.<init>(Range.java:87)
	at org.gephi.filters.FilterProcessor.init(FilterProcessor.java:232)
	at org.gephi.filters.FilterProcessor.processEdgeFilter(FilterProcessor.java:150)
	at org.gephi.filters.FilterProcessor.process(FilterProcessor.java:110)
	at org.gephi.filters.FilterControllerImpl.filter(FilterControllerImpl.java:262)

**Comment by Joseph-Schafer** [comment]
If you happen to still remember, how did you solve this issue? I'm running into this with my own code. Thanks!

**Comment by KiranGershenfeld** [comment]
> If you happen to still remember, how did you solve this issue? I'm running into this with my own code. Thanks!

Did you ever solve it?
