### ISSUE TITLE
What's this exception?

### ISSUE THREAD

**Issue by Kalethars** [gephi/gephi#1620]
Exception in thread "PreviewRefreshLoop" java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at java.util.AbstractCollection.toArray(AbstractCollection.java:196)
	at org.gephi.preview.PreviewModelImpl.getItemTypes(PreviewModelImpl.java:213)
	at org.gephi.preview.PreviewModelImpl.getGraphicsCanvasSize(PreviewModelImpl.java:281)
	at org.gephi.preview.G2DRenderTargetBuilder$G2DGraphics.getSheetCanvasSize(G2DRenderTargetBuilder.java:253)
	at org.gephi.preview.G2DRenderTargetBuilder$G2DGraphics.refresh(G2DRenderTargetBuilder.java:191)
	at org.gephi.preview.G2DRenderTargetBuilder$G2DTargetImpl.refresh(G2DRenderTargetBuilder.java:154)
	at org.gephi.toolkit.demos.plugins.preview.PreviewSketch$RefreshLoop$1.run(PreviewSketch.java:222)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by eduramiba** [comment]
Looks like a bug. What's the steps to reproduce?

**Comment by liuyanghah** [comment]
Hi，it‘s me again. Follow exception reported when i try to refresh previewJframe while the layout was running. Just like the preview in software gephi. 

Exception in thread "PreviewRefreshLoop" java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
	at java.util.HashMap$KeyIterator.next(HashMap.java:841)
	at java.util.AbstractCollection.toArray(AbstractCollection.java:188)
	at org.gephi.preview.PreviewModelImpl.getItemTypes(PreviewModelImpl.java:213)
	at org.gephi.preview.PreviewModelImpl.getGraphicsCanvasSize(PreviewModelImpl.java:281)
	at org.gephi.preview.G2DRenderTargetBuilder$G2DGraphics.getSheetCanvasSize(G2DRenderTargetBuilder.java:253)
	at org.gephi.preview.G2DRenderTargetBuilder$G2DGraphics.refresh(G2DRenderTargetBuilder.java:191)
	at org.gephi.preview.G2DRenderTargetBuilder$G2DTargetImpl.refresh(G2DRenderTargetBuilder.java:154)
	at frame.PreviewSketch$RefreshLoop$1.run(PreviewSketch.java:222)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by liuyanghah** [comment]
[txt.txt](https://github.com/gephi/gephi/files/922161/txt.txt)
the related code are int this txt.
Actually，I am a master student，and i want to use gephi to finish my master paper. If you would like to share more demos to me，with the functions just like the gephi，I would be very grateful. (p.s. Of course, I will explain your help in the paper)

**Comment by eduramiba** [comment]
Seems to be a synchronization problem when refreshing. Anyway @liuyanghah your frame creation code should probably be outside of the loop.

**Comment by mbastian** [comment]
Closing old issue. I think this one got fixed as we had an overhaul of the preview refresh code before 0.9.3 version. Please reopen if it still occurs.
