### ISSUE TITLE
ArrayIndexOutOfBoundsException on when deleting nodes

### ISSUE THREAD

**Issue by vberten** [gephi/gephi#1623]
I got frequently the following error when deleting a node in Gephi 0.9.2 (snapshot), but also in 0.9.1, from the overview or from the data lab.

It's difficult to reproduce: it usually happens after a few node deletions, but not always with the same node.
It sounds to be "partially deterministic" ; if a delete node a, b, c, exceptions occurs always with node c, but if I delete in another order, if occurs on a different node (not necessarily the third one). It seems that it occurs mainly with node with high degree. 
Note that I use multi-edge graphs, with several thousands nodes,

 
java.lang.ArrayIndexOutOfBoundsException: 67
	at org.gephi.graph.impl.EdgeStore.removeInEdge(EdgeStore.java:261)
	at org.gephi.graph.impl.EdgeStore.remove(EdgeStore.java:648)
	at org.gephi.graph.impl.EdgeStore$EdgeInOutIterator.remove(EdgeStore.java:1365)
	at org.gephi.graph.impl.GraphStore.removeNode(GraphStore.java:242)
	at org.gephi.datalab.impl.GraphElementsControllerImpl.removeNode(GraphElementsControllerImpl.java:454)
	at org.gephi.datalab.impl.GraphElementsControllerImpl.deleteNodes(GraphElementsControllerImpl.java:187)
	at org.gephi.datalab.plugin.manipulators.nodes.DeleteNodes.execute(DeleteNodes.java:70)
[catch] at org.gephi.datalab.api.DataLaboratoryHelper$5.run(DataLaboratoryHelper.java:325)

**Comment by eduramiba** [comment]
Looks like a locking/concurrency issue, possibly related to https://github.com/gephi/graphstore/issues/129

**Comment by mbastian** [comment]
Hi, thanks for the report we've identified the issue. It was related to multi-graph implementation. The fix will be included in the upcoming 0.9.3 release.
