### ISSUE TITLE
Error trying to show any graph

### ISSUE THREAD

**Issue by aortigosa** [gephi/gephi#1627]
Configuration:
Gephi 0.9.1
Java: 1.8.0_74; Java HotSpot(TM) 64-Bit Server VM 25.74-b02
Runtime: Java(TM) SE Runtime Environment 1.8.0_74-b02
System: Mac OS X version 10.11.6 running on x86_64; UTF-8; en_US (gephi)

This error, trying to preview any graph:

[INFO] [PersistenceManager.getTopComponentForID] Problem when deserializing TopComponent for tcID:'PreviewSettingsTopComponent'. Reason: Top component PreviewSettingsTopComponent could not be located or loaded from Components folder. 
[SEVERE] null 
java.lang.NullPointerException
	at org.gephi.desktop.preview.PreviewUIControllerImpl$3.run(PreviewUIControllerImpl.java:217)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Any help? Thanks in advance.

**Comment by eduramiba** [comment]
Hi,
You can try to delete your user directory (see https://github.com/gephi/gephi/wiki/Troubleshooting), since there might be some corrupted files.

**Comment by aortigosa** [comment]
Dear Sir, I really appreciate your help, it worked.

Best,

A:

**Comment by eduramiba** [comment]
Great! :)
