### ISSUE TITLE
v0.9.1 unable to read v0.9 gephi file

### ISSUE THREAD

**Issue by rbelew** [gephi/gephi#1691]
## Expected Behavior

I'd expect this minor revision to be able to read a slightly earlier version

## Current Behavior

Null pointer exception, reliably across multiple 0.9 files

## Your Environment

* Version used: Gephi 0.9.1
* Operating System: MacOS 10.12.3

java.lang.NullPointerException
	at org.gephi.graph.impl.Serialization.deserializeGraphStore(Serialization.java:295)
	at org.gephi.graph.impl.Serialization.deserialize(Serialization.java:2040)
	at org.gephi.graph.impl.Serialization.deserializeConfiguration(Serialization.java:1075)
	at org.gephi.graph.impl.Serialization.deserialize(Serialization.java:2100)
	at org.gephi.graph.impl.Serialization.deserializeGraphModel(Serialization.java:242)
	at org.gephi.graph.api.GraphModel$Serialization.read(GraphModel.java:135)
	at org.gephi.graph.GraphPersistenceProvider.readBytes(GraphPersistenceProvider.java:77)
	at org.gephi.project.io.LoadTask.readWorkspaceChildrenBytes(LoadTask.java:326)
	at org.gephi.project.io.LoadTask.run(LoadTask.java:129)
	at org.gephi.desktop.project.ProjectControllerUIImpl$6.run(ProjectControllerUIImpl.java:297)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by rbelew** [comment]
(don't seem able to attach the 0.9 gephi file to test?)

**Comment by eduramiba** [comment]
Yeah it should work, it must be a bug. You can try to attach it as a zip.

**Comment by rbelew** [comment]
thanks!  sample file attached

**Comment by eduramiba** [comment]
Hi, you will need to do it in github, email attachments are not automatically available in github.

**Comment by rbelew** [comment]
[tenorMadness_090.gephi.zip](https://github.com/gephi/gephi/files/859657/tenorMadness_090.gephi.zip)
ok, zipping the .gephi file seems to work

**Comment by eduramiba** [comment]
Please test the fix with the latest 0.9.2 snapshot https://github.com/gephi/gephi#nightly-builds
