### ISSUE TITLE
error trying to open gephi

### ISSUE THREAD

**Issue by susanarosano** [gephi/gephi#1724]
## Expected Behavior
to open Gephi to start working with it

## Current Behavior
I am getting an error when trying to open Gephi, it shows the error "Can't find the name of intel ICD OpenGL driver", 

## Steps to Reproduce

1. Install Gephi and open it
2.
3.
4.

## Context
I contacted intel for help, they were connected to my computer and updated the driver. We test gephi unsuccessful. The issue is happening with both video cards, the Nvidia one and the Intel® one so seems the problem is with gephi and not with intel

I have to finish my homework and I don't have enough time to finish it.

## Your Environment

* Version used: Gephi 0.9.1
* Operating System: Windows 10

**Comment by eduramiba** [comment]
This seems a new problem with JOGL. Please try to:

* Update your Java version
* Run Gephi as administrator

Workarounds would be using a virtual machine

**Comment by ldparadise** [comment]
I'm having the same issue, and neither running Gephi as an administrator nor updating my Java version fixed it. I tried downloading an earlier Gephi, 8.2. but that doesn't work either, just brings up the loading screen and then disappears. Are there other earlier versions of Gephi that don't have this issue?

**Comment by susanarosano** [comment]
hello,

I tried also but problem is not solved. I am using the last Gephi version.

**Comment by methodds** [comment]
hi,
my gephi starts but then does not initialize graphs and shows an exception at the bottom right:
`` 
com.jogamp.opengl.GLException: Profile GL2 is not available on X11GraphicsDevice[type .x11, connection :0, unitID 0, handle 0x0, owner false, ResourceToolkitLock[obj 0x148976cd, isOwner false, <10b6f084, 55b47cf6>[count 0, qsz 0, owner <NULL>]]], but: []
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:991)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1004)
	at org.gephi.visualization.swing.GLAbstractListener.getCaps(GLAbstractListener.java:174)
	at org.gephi.visualization.swing.NewtGraphCanvas.<init>(NewtGraphCanvas.java:66)
	at org.gephi.visualization.VizController.createNewtCanvas(VizController.java:302)
	at org.gephi.visualization.VizController.initInstances(VizController.java:125)
	at org.gephi.visualization.VizController.getInstance(VizController.java:88)
	at org.gephi.visualization.VizModel.defaultValues(VizModel.java:135)
	at org.gephi.visualization.VizModel.<init>(VizModel.java:95)
	at org.gephi.visualization.VizModelPersistenceProvider.readXML(VizModelPersistenceProvider.java:76)
	at org.gephi.project.io.LoadTask.readWorkspaceChildrenXML(LoadTask.java:297)
	at org.gephi.project.io.LoadTask.run(LoadTask.java:127)
	at org.gephi.desktop.project.ProjectControllerUIImpl$6.run(ProjectControllerUIImpl.java:297)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
``
is this related or a different issue?

**Comment by flavia01** [comment]
Hi
I have the same issue of @susanarosano 
anyone solved it?
Thanks

**Comment by mizvol** [comment]
Same issue as @methodds.

`com.jogamp.opengl.GLException: Profile GL2 is not available on X11GraphicsDevice[type .x11, connection :0, unitID 0, handle 0x0, owner false, ResourceToolkitLock[obj 0x5cfca66c, isOwner false, <58c3392b, 1dc1ac57>[count 0, qsz 0, owner <NULL>]]], but: []
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:991)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1004)
	at org.gephi.visualization.swing.GLAbstractListener.getCaps(GLAbstractListener.java:174)
	at org.gephi.visualization.swing.NewtGraphCanvas.<init>(NewtGraphCanvas.java:66)
	at org.gephi.visualization.VizController.createNewtCanvas(VizController.java:302)
	at org.gephi.visualization.VizController.initInstances(VizController.java:125)
	at org.gephi.visualization.VizController.getInstance(VizController.java:88)
	at org.gephi.visualization.component.VizBarController.createDefaultGroups(VizBarController.java:99)
	at org.gephi.visualization.component.VizBarController.<init>(VizBarController.java:88)
	at org.gephi.visualization.component.GraphTopComponent.initCollapsePanel(GraphTopComponent.java:118)
	at org.gephi.visualization.component.GraphTopComponent.access$000(GraphTopComponent.java:77)
	at org.gephi.visualization.component.GraphTopComponent$1$1.run(GraphTopComponent.java:99)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by rzo1** [comment]
I can confirm on my Thinkpad T460p (Intel and NVIDIA graphics) running Windows 10 LTSB, latest Oracle JDK and Gephi 0.9.1

**Comment by mizvol** [comment]
Ubuntu 16.04.
Recent updates fixed the problem.

**Comment by MontePino** [comment]
I ran into the same error message "Can't find the name of intel ICD OpenGL driver" while running Gephi with latest Java JRE. 
The hint of @rzo1 worked for me. After replacing my Java version by JDK, Gephi starts without problems. 
Thanks a lot!

**Comment by Neergaard** [comment]
I tried installing Gephi 0.9.1 on my Razer Blade (2017) with integrated Intel HD and discrete NVIDIA graphics on Windows 10 with latest JRE, which gave me the same error with the ICD OpenGL driver.

Confirming @rzo1 and @MontePino's comments, my installation worked after removing JRE and installing JDK instead.

**Comment by imranakram** [comment]
After installing JDK v8, I also had to update the drivers for Display Adapters (graphics card) on Windows 10. You can find it in Device Manager -> <Computer Name> -> Display Adapters. I Have Gephi 0.9.2.

**Comment by brandonleekramer** [comment]
I'm running Gephi 0.9.2 on Windows 10 with an NVIDIA GeForce GTX 1660 Ti graphics card. Just updated the driver, but I am still running into the same error of "Can't find the Intel Graphics" once the startup gets to "Starting Modules..." Running the 64 bit .exe didn't change anything.

**Comment by krisf93** [comment]
Anyone have a solution for this? Having the same problem and not sure how others are able to make it work.

**Comment by AlexisParra** [comment]
Installing JDK and changing the path in gephi.conf to point on JDK dir (don't forget to uncomment) worked fine for me.

**Comment by krisf93** [comment]
> Installing JDK and changing the path in gephi.conf to point on JDK dir (make sure it's not commented out) worked fine for me.

Thanks for the recommendation AlexisParra. Can you tell me how you modified your gephi.conf file? When I try to modify as recommended here (https://github.com/gephi/gephi/issues/1787) with the JDK I Gephi says that it cannot find Java (but with the JRE I didn't get the Java issue and got the issue on this page instead). Hope that makes sense.

**Comment by AlexisParra** [comment]
See comment in gephi.conf:
```
#default location of JDK/JRE, can be overridden by using --jdkhome <dir> switch
#jdkhome="/path/to/jdk"
```
In my case:

`jdkhome="C:\Program Files\Java\jdk-12.0.1"`

**Comment by brandonleekramer** [comment]
I just got back around to this and still had some trouble opening Gephi (still got stuck starting the modules). However, after downloading the most recent JDK and changing the path as AlexisParra suggested, I was able to open Gephi using the gephi64.exe in the bin folder. Thanks for the feedback!

**Comment by BrockWester** [comment]
I just recently received this same error as well.  I have a Windows 10 PC (Razer Blade 15) with an intel graphics card and an NVIDIA graphics card.  I tried opening both the 32-bit and 64-bit versions, on regular and administrator settings - neither solved the problem.   Through the NVIDIA control panel, you're able to change the 3D graphics settings and specify which graphics cards are used with specific applications - none of the settings changes solved the problem.  My work IT had recently updated JRE 1.8 with a 32-bit version, so I tried installing the most recent 64 bit version - this did not solve the problem.  

**What solved the problem:**  I was using thunderbolt cable to connect to an external monitor, and I was using the Windows display settings for "Second Screen Only".... in changing this setting to "Duplicate", the Open GL error no longer appeared at run time.

**Comment by lrossi79** [comment]
> I just recently received this same error as well. I have a Windows 10 PC (Razer Blade 15) with an intel graphics card and an NVIDIA graphics card. I tried opening both the 32-bit and 64-bit versions, on regular and administrator settings - neither solved the problem. Through the NVIDIA control panel, you're able to change the 3D graphics settings and specify which graphics cards are used with specific applications - none of the settings changes solved the problem. My work IT had recently updated JRE 1.8 with a 32-bit version, so I tried installing the most recent 64 bit version - this did not solve the problem.
> 
> **What solved the problem:** I was using thunderbolt cable to connect to an external monitor, and I was using the Windows display settings for "Second Screen Only".... in changing this setting to "Duplicate", the Open GL error no longer appeared at run time.

I can confirm this issue on the same system and set-up.

**Comment by joshhansen** [comment]
I'm getting this on Fedora 32 Linux. Changing Java versions from 1.8 doesn't work---always an error on startup (with 11 and 15). I can run OpenGL apps like glxgears. Running as superuser seems to make no difference. Gephi 0.9.2 with all updates installed.

**Comment by mbastian** [comment]
Thanks for the report. "Can't find the name of intel ICD OpenGL driver" comes from the old engine's driver-detection code, which Gephi 0.11 replaced with a new visualization engine implementation.

Could you retry on the latest 0.11.x release with an updated Intel driver? If it still reproduces, please open a fresh issue with your Windows version and driver version. Closing this for now as superseded by the new engine.
