### ISSUE TITLE
NPE 	at EdgeTypeBuilder$EdgeTypeFilter.evaluate when using an EdgeType subfilter on a Partion

### ISSUE THREAD

**Issue by arnehaber** [gephi/gephi#1727]
NPE 	at EdgeTypeBuilder$EdgeTypeFilter.evaluate when using an EdgeType subfilter on a Partion.

## Expected Behavior
No NPE.

## Current Behavior
NPE. Also the Filtering Process will not exit.

## Steps to Reproduce

1. defining a partion query
2. add an edge type subfilter so that zero edges will be the result (I suggest the latter part is the problem, since the first edge type is immediatly selected)

## Context
I tried to filter nodes which are connected in a specific way.

## Your Environment

* Version used: Gephi 0.9.1
* Operating System: Win 7 64 bit

java.lang.NullPointerException
	at org.gephi.filters.plugin.edge.EdgeTypeBuilder$EdgeTypeFilter.evaluate(EdgeTypeBuilder.java:122)
	at org.gephi.filters.plugin.edge.EdgeTypeBuilder$EdgeTypeFilter.evaluate(EdgeTypeBuilder.java:103)
	at org.gephi.filters.FilterProcessor.processEdgeFilter(FilterProcessor.java:160)
	at org.gephi.filters.FilterProcessor.process(FilterProcessor.java:113)
	at org.gephi.filters.FilterThread.filter(FilterThread.java:149)
[catch] at org.gephi.filters.FilterThread.run(FilterThread.java:121)

**Comment by mbastian** [comment]
Hi, I could not reproduce this issue with the latest version. Or maybe I didn't have a proper dataset to do it. Please reopen if that's still the case for you.
