### ISSUE TITLE
AutoLayout error

### ISSUE THREAD

**Issue by aoyuanbo** [gephi/gephi#1734]
## Expected Behavior
The following code I copied is from  https://gephi.org/gephi-toolkit/0.9.1/apidocs/ 
```
AutoLayout autoLayout = new AutoLayout(1, TimeUnit.MINUTES);
autoLayout.setGraphModel(graphModel);

ForceAtlasLayout forceAtlasLayout = new ForceAtlasLayout(null);

AutoLayout.DynamicProperty gravity = AutoLayout.createDynamicProperty("Gravity", new Double[]{80., 400.0}, new float[]{0f, 1f});

AutoLayout.DynamicProperty speed = AutoLayout.createDynamicProperty("Speed", new Double[]{1.2, 0.3}, new float[]{0f, 1f});

AutoLayout.DynamicProperty repulsion = AutoLayout.createDynamicProperty("Repulsion strength", new Double[]{3000.0, 6000.}, new float[]{0f, 1f});

AutoLayout.DynamicProperty freeze = AutoLayout.createDynamicProperty("Autostab Strength", new Double(100.0), 0f);

autoLayout.addLayout(forceAtlasLayout, 0.8f, new AutoLayout.DynamicProperty[]{gravity, speed, repulsion, freeze});
```
## Current Behavior
.When I run the program error that is 
 _java.lang.IllegalArgumentException: Gravity property cannot be found in layout_
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.1
* Operating System:

**Comment by eduramiba** [comment]
I think this still fails due to translated property names. Try to force english language in java or write the name in your language.

**Comment by eduramiba** [comment]
Does it work if you use the canonical property names like in example https://github.com/gephi/gephi-toolkit-demos/blob/master/src/main/java/org/gephi/toolkit/demos/WithAutoLayout.java ?

**Comment by eduramiba** [comment]
Did it work?

**Comment by EugenioLaghi** [comment]
I have the same problem, then I tried with the following

```
forceAtlas.gravity.name
forceAtlas.speed.name
forceAtlas.repulsionStrength.name
forceAtlas.autostabStrength.name
```

and only autostabStrength didn't work.

Also, it's not clear to me where I can find the list of these canonical property names, I just guessed the names of these starting from the ones provided in the examples. Are them anywhere on the javadocs?

**Comment by eduramiba** [comment]
Hi,
You can call ```layout.getProperties()``` on any layout instance https://gephi.org/gephi-toolkit/0.9.1/apidocs/org/gephi/layout/spi/Layout.html#getProperties-- or just check them here https://github.com/gephi/gephi/blob/master/modules/LayoutPlugin/src/main/java/org/gephi/layout/plugin/forceAtlas/ForceAtlasLayout.java#L264

**Comment by eduramiba** [comment]
Did it work?

**Comment by wybert** [comment]
> Hi,
> You can call `layout.getProperties()` on any layout instance https://gephi.org/gephi-toolkit/0.9.1/apidocs/org/gephi/layout/spi/Layout.html#getProperties-- or just check them here https://github.com/gephi/gephi/blob/master/modules/LayoutPlugin/src/main/java/org/gephi/layout/plugin/forceAtlas/ForceAtlasLayout.java#L264

I tired,
```java
        LayoutProperty[] ps = forceAtlas2Layout.getProperties();

        for (LayoutProperty property : ps) {
            System.out.println( property.getProperty());
//            System.out.println( property.getCategory());
            System.out.println( property.getCanonicalName());
        }
```
and ajust the code as,

```
        AutoLayout.DynamicProperty strongerGravity = AutoLayout.createDynamicProperty("ForceAtlas2.strongGravityMode.name", Boolean.TRUE, 0.1f);
        AutoLayout.DynamicProperty scaling = AutoLayout.createDynamicProperty("ForceAtlas2.scalingRatio.name",100,0.2f);
        AutoLayout.DynamicProperty adjust = AutoLayout.createDynamicProperty("ForceAtlas2.adjustSizes.name",  Boolean.TRUE, 0.1f);
//        AutoLayout.DynamicProperty repulsion = AutoLayout.createDynamicProperty("Repulsion strength", new Double[]{3000.0, 6000.}, new float[]{0f, 1f}, AutoLayout.Interpolation.LINEAR);
//        AutoLayout.DynamicProperty freeze = AutoLayout.createDynamicProperty("Autostab Strength", new Double(100.0), 0f);
        autoLayout.addLayout(forceAtlas2Layout, 1.0f, new AutoLayout.DynamicProperty[]{strongerGravity, scaling, adjust});
```
Then I got error,

java.lang.IllegalArgumentException: java.lang.ClassCastException@62150f9e
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openide.nodes.PropertySupport$Reflection.setValue(PropertySupport.java:335)
	at org.gephi.layout.plugin.AutoLayout.setProperties(AutoLayout.java:144)
	at org.gephi.layout.plugin.AutoLayout.execute(AutoLayout.java:125)
	at org.gephi.toolkit.demos.WithAutoLayout.script(WithAutoLayout.java:142)
	at org.gephi.toolkit.demos.Main.main(Main.java:38)

**Comment by wybert** [comment]
> Did it work?

I think it's work! I get the result of the layout graph, but still  the above `IllegalArgumentException`
