### ISSUE TITLE
Cytoscape to Gephi

### ISSUE THREAD

**Issue by lauraneckstein** [gephi/gephi#1753]
## Current Behavior
When I try to import a graphml file from cytoscape I get this error. Help!
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.1
* Operating System: Mac OS Sierra

java.lang.RuntimeException: Can't modify the read-only 'id' column
	at org.gephi.graph.impl.ElementImpl.checkReadOnlyColumn(ElementImpl.java:727)
	at org.gephi.graph.impl.ElementImpl.setAttribute(ElementImpl.java:321)
	at org.gephi.graph.impl.ElementImpl.setAttribute(ElementImpl.java:315)
	at org.gephi.io.processor.plugin.AbstractProcessor.flushToElementAttributes(AbstractProcessor.java:194)
	at org.gephi.io.processor.plugin.AbstractProcessor.flushToNode(AbstractProcessor.java:154)
	at org.gephi.io.processor.plugin.DefaultProcessor.process(DefaultProcessor.java:169)
	at org.gephi.io.processor.plugin.DefaultProcessor.process(DefaultProcessor.java:102)
	at org.gephi.io.importer.impl.ImportControllerImpl.process(ImportControllerImpl.java:292)
	at org.gephi.desktop.importer.DesktopImportControllerUI.finishImport(DesktopImportControllerUI.java:637)
	at org.gephi.desktop.importer.DesktopImportControllerUI.access$200(DesktopImportControllerUI.java:102)
	at org.gephi.desktop.importer.DesktopImportControllerUI$6.run(DesktopImportControllerUI.java:285)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by eduramiba** [comment]
Does this happen with latest 0.9.2 snapshot? https://github.com/gephi/gephi#nightly-builds

**Comment by lauraneckstein** [comment]
Yup, still getting : java.lang.RuntimeException: Can't modify the read-only 'id' column
	at org.gephi.graph.impl.ElementImpl.checkReadOnlyColumn(ElementImpl.java:727)
	at org.gephi.graph.impl.ElementImpl.setAttribute(ElementImpl.java:321)
	at org.gephi.graph.impl.ElementImpl.setAttribute(ElementImpl.java:315)
	at org.gephi.io.processor.plugin.AbstractProcessor.flushToElementAttributes(AbstractProcessor.java:259)
	at org.gephi.io.processor.plugin.AbstractProcessor.flushToNode(AbstractProcessor.java:186)
	at org.gephi.io.processor.plugin.DefaultProcessor.process(DefaultProcessor.java:181)
	at org.gephi.io.processor.plugin.DefaultProcessor.process(DefaultProcessor.java:104)
	at org.gephi.io.importer.impl.ImportControllerImpl.process(ImportControllerImpl.java:331)
	at org.gephi.desktop.importer.DesktopImportControllerUI.finishImport(DesktopImportControllerUI.java:566)
	at org.gephi.desktop.importer.DesktopImportControllerUI.access$000(DesktopImportControllerUI.java:104)
	at org.gephi.desktop.importer.DesktopImportControllerUI$3.run(DesktopImportControllerUI.java:288)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by eduramiba** [comment]
Can you share a file to reproduce this please?

**Comment by lauraneckstein** [comment]
[Kaplan Network.graphml.zip](https://github.com/gephi/gephi/files/1146291/Kaplan.Network.graphml.zip)

**Comment by lauraneckstein** [comment]
updates? sorry, what does a milestone mean?

**Comment by eduramiba** [comment]
It will soon be fixed for version 0.9.2

**Comment by lauraneckstein** [comment]
how is this coming?

**Comment by eduramiba** [comment]
I will probably be able to check it later this week

**Comment by eduramiba** [comment]
Fixed for 0.9.2, please try with the latest 0.9.2 snapshot later: https://github.com/gephi/gephi#nightly-builds
