### ISSUE TITLE
Exception with no-merge strategy in some cases. Incompatible edge should not be created

### ISSUE THREAD

**Issue by eduramiba** [gephi/gephi#1802]
```java
java.lang.IllegalArgumentException: An directed edge already exists
	at org.gephi.graph.impl.EdgeStore.checkUndirectedNotExist(EdgeStore.java:1002)
	at org.gephi.graph.impl.EdgeStore.add(EdgeStore.java:546)
	at org.gephi.graph.impl.GraphStore.addEdge(GraphStore.java:163)
	at org.gephi.io.processor.plugin.DefaultProcessor.process(DefaultProcessor.java:269)
	at org.gephi.io.processor.plugin.DefaultProcessor.process(DefaultProcessor.java:105)
	at org.gephi.io.importer.impl.ImportControllerImpl.process(ImportControllerImpl.java:331)
	at org.gephi.desktop.importer.DesktopImportControllerUI.finishImport(DesktopImportControllerUI.java:585)
	at org.gephi.desktop.importer.DesktopImportControllerUI.access$000(DesktopImportControllerUI.java:106)
	at org.gephi.desktop.importer.DesktopImportControllerUI$3.run(DesktopImportControllerUI.java:307)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pwichmann** [comment]
This still exists, it seems.

```
[SEVERE]  
java.lang.IllegalArgumentException: An directed edge already exists
	at org.gephi.graph.impl.EdgeStore.checkUndirectedNotExist(EdgeStore.java:1002)
	at org.gephi.graph.impl.EdgeStore.add(EdgeStore.java:546)
	at org.gephi.graph.impl.GraphStore.addEdge(GraphStore.java:163)
	at org.gephi.io.processor.plugin.DefaultProcessor.process(DefaultProcessor.java:269)
	at org.gephi.io.processor.plugin.DefaultProcessor.process(DefaultProcessor.java:105)
	at org.gephi.io.importer.impl.ImportControllerImpl.process(ImportControllerImpl.java:331)
	at org.gephi.desktop.importer.DesktopImportControllerUI.finishImport(DesktopImportControllerUI.java:585)
	at org.gephi.desktop.importer.DesktopImportControllerUI.access$000(DesktopImportControllerUI.java:106)
	at org.gephi.desktop.importer.DesktopImportControllerUI$3.run(DesktopImportControllerUI.java:307)
	at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
