### ISSUE TITLE
Apple menu Netbeans module missing

### ISSUE THREAD

**Issue by eduramiba** [gephi/gephi#1806]
```
FileNotFoundException: /Volumes/Gephi 0.9.2/Gephi.app/Contents/Resources/gephi/platform/modules/org-netbeans-modules-applemenu.jar (No such file or directory)
    at java.util.zip.ZipFile.open(ZipFile.java)
    at java.util.zip.ZipFile.<init>(ZipFile.java:225)
    at java.util.zip.ZipFile.<init>(ZipFile.java:155)
    at java.util.jar.JarFile.<init>(JarFile.java:166)
    at java.util.jar.JarFile.<init>(JarFile.java:103)
...
(20 additional frame(s) were not displayed)

FileNotFoundException: Cannot find 'jar:file:/Volumes/Gephi%200.9.2/Gephi.app/Contents/Resources/gephi/platform/modules/org-netbeans-modules-applemenu.jar!/org/netbeans/modules/applemenu/shortcuts_mac.xml'
    at org.netbeans.core.startup.layers.BinaryFS$BFSFile.getInputStream(BinaryFS.java:909)
    at org.openide.filesystems.MultiFileObject.getInputStream(MultiFileObject.java:666)
    at org.openide.filesystems.MultiFileObject.getInputStream(MultiFileObject.java:666)
    at org.openide.loaders.XMLDataObjectInfoParser.waitFinished(XMLDataObjectInfoParser.java:237)
    at org.openide.loaders.XMLDataObjectInfoParser.waitFinished(XMLDataObjectInfoParser.java:187)
...
(10 additional frame(s) were not displayed)

Cannot find 'jar:file:/Volumes/Gephi%200.9.2/Gephi.app/Contents/Resources/gephi/platform/modules/org-netbeans-modules-applemenu.jar!/org/netbeans/modules/applemenu/shortcuts_mac.xml'
```

**Comment by eduramiba** [comment]
Probable not an issue. Seems duplicate of #722 and I can confirm that the jar is in the 0.9.2 distribution platform/modules folder
