### ISSUE TITLE
Exception exporting spreadsheet

### ISSUE THREAD

**Issue by eduramiba** [gephi/gephi#1893]
```java
java.lang.NullPointerException
at org.gephi.io.exporter.plugin.ExporterSpreadsheet.exportData(ExporterSpreadsheet.java:190)
at org.gephi.io.exporter.plugin.ExporterSpreadsheet.execute(ExporterSpreadsheet.java:110)
Caused: java.lang.RuntimeException
at org.gephi.io.exporter.plugin.ExporterSpreadsheet.execute(ExporterSpreadsheet.java:112)
at org.gephi.io.exporter.impl.ExportControllerImpl.exportFile(ExportControllerImpl.java:134)
at org.gephi.desktop.io.export.DesktopExportController$2.run(DesktopExportController.java:97)
Caused: java.lang.RuntimeException
at org.gephi.desktop.io.export.DesktopExportController$2.run(DesktopExportController.java:100)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source
```

**Comment by mbastian** [comment]
@eduramiba Do you have a way to reproduce this one? Thanks!

**Comment by eduramiba** [comment]
@mbastian Sorry I don't remember how I got this one. It seems to point here: https://github.com/gephi/gephi/blob/master/modules/ExportPlugin/src/main/java/org/gephi/io/exporter/plugin/ExporterSpreadsheet.java#L190 which could mean a row is null 🤔

**Comment by mbastian** [comment]
OK, weird that shouldn't be the case. Let me remove the 0.9.3 milestone until we can reproduce this one.
