### ISSUE TITLE
Gephi ( 0.9.1 and 0.9.2 ) fails to start 

### ISSUE THREAD

**Issue by mderouss** [gephi/gephi#1894]
## Expected Behavior

Executing the 'gephi' script in gephi-0.9.2/bin should start Gephi

## Current Behavior

Gephi does not start. 

## Possible Solution

According to the log, there's an OpenGL based issue, but I do not know how to fix it. 

## Steps to Reproduce

1. cd to the directory that contains the 'gephi' script
2. execute the gephi script ( ./gephi )

## Context

Just want to start the tool...

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 

Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

* Operating System: 

Linux xxxx-Z800 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

xxxx@xxxx-Z800:~$ glxinfo | grep version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.3
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL core profile version string: 4.3 (Core Profile) Mesa 17.2.4
OpenGL core profile shading language version string: 4.30
OpenGL version string: 3.0 Mesa 17.2.4
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 17.2.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10

>Log Session: Sunday, January 14, 2018 10:57:12 PM GMT
>System Info: 
  Product Version         = Gephi 0.9.2 201709241107
  Operating System        = Linux version 4.4.0-109-generic running on amd64
  Java; VM; Vendor        = 1.8.0_151; Java HotSpot(TM) 64-Bit Server VM 25.151-b12; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 1.8.0_151-b12
  Java Home               = /usr/lib/jvm/java-8-oracle/jre
  System Locale; Encoding = en_GB (gephi); UTF-8
  Home Directory          = /home/xxxx
  Current Directory       = /home/xxxx/Downloads/gephi-0.9.2-linux/gephi-0.9.2/bin
  User Directory          = /home/xxxx/.gephi/0.9.2/dev
  Cache Directory         = /home/xxxx/.gephi/0.9.2/dev/var/cache
  Installation            = /home/xxxx/Downloads/gephi-0.9.2-linux/gephi-0.9.2/platform
                            /home/xxxx/Downloads/gephi-0.9.2-linux/gephi-0.9.2/gephi
                            /home/xxxx/Downloads/gephi-0.9.2-linux/gephi-0.9.2/platform
  [Boot & Ext. Classpath omitted for brevity]
-------------------------------------------------------------------------------
WARNING [org.netbeans.modules.autoupdate.ui.actions.AutoupdateSettings]: The property "netbeans.default_userdir_root" was not set!
WARNING [null]: Last record repeated again.
java.lang.InternalError: XXX0 profile[1]: GL3bc -> profileImpl GL4bc !!! not mapped 
	at com.jogamp.opengl.GLProfile.computeProfileMap(GLProfile.java:2071)
	at com.jogamp.opengl.GLProfile.initProfilesForDeviceCritical(GLProfile.java:1954)
	at com.jogamp.opengl.GLProfile.initProfilesForDevice(GLProfile.java:1875)
	at com.jogamp.opengl.GLProfile.initProfilesForDefaultDevices(GLProfile.java:1842)
	at com.jogamp.opengl.GLProfile.access$000(GLProfile.java:80)
	at com.jogamp.opengl.GLProfile$1.run(GLProfile.java:230)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.opengl.GLProfile.initSingleton(GLProfile.java:216)
	at org.gephi.visualization.Installer.restored(Installer.java:55)
	at org.netbeans.core.startup.NbInstaller.loadCode(NbInstaller.java:468)
	at org.netbeans.core.startup.NbInstaller.loadImpl(NbInstaller.java:391)
	at org.netbeans.core.startup.NbInstaller.access$000(NbInstaller.java:102)
	at org.netbeans.core.startup.NbInstaller$1.run(NbInstaller.java:343)
	at org.openide.filesystems.FileUtil$2.run(FileUtil.java:436)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:127)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:519)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:420)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:440)
	at org.netbeans.core.startup.NbInstaller.load(NbInstaller.java:340)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1365)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1170)
	at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:340)
	at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:276)
	at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:301)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:181)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:150)
	at org.netbeans.core.startup.Main.start(Main.java:307)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:123)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mderouss** [comment]
Found another issue that described this problem better ( 1803 ). Switched from nouveau drivers to latest NVidia drivers for my graphics card, problem now solved.
