### ISSUE TITLE
Failure to launch using Nouveau drivers

### ISSUE THREAD

**Issue by ZHNNN** [gephi/gephi#1910]
## Expected Behavior
Program opens
## Current Behavior
Program crashes at splash screen
## Steps to Reproduce

1. Get a high-res monitor for your linux machine
2. Install gephi
3. Ignore the suggestion from the devs to "install the latest drivers from NVidia", because NVidia recently added a function banning WQHD output from a 560M over HDMI, even though it has been working flawlessly for years.
4. Try to launch gephi

## Context

There's possibly a better tool for what I want, which is using directed graphs to analyze boolean logic, but I have not found it.   I wrote a program to convert large programs into GEXF directed graphs, and I'm trying to test it on my development machine.  I cannot presently load my GEXF into gephi without borrowing a Windows machine.

## Your Environment

>System Info: 
  Product Version         = Gephi 0.9.2 201709241107
  Operating System        = Linux version 4.14.15-1-MANJARO running on amd64
  Java; VM; Vendor        = 1.8.0_144; OpenJDK 64-Bit Server VM 25.144-b01; Oracle Corporation
  Runtime                 = OpenJDK Runtime Environment 1.8.0_144-b01
  Java Home               = /usr/lib/jvm/java-8-openjdk/jre
  System Locale; Encoding = en_US (gephi); UTF-8
  Home Directory          = /home/user
  Current Directory       = /home/user/
  User Directory          = /home/user/.gephi/0.9.2/dev
  Cache Directory         = /home/user/.gephi/0.9.2/dev/var/cache
  Installation            = /usr/share/java/gephi/platform
                            /usr/share/java/gephi/gephi
                            /usr/share/java/gephi/platform
  Boot & Ext. Classpath   = /usr/lib/jvm/java-8-openjdk/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk/jre/classes:/usr/lib/jvm/java-8-openjdk/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/ext/nashorn.jar
  Application Classpath   = /usr/share/java/gephi/platform/lib/boot.jar:/usr/share/java/gephi/platform/lib/org-openide-modules.jar:/usr/share/java/gephi/platform/lib/org-openide-util.jar:/usr/share/java/gephi/platform/lib/org-openide-util-lookup.jar:/usr/share/java/gephi/platform/lib/org-openide-util-ui.jar:/usr/share/java/gephi/platform/lib/locale/boot_ar_SA.jar:/usr/share/java/gephi/platform/lib/locale/boot_bg.jar:/usr/share/java/gephi/platform/lib/locale/boot_ca.jar:/usr/share/java/gephi/platform/lib/locale/boot_cs.jar:/usr/share/java/gephi/platform/lib/locale/boot_de.jar:/usr/share/java/gephi/platform/lib/locale/boot_es.jar:/usr/share/java/gephi/platform/lib/locale/boot_fr.jar:/usr/share/java/gephi/platform/lib/locale/boot_gl_ES.jar:/usr/share/java/gephi/platform/lib/locale/boot_in_ID.jar:/usr/share/java/gephi/platform/lib/locale/boot_it.jar:/usr/share/java/gephi/platform/lib/locale/boot_ja.jar:/usr/share/java/gephi/platform/lib/locale/boot_ko.jar:/usr/share/java/gephi/platform/lib/locale/boot_nl_NL.jar:/usr/share/java/gephi/platform/lib/locale/boot_pl.jar:/usr/share/java/gephi/platform/lib/locale/boot_pt_BR.jar:/usr/share/java/gephi/platform/lib/locale/boot_pt_PT.jar:/usr/share/java/gephi/platform/lib/locale/boot_ro.jar:/usr/share/java/gephi/platform/lib/locale/boot_ru.jar:/usr/share/java/gephi/platform/lib/locale/boot_si.jar:/usr/share/java/gephi/platform/lib/locale/boot_sq.jar:/usr/share/java/gephi/platform/lib/locale/boot_sv.jar:/usr/share/java/gephi/platform/lib/locale/boot_tr.jar:/usr/share/java/gephi/platform/lib/locale/boot_zh_CN.jar:/usr/share/java/gephi/platform/lib/locale/boot_zh_TW.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-modules_ar_SA.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-modules_bg.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-modules_ca.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-modules_cs.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-modules_de.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-modules_es.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-modules_fr.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-modules_gl_ES.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-modules_in_ID.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-modules_it.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-modules_ja.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-modules_ko.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-modules_nl_NL.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-modules_pl.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-modules_pt_BR.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-modules_pt_PT.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-modules_ro.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-modules_ru.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-modules_si.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-modules_sq.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-modules_sv.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-modules_tr.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-modules_zh_CN.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-modules_zh_TW.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util_ar_SA.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util_bg.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util_ca.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util_cs.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util_de.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util_es.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util_fr.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util_gl_ES.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util_in_ID.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util_it.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util_ja.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util_ko.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util-lookup_bg.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util-lookup_ca.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util-lookup_cs.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util-lookup_de.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util-lookup_es.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util-lookup_fr.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util-lookup_gl_ES.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util-lookup_in_ID.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util-lookup_it.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util-lookup_ja.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util-lookup_ko.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util-lookup_nl_NL.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util-lookup_pl.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util-lookup_pt_BR.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util-lookup_ro.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util-lookup_ru.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util-lookup_si.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util-lookup_sv.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util-lookup_tr.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util-lookup_zh_CN.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util_nl_NL.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util_pl.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util_pt_BR.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util_pt_PT.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util_ro.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util_ru.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util_si.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util_sq.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util_sv.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util_tr.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util-ui_ja.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util-ui_pt_BR.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util-ui_ru.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util-ui_zh_CN.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util_zh_CN.jar:/usr/share/java/gephi/platform/lib/locale/org-openide-util_zh_TW.jar:/usr/lib/jvm/default/lib/dt.jar:/usr/lib/jvm/default/lib/tools.jar
  Startup Classpath       = /usr/share/java/gephi/platform/core/org-openide-filesystems-compat8.jar:/usr/share/java/gephi/platform/core/org-openide-filesystems.jar:/usr/share/java/gephi/platform/core/asm-all-5.0.1.jar:/usr/share/java/gephi/platform/core/core.jar:/usr/share/java/gephi/platform/core/org-netbeans-libs-asm.jar:/usr/share/java/gephi/platform/core/core-base.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems-compat8_ja.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems_ko.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems_pt_PT.jar:/usr/share/java/gephi/platform/core/locale/core_sv.jar:/usr/share/java/gephi/platform/core/locale/core_ru.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems_fr.jar:/usr/share/java/gephi/platform/core/locale/core_zh_TW.jar:/usr/share/java/gephi/platform/core/locale/core_cs.jar:/usr/share/java/gephi/platform/core/locale/core_zh_CN.jar:/usr/share/java/gephi/platform/core/locale/core_pl.jar:/usr/share/java/gephi/platform/core/locale/core_de.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems_ru.jar:/usr/share/java/gephi/platform/core/locale/core_fr.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems_ar_SA.jar:/usr/share/java/gephi/platform/core/locale/core_nl_NL.jar:/usr/share/java/gephi/platform/core/locale/core-base_pt_BR.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems_zh_CN.jar:/usr/share/java/gephi/platform/core/locale/core_gl_ES.jar:/usr/share/java/gephi/platform/core/locale/core_si.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems_bg.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems-compat8_ru.jar:/usr/share/java/gephi/platform/core/locale/core_sq.jar:/usr/share/java/gephi/platform/core/locale/core_in_ID.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems_it.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems_ca.jar:/usr/share/java/gephi/platform/core/locale/org-netbeans-libs-asm_pt_BR.jar:/usr/share/java/gephi/platform/core/locale/core_ca.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems_cs.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems_gl_ES.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems_si.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems_in_ID.jar:/usr/share/java/gephi/platform/core/locale/org-netbeans-libs-asm_ja.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems_de.jar:/usr/share/java/gephi/platform/core/locale/core_tr.jar:/usr/share/java/gephi/platform/core/locale/core_ar_SA.jar:/usr/share/java/gephi/platform/core/locale/core_es.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems_pt_BR.jar:/usr/share/java/gephi/platform/core/locale/core_ko.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems_sq.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems_sv.jar:/usr/share/java/gephi/platform/core/locale/org-netbeans-libs-asm_zh_CN.jar:/usr/share/java/gephi/platform/core/locale/org-netbeans-libs-asm_ru.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems_ja.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems_ro.jar:/usr/share/java/gephi/platform/core/locale/core_it.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems_pl.jar:/usr/share/java/gephi/platform/core/locale/core-base_ja.jar:/usr/share/java/gephi/platform/core/locale/core_ro.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems_tr.jar:/usr/share/java/gephi/platform/core/locale/core_ja.jar:/usr/share/java/gephi/platform/core/locale/core-base_zh_CN.jar:/usr/share/java/gephi/platform/core/locale/core_bg.jar:/usr/share/java/gephi/platform/core/locale/core-base_ru.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems_nl_NL.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems_es.jar:/usr/share/java/gephi/platform/core/locale/core_pt_PT.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems-compat8_zh_CN.jar:/usr/share/java/gephi/platform/core/locale/core_pt_BR.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems_zh_TW.jar:/usr/share/java/gephi/platform/core/locale/org-openide-filesystems-compat8_pt_BR.jar:/usr/share/java/gephi/gephi/core/locale/core_gephi.jar
-------------------------------------------------------------------------------
WARNING [org.netbeans.modules.autoupdate.ui.actions.AutoupdateSettings]: The property "netbeans.default_userdir_root" was not set!
java.lang.InternalError: XXX0 profile[1]: GL3bc -> profileImpl GL4bc !!! not mapped 
	at com.jogamp.opengl.GLProfile.computeProfileMap(GLProfile.java:2071)
	at com.jogamp.opengl.GLProfile.initProfilesForDeviceCritical(GLProfile.java:1954)
	at com.jogamp.opengl.GLProfile.initProfilesForDevice(GLProfile.java:1875)
	at com.jogamp.opengl.GLProfile.initProfilesForDefaultDevices(GLProfile.java:1842)
	at com.jogamp.opengl.GLProfile.access$000(GLProfile.java:80)
	at com.jogamp.opengl.GLProfile$1.run(GLProfile.java:230)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.opengl.GLProfile.initSingleton(GLProfile.java:216)
	at org.gephi.visualization.Installer.restored(Installer.java:55)
	at org.netbeans.core.startup.NbInstaller.loadCode(NbInstaller.java:468)
	at org.netbeans.core.startup.NbInstaller.loadImpl(NbInstaller.java:391)
	at org.netbeans.core.startup.NbInstaller.access$000(NbInstaller.java:102)
	at org.netbeans.core.startup.NbInstaller$1.run(NbInstaller.java:343)
	at org.openide.filesystems.FileUtil$2.run(FileUtil.java:436)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:127)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:519)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:420)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:440)
	at org.netbeans.core.startup.NbInstaller.load(NbInstaller.java:340)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1365)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1170)
	at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:340)
	at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:276)
	at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:301)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:181)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:150)
	at org.netbeans.core.startup.Main.start(Main.java:307)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:123)
	at java.lang.Thread.run(Thread.java:748)

**Comment by eduramiba** [comment]
Same as https://github.com/gephi/gephi/issues/1898 ?
