### ISSUE TITLE
Emoji makes SVG export fail

### ISSUE THREAD

**Issue by totetmatt** [gephi/gephi#1921]
If a graph is having a label with Emoji, the SVG export will fail with the following error

```
java.lang.Error: IO:Invalid character
	at org.apache.batik.transcoder.svg2svg.SVGTranscoder.transcode(SVGTranscoder.java:179)
	at org.gephi.io.exporter.preview.SVGExporter.execute(SVGExporter.java:107)
	at org.gephi.io.exporter.impl.ExportControllerImpl.exportFile(ExportControllerImpl.java:134)
	at org.gephi.desktop.io.export.DesktopExportController$2.run(DesktopExportController.java:97)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

Not sure if it's only for emoji or any "extended" UTF-8 characters.
Graph File to reproduce error.
[emoji.zip](https://github.com/gephi/gephi/files/1772829/emoji.zip)

**Comment by Marmeladenbrot** [comment]
Had the same problem with a flag symbol in a twitter accounts screen name.

In the csv extract: 🇩🇪
In Gephi as label: 🇩🇪

But if you go to "Edit Node" the label says "accountname \ud83c\udde9\ud83c\uddea" which is the german flag.

**Comment by ZinoZaino** [comment]
Hi, 
I have the same problem, with Twitter importer. I can't export graph in .svg

**Comment by mbastian** [comment]
I could reproduce this issue too, with this exception

```
java.lang.NullPointerException
	at org.gephi.preview.plugin.renderers.NodeLabelRenderer.renderSVG(NodeLabelRenderer.java:293)
	at org.gephi.preview.plugin.renderers.NodeLabelRenderer.render(NodeLabelRenderer.java:198)
	at org.gephi.preview.PreviewControllerImpl.render(PreviewControllerImpl.java:251)
	at org.gephi.preview.PreviewControllerImpl.render(PreviewControllerImpl.java:208)
	at org.gephi.io.exporter.preview.SVGExporter.execute(SVGExporter.java:95)
Caused: java.lang.RuntimeException
	at org.gephi.io.exporter.preview.SVGExporter.execute(SVGExporter.java:113)
	at org.gephi.io.exporter.impl.ExportControllerImpl.exportFile(ExportControllerImpl.java:134)
	at org.gephi.desktop.io.export.DesktopExportController$2.run(DesktopExportController.java:97)
Caused: java.lang.RuntimeException
	at org.gephi.desktop.io.export.DesktopExportController$2.run(DesktopExportController.java:100)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by mbastian** [comment]
This issue's root cause is within the Batik library itself. We would need to make some additional research and potentially file a bug to get it fixed. Moving to 0.9.4 milestone as a result.
