### ISSUE TITLE
IllegalArgumentException: Node id=-1 is invalid

### ISSUE THREAD

**Issue by MathewToll** [gephi/gephi#1982]
## Expected Behavior

Open project file and initialize graph. 

## Current Behavior

Open project file, no graph initializes and an error message that reads: 

java.lang.IllegalArgumentException: Node id=-1 is invalid
	at org.gephi.graph.impl.NodeStore.checkValidId(NodeStore.java:511)
	at org.gephi.graph.impl.NodeStore.get(NodeStore.java:117)
	at org.gephi.graph.impl.Serialization.deserializeEdge(Serialization.java:408)
	at org.gephi.graph.impl.Serialization.deserialize(Serialization.java:2050)
	at org.gephi.graph.impl.Serialization.deserializeGraphStore(Serialization.java:345)
	at org.gephi.graph.impl.Serialization.deserialize(Serialization.java:2062)
	at org.gephi.graph.impl.Serialization.deserializeGraphModel(Serialization.java:245)
	at org.gephi.graph.api.GraphModel$Serialization.read(GraphModel.java:135)
	at org.gephi.graph.GraphPersistenceProvider.readBytes(GraphPersistenceProvider.java:88)
	at org.gephi.project.io.LoadTask.readWorkspaceChildrenBytes(LoadTask.java:327)
	at org.gephi.project.io.LoadTask.run(LoadTask.java:130)
Caused: org.gephi.project.io.GephiFormatException: Gephi failed importing the project.

Exception: IllegalArgumentException : Node id=-1 is invalid
File: org.gephi.graph.impl.NodeStore
Line : 511
	at org.gephi.project.io.LoadTask.run(LoadTask.java:173)
	at org.gephi.desktop.project.ProjectControllerUIImpl$7.run(ProjectControllerUIImpl.java:341)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
 

## Steps to Reproduce

1.  Run Twitter Streaming Plugin 
2.  Save network 
3.  Check back to find program non-responding
4.  Close and try and reopen project file/ find project file won't load graph

## Context

I was trying to reopen the project file and continue streaming twitter data.   

## Your Environment

* Version used: Gephi 0.9.2
* Java version: Java 8 Update 144 (64-bit)
* Operating System:  Windows 7 Enterprise

**Comment by ning1no** [comment]
I have the same issue. ¿Did you find any workaround?

**Comment by wetneb** [comment]
This seems to be an issue with the Twitter plugin, so migrating the issue there.
