### ISSUE TITLE
Silent Exception when loading malformed GML file

### ISSUE THREAD

**Issue by thomai-d** [gephi/gephi#2044]
I accidently created a malformed GML file which I opened with Gephi.
The "crashattr" was missing quotes:

```
graph [
   directed 1
   label "Some label"
   comment "Some comment"

   node [
      id "MyId"
      label "MyLabel"
      crashattr > 10k
   ]
]
```

# Expected Behavior
I would have expected that gephi gave me a problem report, similar to the following one:
![grafik](https://user-images.githubusercontent.com/24974298/47614681-e0275a80-daa3-11e8-9fc5-c35d61d218c8.png)

Also the line number / node number would have been very helpful.

## Current Behavior
Nothing happens. No graph is shown, but also no problems are reported. Just an empty screen is shown.

In the logfile a single entry is produced:
```
SEVERE [org.openide.util.Exceptions]
java.lang.IndexOutOfBoundsException: Index: 7, Size: 7
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.gephi.io.importer.plugin.file.ImporterGML.parseNode(ImporterGML.java:198)
	at org.gephi.io.importer.plugin.file.ImporterGML.parseGraph(ImporterGML.java:170)
	at org.gephi.io.importer.plugin.file.ImporterGML.importData(ImporterGML.java:94)
	at org.gephi.io.importer.plugin.file.ImporterGML.execute(ImporterGML.java:73)
Caused: java.lang.RuntimeException
	at org.gephi.io.importer.plugin.file.ImporterGML.execute(ImporterGML.java:75)
	at org.gephi.io.importer.impl.ImportControllerImpl.importFile(ImportControllerImpl.java:199)
	at org.gephi.io.importer.impl.ImportControllerImpl.importFile(ImportControllerImpl.java:169)
	at org.gephi.desktop.importer.DesktopImportControllerUI$4.run(DesktopImportControllerUI.java:341)
Caused: java.lang.RuntimeException
	at org.gephi.desktop.importer.DesktopImportControllerUI$4.run(DesktopImportControllerUI.java:349)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

## Your Environment

* Version used: Gephi 0.9.2 201709241107
* Java version: 1.8.0_172; Java HotSpot(TM) 64-Bit Server VM 25.172-b11; Oracle Corporation
* Operating System: Windows 10 Pro

**Comment by WaltonG** [comment]
Would like to work on this if no one else is
