### ISSUE TITLE
How should I visualize the graph on the remote server?

### ISSUE THREAD

**Issue by wxr1997** [gephi/gephi#2053]
## Expected Behavior
I need to visualize a graph database named janusgraph which is constructed on my remote server. Now from the general recommendation of official page of janusgraph, I want to use gephi plugin to visualize the graph. I hope to establish a server of the visualized graph which can be seen from the local browser by giving the server and port.
## Current Behavior
I don't know how to manipulate the 'gephi' from the command line because it is quite hard to use UI from the remote server. I just want to establish a visualization server from the command line by gephi plugin. I use ssh to connect my server.
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8.0
* Operating System:remote linux server

**Comment by eduramiba** [comment]
Hi,
Gephi does not have a command line interface. You have to open the GUI manually.

It seems you will need to do one of these:

- Export the database to one of the gephi supported formats: https://gephi.org/users/supported-graph-formats/
- Use the gremlin plugin of tinkerpop with Janusgraph, and Gephi with streaming plugin: http://tinkerpop.apache.org/docs/current/reference/#gephi-plugin

**Comment by wxr1997** [comment]
@eduramiba Thanks for your reply! As a freshman to database, I still have some questions as follows. I really want the second way you've mentioned and realize on my own server. Initially, I install janusgraph, a graph database, on my remote server. Meanwhile, there are some graphs in the database which I can make sure the availability of the graph database. In addition, I download gephi from https://gephi.org into the remote server. 
There are something I am confused with:
1. Whether the thing I downloaded is the gremlin plugin of tinkerpop with Janusgraph or not?
2. How should I make a http server by gremlin or gremlin plugin which I can directly see the visualization of the graph saved in my database locally from the browser by some server with port, such as http://xxx.xxx.xxx.xxx:nn

**Comment by eduramiba** [comment]
Hi,
Unfortunately I have never use Janusgraph, but the Gephi part is:

1. Install Gephi and run it
2. Go to Tools - Plugins menu and install the streaming plugin
3. Start the streaming server in Gephi, that creates a URL like http://localhost:8080/your_workspace_name
4. Use the gremlin janusgraph plugin to stream to that URL (not sure about this part)

Follow the guide here, for example: https://matthieu-totet.fr/Koumin/2013/09/16/gephi-and-the-streaming-module/

Also, you could export janusgraph to graphml and load it into Gephi I think: https://groups.google.com/forum/#!topic/janusgraph-users/tVDikFTv1Bs

**Comment by wxr1997** [comment]
@eduramiba Well, you know I have installed all the software and system on the remote server to which I connect by ssh protocol locally. So it is hard to use UI from this connection. Well I have a small virtual machine established by ubuntu locally. I only install gephi in the virtual machine. There is a bug I don't know how to fix. That is, the graph interface is always initializing and I cannot see the visualization of the example graph.
This may be the cause: The right below corner has a icon, with report as follows: 

> java.lang.ClassNotFoundException: com.sun.java.swing.plaf.windows.WindowsButtonUI
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:222)
Caused: java.lang.ClassNotFoundException: com.sun.java.swing.plaf.windows.WindowsButtonUI starting from ModuleCL@5bd2acdf[org.gephi.ui.utils] with possible defining loaders null and declared parents [org.netbeans.MainImpl$BootClassLoader@6b4ac21a, ModuleCL@4b32b1e4[org.gephi.core.library.wrapper], ModuleCL@798d5692[org.gephi.lib.validation], ModuleCL@533e3864[org.gephi.graph.api], ModuleCL@ddd1e76[org.gephi.utils]]
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:224)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
Caused: java.lang.NoClassDefFoundError: com/sun/java/swing/plaf/windows/WindowsButtonUI
	at org.gephi.ui.utils.UIUtils.fixButtonUI(UIUtils.java:385)
	at org.gephi.visualization.component.VizToolbar.add(VizToolbar.java:94)
	at org.gephi.visualization.component.VizToolbar.<init>(VizToolbar.java:65)
	at org.gephi.visualization.component.VizBarController.getToolbar(VizBarController.java:116)
	at org.gephi.visualization.component.GraphTopComponent.initCollapsePanel(GraphTopComponent.java:120)
	at org.gephi.visualization.component.GraphTopComponent.access$000(GraphTopComponent.java:77)
	at org.gephi.visualization.component.GraphTopComponent$1$1.run(GraphTopComponent.java:99)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Could you please tell me what causes this bug?

**Comment by eduramiba** [comment]
I suggest you use Gephi in a machine with good GUI support instead of a server.
Also, make sure you use Java 8 and not later or earlier.

**Comment by wxr1997** [comment]
@eduramiba OK, thank you very much!
