### ISSUE TITLE
java.util.MissingResourceException gephi version 0.9.2

### ISSUE THREAD

**Issue by mpolat00** [gephi/gephi#2063]
I am using windows 10 64 bit.
I have java jre 1.8.0_192 and jdk-11.0.1. installed.
The app opens up nicely. Once I try to open a .net file it gives an error on the right bottom corner starting with this expression.
The rest is like this:
java.util.MissingResourceException: Can't find resource for bundle org.openide.util.NbBundle$PBundle, key ReportPanel.mergeStrategy.mın
	at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:564)
	at java.base/java.util.ResourceBundle.getString(ResourceBundle.java:521)
	at org.openide.util.NbBundle.getMessage(NbBundle.java:642)
	at org.gephi.desktop.importer.EdgesMergeStrategyWrapper.toString(EdgesMergeStrategyWrapper.java:90)
	at java.desktop/javax.swing.plaf.basic.BasicComboBoxRenderer.getListCellRendererComponent(BasicComboBoxRenderer.java:125)
	at java.desktop/com.sun.java.swing.plaf.windows.WindowsComboBoxUI$WindowsComboBoxRenderer.getListCellRendererComponent(WindowsComboBoxUI.java:628)
	at java.desktop/javax.swing.plaf.basic.BasicComboBoxUI.getDisplaySize(BasicComboBoxUI.java:1407)
	at java.desktop/javax.swing.plaf.basic.BasicComboBoxUI.getMinimumSize(BasicComboBoxUI.java:960)
	at java.desktop/com.sun.java.swing.plaf.windows.WindowsComboBoxUI.getMinimumSize(WindowsComboBoxUI.java:340)
	at java.desktop/javax.swing.plaf.basic.BasicComboBoxUI.getPreferredSize(BasicComboBoxUI.java:949)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1680)
	at java.desktop/java.awt.GridBagLayout.GetLayoutInfo(GridBagLayout.java:1127)
	at java.desktop/java.awt.GridBagLayout.getLayoutInfo(GridBagLayout.java:922)
	at java.desktop/java.awt.GridBagLayout.ArrangeGrid(GridBagLayout.java:2090)
	at java.desktop/java.awt.GridBagLayout.arrangeGrid(GridBagLayout.java:2050)
	at java.desktop/java.awt.GridBagLayout.layoutContainer(GridBagLayout.java:818)
	at java.desktop/java.awt.Container.layout(Container.java:1537)
	at java.desktop/java.awt.Container.doLayout(Container.java:1526)
	at java.desktop/java.awt.Container.validateTree(Container.java:1722)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validate(Container.java:1657)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2770)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by CanberkKaman** [comment]
I am having the same problem, did you find any solution??

**Comment by ilaozdemir** [comment]
go to Tools -> Languages to switch the language, for example, to English and restart the app

**Comment by atakanguney** [comment]
It worked, thanks @ilaozdemir

**Comment by rabia174** [comment]
I had the same problem, you saved me too, thanks!

**Comment by kurtsenol** [comment]
> go to Tools -> Languages to switch the language, for example, to English and restart the app

Thanks a lot. Saved me, as well!!!

**Comment by FatihGuven** [comment]
> go to Tools -> Languages to switch the language, for example, to English and restart the app

Really worked.

**Comment by gurcankavakci** [comment]
> go to Tools -> Languages to switch the language, for example, to English and restart the app

Thanks

**Comment by suatatan** [comment]
Thanks for the answers it has worked. So many Gephi lovers among Turkish speakers? :)

**Comment by mbastian** [comment]
This issue has been fixed and will be included in the upcoming 0.9.3 release. 

teşekkür ederim!
