### ISSUE TITLE
Gephi doesn't start on Mac OS Mojave - java.lang.NullPointerException

### ISSUE THREAD

**Issue by daviddias** [gephi/gephi#2075]
## Expected Behavior

Gephi to start normally

## Current Behavior

The icon pops up at the doc, bounces and then closes

## Steps to Reproduce

1. Get a Mac OS Mojave 10.14.2
2. Install Java 8 (through the website or using brew)
3. Install Gephi (move app to Applications folder)
4. Click to start gephi

## Context

I'm using Gephi for the first time and so, I'm not sure if it is just me missing something.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: java version "1.8.0_202-ea", Java(TM) SE Runtime Environment (build 1.8.0_202-ea-b03), Java HotSpot(TM) 64-Bit Server VM (build 25.202-b03, mixed mode)
* Operating System: Mac OS Mojave 10.14.2

```
-------------------------------------------------------------------------------
>Log Session: Sunday, January 27, 2019 6:19:37 PM CET
>System Info: 
  Product Version         = Gephi 0.9.2 201709242018
  Operating System        = Mac OS X version 10.14.2 running on x86_64
  Java; VM; Vendor        = 1.8.0_144; Java HotSpot(TM) 64-Bit Server VM 25.144-b01; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 1.8.0_144-b01
  Java Home               = /Applications/Gephi.app/Contents/PlugIns/jre1.8.0_144.jre/Contents/Home
  System Locale; Encoding = en_US (gephi); UTF-8
  Home Directory          = /Users/imp
  Current Directory       = /
  User Directory          = /Users/imp/Library/Application Support/gephi/0.9.2/dev
  Cache Directory         = /Users/imp/Library/Application Support/gephi/0.9.2/dev/var/cache
  Installation            = /Applications/Gephi.app/Contents/Resources/gephi/gephi
                            /Applications/Gephi.app/Contents/Resources/gephi/platform
                            /Applications/Gephi.app/Contents/Resources/gephi/platform
  Boot & Ext. Classpath   = /Applications/Gephi.app/Contents/PlugIns/jre1.8.0_144.jre/Contents/Home/lib/resources.jar:/Applications/Gephi.app/Contents/PlugIns/jre1.8.0_144.jre/Contents/Home/lib/rt.jar:/Applications/Gephi.app/Contents/PlugIns/jre1.8.0_144.jre/Contents/Home/lib/sunrsasign.jar:/Applications/Gephi.app/Contents/PlugIns/jre1.8.0_144.jre/Contents/Home/lib/jsse.jar:/Applications/Gephi.app/Contents/PlugIns/jre1.8.0_144.jre/Contents/Home/lib/jce.jar:/Applications/Gephi.app/Contents/PlugIns/jre1.8.0_144.jre/Contents/Home/lib/charsets.jar:/Applications/Gephi.app/Contents/PlugIns/jre1.8.0_144.jre/Contents/Home/lib/jfr.jar:/Applications/Gephi.app/Contents/PlugIns/jre1.8.0_144.jre/Contents/Home/classes:/Applications/Gephi.app/Contents/PlugIns/jre1.8.0_144.jre/Contents/Home/lib/ext/sunec.jar:/Applications/Gephi.app/Contents/PlugIns/jre1.8.0_144.jre/Contents/Home/lib/ext/nashorn.jar:/Applications/Gephi.app/Contents/PlugIns/jre1.8.0_144.jre/Contents/Home/lib/ext/cldrdata.jar:/Applications/Gephi.app/Contents/PlugIns/jre1.8.0_144.jre/Contents/Home/lib/ext/jfxrt.jar:/Applications/Gephi.app/Contents/PlugIns/jre1.8.0_144.jre/Contents/Home/lib/ext/dnsns.jar:/Applications/Gephi.app/Contents/PlugIns/jre1.8.0_144.jre/Contents/Home/lib/ext/localedata.jar:/Applications/Gephi.app/Contents/PlugIns/jre1.8.0_144.jre/Contents/Home/lib/ext/sunjce_provider.jar:/Applications/Gephi.app/Contents/PlugIns/jre1.8.0_144.jre/Contents/Home/lib/ext/sunpkcs11.jar:/Applications/Gephi.app/Contents/PlugIns/jre1.8.0_144.jre/Contents/Home/lib/ext/jaccess.jar:/Applications/Gephi.app/Contents/PlugIns/jre1.8.0_144.jre/Contents/Home/lib/ext/zipfs.jar:/System/Library/Java/Extensions/MRJToolkit.jar
  Application Classpath   = /Applications/Gephi.app/Contents/Resources/gephi/platform/lib/boot.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/org-openide-modules.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/org-openide-util-lookup.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/org-openide-util-ui.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/org-openide-util.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_ar_SA.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_bg.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_ca.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_cs.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_de.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_es.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_fr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_gl_ES.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_in_ID.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_it.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_ja.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_ko.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_nl_NL.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_pl.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_pt_BR.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_pt_PT.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_ro.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_ru.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_si.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_sq.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_sv.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_tr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_zh_CN.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_zh_TW.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_ar_SA.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_bg.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_ca.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_cs.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_de.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_es.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_fr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_gl_ES.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_in_ID.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_it.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_ja.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_ko.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_nl_NL.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_pl.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_pt_BR.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_pt_PT.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_ro.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_ru.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_si.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_sq.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_sv.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_tr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_zh_CN.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_zh_TW.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_bg.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_ca.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_cs.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_de.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_es.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_fr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_gl_ES.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_in_ID.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_it.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_ja.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_ko.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_nl_NL.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_pl.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_pt_BR.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_ro.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_ru.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_si.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_sv.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_tr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_zh_CN.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-ui_ja.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-ui_pt_BR.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-ui_ru.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-ui_zh_CN.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_ar_SA.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_bg.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_ca.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_cs.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_de.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_es.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_fr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_gl_ES.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_in_ID.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_it.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_ja.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_ko.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_nl_NL.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_pl.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_pt_BR.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_pt_PT.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_ro.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_ru.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_si.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_sq.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_sv.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_tr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_zh_CN.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_zh_TW.jar
  Startup Classpath       = /Applications/Gephi.app/Contents/Resources/gephi/platform/core/org-netbeans-libs-asm.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/org-openide-filesystems-compat8.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/asm-all-5.0.1.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/org-openide-filesystems.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/core.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/core-base.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_pt_BR.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_cs.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_gl_ES.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_ca.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_tr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_ar_SA.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-netbeans-libs-asm_pt_BR.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core-base_zh_CN.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_pt_PT.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_bg.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_es.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_ko.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_si.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_fr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core-base_ru.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_ar_SA.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_pt_PT.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_ru.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_sq.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_ro.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_ja.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems-compat8_zh_CN.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_de.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_pt_BR.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_sv.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_pl.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core-base_ja.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_it.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_gl_ES.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_pl.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_it.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_de.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_sv.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_ja.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems-compat8_ru.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_zh_TW.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems-compat8_ja.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_ru.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_sq.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_ro.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems-compat8_pt_BR.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_zh_CN.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_in_ID.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_nl_NL.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_si.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_es.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_ko.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_fr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_bg.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_in_ID.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_zh_CN.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_ca.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_nl_NL.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-netbeans-libs-asm_ru.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_tr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-netbeans-libs-asm_ja.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_cs.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core-base_pt_BR.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-netbeans-libs-asm_zh_CN.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_zh_TW.jar:/Applications/Gephi.app/Contents/Resources/gephi/gephi/core/locale/core_gephi.jar
-------------------------------------------------------------------------------
java.lang.NullPointerException
	at java.awt.Window.init(Window.java:497)
	at java.awt.Window.<init>(Window.java:537)
	at java.awt.Frame.<init>(Frame.java:420)
	at org.netbeans.core.startup.Splash.setRunning(Splash.java:158)
	at org.netbeans.core.startup.Main.start(Main.java:296)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:123)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by daviddias** [comment]
Note: Gephi 0.9.1 works like a charm 👌🏽

**Comment by daviddias** [comment]
Ups, scratch that, graphs get all messed up :( 

<img width="1840" alt="image" src="https://user-images.githubusercontent.com/1211152/51806125-df05f500-226d-11e9-80fc-e58452330bf4.png">

**Comment by franzesilva** [comment]
@daviddias I'm using gephi 0.9.2. Its working fine after I executed this troubleshoot: https://medium.com/coder-snorts/gephi-is-broken-on-mac-os-97fbaef4305e

P.S.: I'm an absolute N00B.

**Comment by franzesilva** [comment]
@daviddias did you find a solution?

**Comment by daviddias** [comment]
No I didn't, unfortunately :(

**Comment by mbastian** [comment]
Hi, thanks for your report. The latest version of Gephi ([0.9.3](https://github.com/gephi/gephi/releases/tag/v0.9.3)) embed Java (JRE11) on Linux/Windows/MacOS so no need anymore to install Java separately. This should solve most Java compatibility issues.
