### ISSUE TITLE
Won't stop "Initializing" in Ubuntu 18.04 with OpenJDK

### ISSUE THREAD

**Issue by paredesroger** [gephi/gephi#2081]
## Expected Behavior
Finish "Initializing" graph window.
## Current Behavior
Graph window won't stop "Initializing".

After issuing `.\bin\gephi` in the terminal, I see some exceptions:

`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.netbeans.ProxyURLStreamHandlerFactory (file:/home/user/Downloads/gephi-0.9.2-linux/gephi-0.9.2/platform/lib/boot.jar) to field java.net.URL.handler
WARNING: Please consider reporting this to the maintainers of org.netbeans.ProxyURLStreamHandlerFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
`

After updating plugins an error appears in the bottom left corner prompting:

`java.lang.ClassNotFoundException: com.sun.java.swing.plaf.windows.WindowsButtonUI
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:222)
Caused: java.lang.ClassNotFoundException: com.sun.java.swing.plaf.windows.WindowsButtonUI starting from ModuleCL@2338bda4[org.gephi.ui.utils] with possible defining loaders null and declared parents [org.netbeans.MainImpl$BootClassLoader@2d5ff16c, ModuleCL@668e19e7[org.gephi.lib.validation], ModuleCL@1033fb41[org.gephi.core.library.wrapper], ModuleCL@722ef298[org.gephi.utils], ModuleCL@28bca833[org.gephi.graph.api]]
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:224)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
Caused: java.lang.NoClassDefFoundError: com/sun/java/swing/plaf/windows/WindowsButtonUI
	at org.gephi.ui.utils.UIUtils.fixButtonUI(UIUtils.java:385)
	at org.gephi.visualization.component.VizToolbar.add(VizToolbar.java:94)
	at org.gephi.visualization.component.VizToolbar.<init>(VizToolbar.java:65)
	at org.gephi.visualization.component.VizBarController.getToolbar(VizBarController.java:116)
	at org.gephi.visualization.component.GraphTopComponent.initCollapsePanel(GraphTopComponent.java:120)
	at org.gephi.visualization.component.GraphTopComponent.access$000(GraphTopComponent.java:77)
	at org.gephi.visualization.component.GraphTopComponent$1$1.run(GraphTopComponent.java:99)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
`

## Possible Solution

- Download Oracle's JRE: `jre-8u201-linux-x64.tar.gz `
- Open `path_to/gephi-0.9.2-linux/gephi-0.9.2/etc/gephi.conf` and set `jdkhome="/path_to/jre-8u201-linux-x64/jre1.8.0_201"`
- Now it should work.

## Steps to Reproduce

1. Be on Ubuntu 18.04
2. issue `./bin/gephi`
3. voila

## Context
The `Graph` window will never render.

## Your Environment

![gephi](https://user-images.githubusercontent.com/15825274/52921141-50274e00-32ea-11e9-84dd-a25deb0882e3.png)
![ubuntu](https://user-images.githubusercontent.com/15825274/52921142-50bfe480-32ea-11e9-8e20-4bbdb33a9df0.png)

**Comment by eduramiba** [comment]
Hi,
Java 9+ support is not yet possible in Gephi.
Also, if the graph window does not work, it's always useful to try to update graphics card drivers.

**Comment by paredesroger** [comment]
Thanks, @eduramiba.

Fortunately, my graphic card did not present issues and the instructions under "Possible Solution" worked for me.

I think you should link handy some instructions on how to get and set Gephi to use the right Java version in Ubuntu. Users like myself will be discouraged after encountering more than one issue, and not starting with the right Java version from the get go should be none of them.

I'm loving Gephi anyways!

**Comment by mittenchops** [comment]
Gephi is amazing, and thank you team for your work on it.

I am having the same issue above, same error message.  From [here,](https://askubuntu.com/a/219864/29907) I understand that 

> For Intel, the Open Source drivers that come with Ubuntu are always up to date. There is no need to update them (Very different than ATI or Nvidia for example). Ubuntu always comes with the latest Intel driver when it comes out and it also updates the Intel drivers with the most updated Open Source version available.

So, I believe my video drivers to be as up-to-date as possible.  

I agree with @paredesroger that it would be really helpful if there were some error message telling me to use a different java version---as trying to track this error down this was deeply confusing to me, and nearly resulted in me messing up my system by installing whacky out of date video drivers I found in conflicting and out of date information online, when the solution is not video, but rather changing java versions---something I didn't even know I could do before finding this link!

**Comment by cmclean5** [comment]
Ah, 'possible solution' works for us. Great. Thanks

**Comment by LyapunovShao** [comment]
It works for me, too.

**Comment by KokeCacao** [comment]
It turns out that you don't need to download another JRE if you have one 1.8 version on your laptop. Mine won't recognize its right path. Just do `which java` then look for the `jre` folder (something like `/usr/local/java/jre`). Open `path_to/gephi-0.9.2-linux/gephi-0.9.2/etc/gephi.conf` and set jdkhome="/usr/local/java/jre"

**Comment by laimaretto** [comment]
Still cannot make it work. I have openjdk-1.8 on Ubuntu 20.04 and the main page is still stuck at 'initializing'...

```
$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
```

I have also tried @KokeCacao 's idea of setting the path to jre under the config file, but it does not work either ...

any help with this? thanks a lot!

**Comment by laimaretto** [comment]
So I solved it by doing [this](https://github.com/gephi/gephi/issues/2189#issuecomment-636301758)
`$ export LIBGL_ALWAYS_SOFTWARE=1`

**Comment by theisuru** [comment]
setting Oracle jre did not solve it form me but @laimaretto solution of `export LIBGL_ALWAYS_SOFTWARE=1` worked fine for Ubuntu 20.04.2 LTS

**Comment by mbastian** [comment]
Hi, thanks for your report. The latest version of Gephi ([0.9.3](https://github.com/gephi/gephi/releases/tag/v0.9.3)) embed Java (JRE11) on Linux as well so no need anymore to install Java separately. This should solve most Java compatibility issues. We've also published it to [Snapcraft](https://snapcraft.io/gephi).
