### ISSUE TITLE
Cannot set value if type of column is double

### ISSUE THREAD

**Issue by arpicheck** [gephi/gephi#2124]
**Prerequisite**
Scripting plugin should be installed

**Repro steps**
Create a node
Create a data column, named **scaled**, with the type **Double**.
Set the the value of **scaled** to 0.0, using the Edit window.

Using the Console (scripting), execute the following command:
`iter(g.nodes).next().scaled = iter(g.nodes).next().scaled`

This should set the first (in your case only) node's **scaled** column to its own value.
However you will receive the error message below:

> Traceback (most recent call last):
>   File "<input>", line 1, in <module>
> IllegalArgumentException: java.lang.IllegalArgumentException: The object class does not match with the column type (java.lang.Double)

Try this command:
`type(iter(g.nodes).next().scaled)`

Result will be:

> <type 'float'>

In my opinion, this means, that the column **scaled** , type of _java.lang.Double_, will be converted to the python type _float_, but this conversion is irreversible.

I found no way to assign any value to a data column having the type of **Double**.

**Comment by eduramiba** [comment]
Hi,
I think you should be able to import java `Double` and use it:

```
from java.lang import Double
```

and then create a `new Double`

**Comment by arpicheck** [comment]
Hi,

`iter(g.nodes).next().scaled = Double.MAX_VALUE`

> Traceback (most recent call last):
>   File "<input>", line 1, in <module>
> IllegalArgumentException: java.lang.IllegalArgumentException: The object class does not match with the column type (java.lang.Double)

By the way, should not my first example work out of the box?
Once again:

`iter(g.nodes).next().scaled = iter(g.nodes).next().scaled`

I think, but I do not know, that there is a default mapping/proxy if you use the scripting plugin. It maps java.lang.Double to float automatically, and starting out from the above experiment, it is mapping non-integer python types to java.lang.Float.

**Comment by eduramiba** [comment]
I see, not sure what's happening there. We will need to check it.

**Comment by arpicheck** [comment]
Let me know, if I can help you somehow.
