### ISSUE TITLE
Gephi shredded .gephi file while saving

### ISSUE THREAD

**Issue by MaxMLeip** [gephi/gephi#2219]
## Expected Behavior

Gephi saves a .gephi project file correctly without destroying the data.

## Current Behavior

Gephi saved a .gephi file and three additional files in the .gephi_temp format. I cannot open any of these files and get this error code:
"
java.io.EOFException
	at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:290)
	at org.gephi.graph.impl.Serialization.deserialize(Serialization.java:1784)
	at org.gephi.graph.impl.Serialization.deserializeGraphStore(Serialization.java:345)
	at org.gephi.graph.impl.Serialization.deserialize(Serialization.java:2062)
	at org.gephi.graph.impl.Serialization.deserializeGraphModel(Serialization.java:245)
	at org.gephi.graph.api.GraphModel$Serialization.read(GraphModel.java:135)
	at org.gephi.graph.GraphPersistenceProvider.readBytes(GraphPersistenceProvider.java:88)
Caused: java.lang.RuntimeException
	at org.gephi.graph.GraphPersistenceProvider.readBytes(GraphPersistenceProvider.java:93)
	at org.gephi.project.io.LoadTask.readWorkspaceChildrenBytes(LoadTask.java:327)
	at org.gephi.project.io.LoadTask.run(LoadTask.java:130)
Caused: org.gephi.project.io.GephiFormatException: Gephi failed importing the project.

Exception: RuntimeException : java.io.EOFException
File: org.gephi.graph.GraphPersistenceProvider
Line : 93
	at org.gephi.project.io.LoadTask.run(LoadTask.java:173)
	at org.gephi.desktop.project.ProjectControllerUIImpl$7.run(ProjectControllerUIImpl.java:341)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
"
## Possible Solution

It might have something to do with xml formatting. Already unpacked and repacked the .gephi file but it produces the same error. I have attached the files if someone has an idea on how to recover the data.

## Steps to Reproduce

1. Install gephi under environment
2. save as .gephi file
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: build 1.8.0_261-b12
* Operating System: OSX 10.14.6

**Comment by mbastian** [comment]
Thanks for the report, unfortunately you actually didn't attach any files and without it I'm not able to reproduce the error. Could you add them? Thank you!
