### ISSUE TITLE
java.lang.ClassCastException: org.gephi.graph.api.types.TimestampSet cannot be cast to org.gephi.graph.api.types.TimeMap

### ISSUE THREAD

**Issue by zhaokoh** [gephi/gephi#2297]
## Expected Behavior

Able to save a Gephi project and re-open it without any loss of data or Gephi functionality.

## Current Behavior

Every time I save a Gephi project with timestamp, close Gephi, and re-open the Gephi project, I got the following error:

```
Exception: ClassCastException : org.gephi.graph.api.types.TimestampSet cannot be cast to org.gephi.graph.api.types.TimeMap
File: org.gephi.appearance.AttributePartitionImpl
Line : 91
	at org.gephi.project.io.LoadTask.run(LoadTask.java:173)
	at org.gephi.desktop.project.ProjectControllerUIImpl$7.run(ProjectControllerUIImpl.java:341)
	at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: org.gephi.graph.api.types.TimestampSet cannot be cast to org.gephi.graph.api.types.TimeMap
	at org.gephi.appearance.AttributePartitionImpl.refresh(AttributePartitionImpl.java:91)
	at org.gephi.appearance.AppearanceModelImpl$ElementFunctionsModel.refreshAttributeFunctions(AppearanceModelImpl.java:549)
	at org.gephi.appearance.AppearanceModelImpl$ElementFunctionsModel.refreshFunctions(AppearanceModelImpl.java:482)
	at org.gephi.appearance.AppearanceModelImpl$FunctionsModel.getFunctions(AppearanceModelImpl.java:420)
	at org.gephi.appearance.AppearanceModelImpl$FunctionsModel.getEdgeFunctions(AppearanceModelImpl.java:416)
	at org.gephi.appearance.AppearanceModelImpl.getEdgeFunctions(AppearanceModelImpl.java:132)
	at org.gephi.desktop.appearance.AppearanceUIModel.initSelectedTransformerUIs(AppearanceUIModel.java:107)
	at org.gephi.desktop.appearance.AppearanceUIModel.<init>(AppearanceUIModel.java:99)
	at org.gephi.desktop.appearance.AppearanceUIController$1.select(AppearanceUIController.java:109)
	at org.gephi.project.impl.ProjectControllerImpl.fireWorkspaceEvent(ProjectControllerImpl.java:331)
	at org.gephi.project.impl.ProjectControllerImpl.openProject(ProjectControllerImpl.java:240)
	at org.gephi.project.io.LoadTask.run(LoadTask.java:161)
	... 7 more
```

## Steps to Reproduce

1. Create a new project, import data that contains timestamp information, e.g.
```
Source,Target,Timestamp
1,2,<[2019-01-11T00:00:00]>
3,2,<[2019-01-11T00:00:00]>
4,2,<[2019-01-11T00:00:00]>
2,2,<[2019-01-11T00:00:00]>
5,6,<[2019-01-11T00:00:00]>
6,5,<[2019-01-10T00:00:00]>
6,7,<[2019-01-10T00:00:00]>
5,6,<[2019-01-09T00:00:00]>
7,6,<[2019-01-09T00:00:00]>
6,6,<[2019-01-09T00:00:00]>
8,1,<[2019-01-10T00:00:00]>
1,9,<[2019-01-10T00:00:00]>
1,8,<[2019-01-10T00:00:00]>
```
2. Import node information.
3. Save the project. 
4. Close Gephi
4. Open Gephi and re-open this project.

## Context

Cannot load a saved Gephi file. Gephi opened fine without the timestamp column in Data Laboratory, after that, I am unable to interact with Appearance panel nor Layout panel.

## Your Environment

* Version used: Gephi 0.9.2 201709242018
* Java version: 1.8.0_144; Java HotSpot(TM) 64-Bit Server VM 25.144-b01
* Java runtime Runtime: Java(TM) SE Runtime Environment 1.8.0_144-b01
* Operating System: Mac OS X version 10.16 running on x86_64; UTF-8; en_AU (gephi)

**Comment by mbastian** [comment]
Fixed, will be shipped in the 0.9.3 release. Thanks for the detailed report, it helped a lot!
