### ISSUE TITLE
Double clicking .gephi file from a file manages application, opens Gephi but nothing is visible

### ISSUE THREAD

**Issue by ypanagis** [gephi/gephi#2301]
## Expected Behavior

When double-clicking a `.gephi` file, Gephi opens and the network visualization of network of the first Workspace, shows up in **Overview.**. Network data are also visible from the **Data Laboratory**.

## Current Behavior

The network visualization of network of the first Workspace does not show up and a small error message appear at the bottom right. The network data are also unavailable.

The following exception is raised:

```
java.lang.NullPointerException
	at org.gephi.graph.api.AttributeUtils.isNodeColumn(AttributeUtils.java:1160)
	at org.gephi.filters.plugin.attribute.AttributeRangeBuilder$AttributeRangeFilter.init(AttributeRangeBuilder.java:132)
	at org.gephi.filters.FilterProcessor.init(FilterProcessor.java:210)
	at org.gephi.filters.FilterModelPersistenceProvider.readXML(FilterModelPersistenceProvider.java:230)
	at org.gephi.filters.FilterModelPersistenceProvider.readXML(FilterModelPersistenceProvider.java:88)
	at org.gephi.project.io.LoadTask.readWorkspaceChildrenXML(LoadTask.java:298)
	at org.gephi.project.io.LoadTask.run(LoadTask.java:128)
Caused: org.gephi.project.io.GephiFormatException: Gephi failed importing the project.

Exception: NullPointerException : null
File: org.gephi.graph.api.AttributeUtils
Line : 1160
	at org.gephi.project.io.LoadTask.run(LoadTask.java:173)
	at org.gephi.desktop.project.ProjectControllerUIImpl$7.run(ProjectControllerUIImpl.java:341)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

## Steps to Reproduce

  -  Double click .gephi file from a file manager, eg. Windows Explorer

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8.301
* Operating System: Windows 10 and similar problem with MacOS

[messages.log](https://github.com/gephi/gephi/files/7172119/messages.log)

**Comment by mbastian** [comment]
This should be fixed for next release as we've increased reliability of the IO module.
