### ISSUE TITLE
Graph window in Overview stuck on initializing  

### ISSUE THREAD

**Issue by Alotsi** [gephi/gephi#2347]
Hi!
I've recently installed Gephi 0.9.2 on Windows 10 (64) with Java JDK 1.8. 
Gephi opens up normally but the Graph window is stuck on 'initializing..' and nothing is shown. Other windows in the Overview mode seem to work fine, as well as in Data Laboratory and in Preview.
A red stop sign appears on the bottom right with the following error:
```
java.lang.NoClassDefFoundError: Could not initialize class com.jogamp.opengl.GLProfile
	at org.gephi.visualization.swing.GLAbstractListener.getCaps(GLAbstractListener.java:173)
	at org.gephi.visualization.swing.NewtGraphCanvas.<init>(NewtGraphCanvas.java:66)
	at org.gephi.visualization.VizController.createNewtCanvas(VizController.java:315)
	at org.gephi.visualization.VizController.initInstances(VizController.java:125)
	at org.gephi.visualization.VizController.getInstance(VizController.java:88)
	at org.gephi.visualization.component.VizBarController.createDefaultGroups(VizBarController.java:99)
	at org.gephi.visualization.component.VizBarController.<init>(VizBarController.java:88)
	at org.gephi.visualization.component.GraphTopComponent.initCollapsePanel(GraphTopComponent.java:118)
	at org.gephi.visualization.component.GraphTopComponent.access$000(GraphTopComponent.java:77)
	at org.gephi.visualization.component.GraphTopComponent$1$1.run(GraphTopComponent.java:99)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

I have seen other posts that encountered similar issues but not on Windows so I couldn't use the solutions proposed.
Thank you!

**Comment by mbastian** [comment]
Thanks for the report. The failure here (`GLProfile` initialization error / "Can't find the Intel Graphics" at startup) comes from the old engine's profile-detection code, which Gephi 0.11 replaced with a new visualization engine implementation that has different driver/profile requirements.

Could you retry on the latest 0.11.x release with an updated Intel graphics driver? If it still reproduces, please open a fresh issue with your Windows version, JDK version, and GPU driver version. Closing this for now as superseded by the new engine.
