### ISSUE TITLE
NullPointerException at javax.swing.ImageIcon for Open dialogs on Windows 7

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#24]
Gephi running on Windows 7 sometimes throws an Exception when users open file dialogs (Open project, Open, Save As).

Stack:
java.lang.NullPointerException
	at javax.swing.ImageIcon.&lt;init&gt;(ImageIcon.java:190)
	at javax.swing.ImageIcon.&lt;init&gt;(ImageIcon.java:176)
	at sun.swing.WindowsPlacesBar.&lt;init&gt;(WindowsPlacesBar.java:82)
	at com.sun.java.swing.plaf.windows.WindowsFileChooserUI.updateUseShellFolder(WindowsFileChooserUI.java:505)
	at com.sun.java.swing.plaf.windows.WindowsFileChooserUI.installComponents(WindowsFileChooserUI.java:196)
	at javax.swing.plaf.basic.BasicFileChooserUI.installUI(BasicFileChooserUI.java:136)
	at com.sun.java.swing.plaf.windows.WindowsFileChooserUI.installUI(WindowsFileChooserUI.java:129)
	at javax.swing.JComponent.setUI(JComponent.java:673)
	at javax.swing.JFileChooser.updateUI(JFileChooser.java:1763)
	at javax.swing.JFileChooser.setup(JFileChooser.java:360)
	at javax.swing.JFileChooser.&lt;init&gt;(JFileChooser.java:342)
	at javax.swing.JFileChooser.&lt;init&gt;(JFileChooser.java:301)
	at org.gephi.branding.desktop.actions.OpenFile.actionPerformed(OpenFile.java:65)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1995)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2318)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:357)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1225)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1266)
	at java.awt.Component.processMouseEvent(Component.java:6263)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3267)
	at java.awt.Component.processEvent(Component.java:6028)
	at java.awt.Container.processEvent(Container.java:2041)
	at java.awt.Component.dispatchEventImpl(Component.java:4630)
	at java.awt.Container.dispatchEventImpl(Container.java:2099)
	at java.awt.Component.dispatchEvent(Component.java:4460)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4574)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4238)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4168)
	at java.awt.Container.dispatchEventImpl(Container.java:2085)
	at java.awt.Component.dispatchEvent(Component.java:4460)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:599)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:125)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2010-02-22T18:23:43Z
 * owner: mathieu.bastian
 * assignee: mathieu.bastian
 * the launchpad url was https://bugs.launchpad.net/bugs/525928

**Comment by mbastian** [comment]
AFAIK that was fixed by the JRE. Mark as won't fix.
