### ISSUE TITLE
Graph tab stuck on "initializing" (linux ubuntu)

### ISSUE THREAD

**Issue by Nolicae** [gephi/gephi#2432]
## Expected Behavior

A graph should appear once the excel sheets are imported

## Current Behavior

Nothing appears let alone that small "initializing" text

## Steps to Reproduce

1. Create a new project
2. Import a nodes/edges file in cvs in the laboratory tab
3. Go back to the home tab
4. The graph tab is eternally initializing

## Context

I am taking informatics class in my college, and will be assessed based on a graph that I will have realized with Gephi. Pretty simple, uh? Turns out I cannot seem to produce any graph. Being his only student operating on Linux, the instructor was not acquainted with the issue. I figured I may find a solution on internet, but I did not understand anything to the posts tackling the same issue.

I hope you will be able to help me!

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8.0_312
* Operating System: Linux Ubuntu 20.04.3

**Comment by Nolicae** [comment]
I have this error report? No idea how to interpret it though

com.jogamp.opengl.GLException: Profile GL2 is not available on X11GraphicsDevice[type .x11, connection :0, unitID 0, handle 0x0, owner false, ResourceToolkitLock[obj 0x54140b91, isOwner false, <30310c69, 40a6a954>[count 0, qsz 0, owner <NULL>]]], but: [GLProfile[GLES1/GLES1.hw], GLProfile[GLES2/GLES3.hw], GLProfile[GL2ES1/GLES1.hw], GLProfile[GL4ES3/GL4.hw], GLProfile[GL2ES2/GL4.hw], GLProfile[GL4/GL4.hw], GLProfile[GLES3/GLES3.hw], GLProfile[GL4/GL4.hw], GLProfile[GL3/GL4.hw], GLProfile[GL2GL3/GL4.hw]]
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:991)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1004)
	at org.gephi.visualization.swing.GLAbstractListener.getCaps(GLAbstractListener.java:173)
	at org.gephi.visualization.swing.NewtGraphCanvas.<init>(NewtGraphCanvas.java:66)
	at org.gephi.visualization.VizController.createNewtCanvas(VizController.java:315)
	at org.gephi.visualization.VizController.initInstances(VizController.java:125)
	at org.gephi.visualization.VizController.getInstance(VizController.java:88)
	at org.gephi.visualization.component.VizBarController.createDefaultGroups(VizBarController.java:99)
	at org.gephi.visualization.component.VizBarController.<init>(VizBarController.java:88)
	at org.gephi.visualization.component.GraphTopComponent.initCollapsePanel(GraphTopComponent.java:118)
	at org.gephi.visualization.component.GraphTopComponent.access$000(GraphTopComponent.java:77)
	at org.gephi.visualization.component.GraphTopComponent$1$1.run(GraphTopComponent.java:99)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by martinzh** [comment]
Some discussion has been done in [this issue](https://github.com/gephi/gephi/issues/1836). I was having the same problem as you with Manjaro. When I use the suggested solution: `MESA_LOADER_DRIVER_OVERRIDE=i965 ./gephi` That error goes away and the graph is displayed. however, when I try to zoom or explore it I get a "fatal error" and Gephi crashes...

**Comment by Nolicae** [comment]
> Some discussion has been done in [this issue](https://github.com/gephi/gephi/issues/1836). I was having the same problem as you with Manjaro. When I use the suggested solution: `MESA_LOADER_DRIVER_OVERRIDE=i965 ./gephi` That error goes away and the graph is displayed. however, when I try to zoom or explore it I get a "fatal error" and Gephi crashes...

Thank you very much, works for me too (until I push it too far and it crashes as well). I think I will just use this solution to follow the class, and render my graded project with my windows pc at home :)

**Comment by mbastian** [comment]
Thanks for the report. This is a native-GL-loading/profile failure (`GLException`/SIGSEGV tied to your Mesa or `libGLX_mesa.so` version, or a Wayland/KDE-specific native crash) in the old rendering engine, which Gephi 0.11 replaced with a new visualization engine implementation with different driver/OpenGL-version requirements and a different native library loading path.

Could you retry on the latest 0.11.x release with your current Mesa/driver stack? If it still reproduces, please open a fresh issue with your distro, Mesa version, and display server (X11/Wayland) details. Closing this for now as superseded by the new engine.
