### ISSUE TITLE
Semantic Web Importer - Error 303 See other / SERIOUS End of  file

### ISSUE THREAD

**Issue by bablf** [gephi/gephi#2434]
## Expected Behavior
I want to query `https://dbpedia.org/sparql`.

## Current Behavior
When Inserting "http://dbpedia.org/sparql" I get the following logs: 
```
2022 8:46:52 AM fr.inria.edelweiss.sparql.restdriver.SparqlRestEndPointDriver sparqlQuery -- INFORMATION: fr.inria.edelweiss.sparql.restdriver.SparqlRestEndPointDriver executing request: query=construct+%7B%0A%3Fx+%3Fr+%3Fy+%0A%7D+where+%7B%0A%3Fx+%3Fr+%3Fy+%0A%7D+limit+100 -- 
Mär 01, 2022 8:46:53 AM fr.inria.edelweiss.sparql.restdriver.SparqlRestEndPointDriver sparqlQuery -- INFORMATION: Result request: -- 
Mär 01, 2022 8:46:53 AM fr.inria.edelweiss.sparql.restdriver.SparqlRestEndPointDriver sparqlQuery -- INFORMATION: <html> -- 
Mär 01, 2022 8:46:53 AM fr.inria.edelweiss.sparql.restdriver.SparqlRestEndPointDriver sparqlQuery -- INFORMATION: <head><title>303 See Other</title></head> -- 
Mär 01, 2022 8:46:53 AM fr.inria.edelweiss.sparql.restdriver.SparqlRestEndPointDriver sparqlQuery -- INFORMATION: <body> -- 
Mär 01, 2022 8:46:53 AM fr.inria.edelweiss.sparql.restdriver.SparqlRestEndPointDriver sparqlQuery -- INFORMATION: <center><h1>303 See Other</h1></center> -- 
Mär 01, 2022 8:46:53 AM fr.inria.edelweiss.sparql.restdriver.SparqlRestEndPointDriver sparqlQuery -- INFORMATION: <hr><center>nginx/1.18.0</center> -- 
Mär 01, 2022 8:46:53 AM fr.inria.edelweiss.sparql.restdriver.SparqlRestEndPointDriver sparqlQuery -- INFORMATION: </body> -- 
Mär 01, 2022 8:46:53 AM fr.inria.edelweiss.sparql.restdriver.SparqlRestEndPointDriver sparqlQuery -- INFORMATION: </html> -- 
Mär 01, 2022 8:46:53 AM fr.inria.edelweiss.sparql.restdriver.SparqlRestEndPointDriver sparqlQuery -- INFORMATION: Result contains 7 lines. -- 
```
The 303 See Other Errror indicates that the request gets forwarded to `https://dbpedia.org/sparql`. (As it happens in the browser as well.) 

BUT, if I put `https://dbpedia.org/sparql` in the EndPoint URL I get the following 
```

Mär 01, 2022 9:21:52 AM fr.inria.edelweiss.semantic.SemanticWebImportMainWindowTopComponent startCreateGraphs -- INFORMATION: Entering startCreateGraphs -- 
Mär 01, 2022 9:21:52 AM fr.inria.edelweiss.semantic.SemanticWebImportMainWindowTopComponent startCreateGraphs -- INFORMATION: Starting the RDF importer for Gephi -- 
Mär 01, 2022 9:21:52 AM fr.inria.edelweiss.semantic.importer.SemanticWebImportParser populateRDFGraph -- INFORMATION: resetWorkspace = false -- 
Mär 01, 2022 9:21:52 AM fr.inria.edelweiss.semantic.importer.SemanticWebImportParser populateRDFGraph -- INFORMATION: postProcessing = false -- 
Mär 01, 2022 9:21:52 AM fr.inria.edelweiss.semantic.analyzer.RdfAnalyzer run -- INFORMATION: Begin: Building the implementation relationships graph. -- 
Mär 01, 2022 9:21:52 AM fr.inria.edelweiss.sparql.restdriver.SparqlRestEndPointDriver sparqlQuery -- INFORMATION: fr.inria.edelweiss.sparql.restdriver.SparqlRestEndPointDriver executing request: query=CONSTRUCT%7B%0A++%3Fperson+%3Chttp%3A%2F%2Fgephi.org%2Ftype%3E+%22person%22.%0A++%3Fmovie+%3Chttp%3A%2F%2Fgephi.org%2Ftype%3E+%22movie%22.%0A++%3Fmovie+%3Chttp%3A%2F%2Ftoto%2Flink%3E+%3Fperson+.%0A%7D%0AWHERE%0A%7B%0A+%3Fmovie+a+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FFilm%3E.%0A+%3Fmovie+%3Frel1+%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FLeonardo_DiCaprio%3E.%0A+%3Fmovie+%3Frel2+%3Fperson.%0A+%3Fperson+a+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FPerson%3E.%0A%7D -- 
Mär 01, 2022 9:21:52 AM fr.inria.edelweiss.sparql.RdfParser$1 fatalError -- SCHWERWIEGEND: Premature end of file. -- 
Mär 01, 2022 9:21:52 AM fr.inria.edelweiss.semantic.analyzer.RdfAnalyzer run -- INFORMATION: Number of triples parsed: 0 -- 
Mär 01, 2022 9:21:52 AM fr.inria.edelweiss.semantic.analyzer.EmptyPostProcessor run -- INFORMATION: Applying empty post-processing -- 
Mär 01, 2022 9:21:52 AM fr.inria.edelweiss.semantic.analyzer.RdfAnalyzer run -- INFORMATION: End: Building the implementation relationships graph. -- 
Mär 01, 2022 9:21:52 AM fr.inria.edelweiss.semantic.SemanticWebImportMainWindowTopComponent taskFinished -- INFORMATION: Finished startCreateGraphs. Time elapsed = 160 milliseconds -- 

```
The Errror `SCHWERWIEGEND: Premature end of file.` (SCHWERWIEGEND is german for SERIOUS) seems to be the problem. As a result the data does not get loaded an the data laboritry remains empty.  

I also had a case where I got a popup saying "The entered URL is not valid." But that does not happen anymore after I reinstalled the plugin. 
## Possible Solution
Come to think of it. Could it be that it stops downloading the file after a while? Kind of like when curl times out and stops the download process?

EDIT: 
I found the "other logs" (when clicking on window). They gave me the following error message: 

```
[SEVERE] null 
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1002)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
	at sun.net.www.protocol.http.HttpURLConnection.access$100(HttpURLConnection.java:91)
	at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1283)
	at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1281)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1280)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at fr.inria.edelweiss.sparql.restdriver.SparqlRestEndPointDriver.sparqlQuery(SparqlRestEndPointDriver.java:67)
	at fr.inria.edelweiss.semantic.analyzer.RdfAnalyzer.run(RdfAnalyzer.java:61)
	at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(InputRecord.java:505)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	... 21 more
```
I don't know java but it seems like there is some kind of issue handling the SSL? 

## Steps to Reproduce

1. Install Semantic Web Importer Plugin
2. Open up the Importer (under Window)
3. Select Remote - REST endpoint for the SPARQL Driver
4. In EndPoint RL enter `https://dbpedia.org/sparql` or `http://dbpedia.org/sparql`
5. In the Query Tab enter a query. I used: 
6. 
```
CONSTRUCT{
  ?person <http://gephi.org/type> "person".
  ?movie <http://gephi.org/type> "movie".
  ?movie <http://toto/link> ?person .
}
WHERE
{
 ?movie a <http://dbpedia.org/ontology/Film>.
 ?movie ?rel1 <http://dbpedia.org/resource/Leonardo_DiCaprio>.
 ?movie ?rel2 ?person.
 ?person a <http://dbpedia.org/ontology/Person>.
}
```
7. Press run and look at logs

## Context

I want to use the official DBpedia Sparql Endpoint and am also trying to setup a local dbpedia instance. That instance runs on localhost:8890 and works perfectly in the browser.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8.0_311
* Operating System:  MacOS

**Comment by totetmatt** [comment]
Hey @bablf  I mange to reproduce the error and find out how a way to get around it .

I manage to make it work only when I'm copy pasting (ctrl-c + ctrl-v) the `EntryPointUrl `OR if I press the  `Enter keyboard key` after typing the `EntryPointUrl `by hand.

Could you tell me if it's working with this trick ?

**Comment by bablf** [comment]
No Idea why that fixes it but yes. Closing issue.

**Comment by totetmatt** [comment]
Good to hear, I'll see if I can patch the plugin to be less confusing with this glitch  :)
