### ISSUE TITLE
`com.jogamp.opengl.GLException` when running from `904a8eba559ca961c4ad54a4c0d11965e9e7b475`

### ISSUE THREAD

**Issue by nikclayton** [gephi/gephi#2457]
## Expected Behavior

Start Gephi, the graph display panel quickly moves on from displaying "Initializing..." and graphs can be displayed.

## Current Behavior

Build Gephi from source, the graph display panel is stuck on "Initializing...". The log shows 

```
SEVERE [global]
com.jogamp.opengl.GLException: Unable to determine GraphicsConfiguration: WindowsWGLGraphicsConfiguration[DefaultGraphicsScreen[WindowsGraphicsDevice[type .windows, connection decon, unitID 0, handle 0x0, owner false, NullToolkitLock[obj 0x52068b2a]], idx 0], pfdID 37, ARB-Choosen true,
	requested GLCaps[rgba 8/8/8/8, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/0/4, sample-ext default, dbl, mono  , hw, GLProfile[GL2/GL4bc.hw], on-scr[.]],
	chosen    GLCaps[wgl vid 37 arb: rgba 8/8/8/8, opaque, accum-rgba 16/16/16/16, dp/st/ms 16/0/4, sample-ext default, dbl, mono  , hw, GLProfile[GL2/GL4bc.hw], on-scr[.]]]
	at jogamp.opengl.windows.wgl.awt.WindowsAWTWGLGraphicsConfigurationFactory.chooseGraphicsConfigurationImpl(WindowsAWTWGLGraphicsConfigurationFactory.java:182)
	at com.jogamp.nativewindow.GraphicsConfigurationFactory.chooseGraphicsConfiguration(GraphicsConfigurationFactory.java:424)
	at com.jogamp.nativewindow.awt.AWTGraphicsConfiguration.create(AWTGraphicsConfiguration.java:104)
	at com.jogamp.newt.awt.NewtCanvasAWT.addNotify(NewtCanvasAWT.java:600)
	at java.desktop/java.awt.Container.addImpl(Container.java:1150)
	at java.desktop/java.awt.Container.add(Container.java:1001)
	at org.gephi.visualization.component.GraphTopComponent$1$1.run(GraphTopComponent.java:113)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

which seems suspicious. I've included the full log below.

The nightly build gephi-0.9.3-20220315.200336-319-windows.exe running on the same computer does not have this problem.

## Steps to Reproduce

Follow the instructions at https://github.com/gephi/gephi:

1. `git clone https://github.com/gephi/gephi.git`
2. Checked out commit is `904a8eba559ca961c4ad54a4c0d11965e9e7b475` (with `git show-ref HEAD`)
3. Build / install with `mvn -T 4 clean installl`
4. Run with `mvn nbm:cluster-app nbm:run-platform` in `modules/application`.
5. Gephi window opens as expected, the graph display panel is stuck on "Initializing".

## Context

Gephi is unusable.

## Your Environment

* Version used: Gephi from commit 904a8eba559ca961c4ad54a4c0d11965e9e7b475
* Java version: 

```
> javac -version
javac 18
> java -version
java version "18" 2022-03-22
Java(TM) SE Runtime Environment (build 18+36-2087)
Java HotSpot(TM) 64-Bit Server VM (build 18+36-2087, mixed mode, sharing)
> mvn -version
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: C:\Users\Nik Clayton\apache-maven-3.8.5
Java version: 18, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-18
Default locale: en_GB, platform encoding: UTF-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

* Operating System: Windows 10

Full log is:

```
-------------------------------------------------------------------------------
>Log Session: Wednesday, March 30, 2022 at 12:53:12 PM Central European Summer Time
>System Info: 
  Product Version         = Gephi 0.9.3-SNAPSHOT 202203301045
  Operating System        = Windows 10 version 10.0 running on amd64
  Java; VM; Vendor        = 18; Java HotSpot(TM) 64-Bit Server VM 18+36-2087; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 18+36-2087
  Java Home               = C:\Program Files\Java\jdk-18
  System Locale; Encoding = en_GB (gephi); UTF-8
  Home Directory          = C:\Users\Nik Clayton
  Current Directory       = C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi
  User Directory          = C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\userdir
  Cache Directory         = C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\userdir\var\cache
  Installation            = C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\bin
                            C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\etc
                            C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\extra
                            C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\gephi
                            C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\platform
                            C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\platform
  Boot & Ext. Classpath   = 
  Application Classpath   = C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\platform\lib\boot.jar;C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\platform\lib\org-openide-modules.jar;C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\platform\lib\org-openide-util-lookup.jar;C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\platform\lib\org-openide-util-ui.jar;C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\platform\lib\org-openide-util.jar
  Startup Classpath       = C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\platform\core\asm-9.2.jar;C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\platform\core\asm-commons-9.2.jar;C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\platform\core\asm-tree-9.2.jar;C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\platform\core\core-base.jar;C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\platform\core\core.jar;C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\platform\core\org-netbeans-libs-asm.jar;C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\platform\core\org-openide-filesystems-compat8.jar;C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\platform\core\org-openide-filesystems.jar;C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\gephi\core\locale\core_gephi.jar
-------------------------------------------------------------------------------
INFO [org.netbeans.core.startup.NbEvents]: Turning on modules:
	org.openide.util.lookup [8.49 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.openide.util [9.23 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.openide.util.ui [9.24 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.openide.modules [7.63 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.api.annotations.common/1 [1.43 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.openide.filesystems [9.27 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.openide.awt [7.83 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.api.progress/1 [1.63 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.api.progress.nb [1.63 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.openide.dialogs [7.57 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.openide.nodes [7.60 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.openide.windows [6.92 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.libs.batik.read [1.8.0.1 1 Netbeans/netbeans-TLP/netbeans/release130-20-on-20220221]
	org.openide.util.ui.svg [1.9 Netbeans/netbeans-TLP/netbeans/release130-20-on-20220221]
	org.netbeans.modules.editor.mimelookup/1 [1.55 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.openide.text [6.83 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.api.scripting [1.12 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.swing.tabcontrol [1.71 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.swing.outline [1.49 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.openide.explorer [6.77 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.openide.actions [6.54 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.modules.queries/1 [1.58 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.api.templates [1.23 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.openide.filesystems.nb [9.25 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.openide.loaders [7.85 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.api.intent [1.17 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.api.io [1.18 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.openide.io [1.64 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.openide.filesystems.compat8 [9.24 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.swing.plaf [1.57 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.modules.keyring [1.39 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.libs.asm [5.18 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.bootstrap/1 [2.93 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.core.startup.base [1.77.0.1 1 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.core.startup/1 [1.77.0.1 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.modules.sampler [1.29 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.core/2 [3.66 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.spi.quicksearch [1.42 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.modules.options.api/1 [1.60 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.libs.flatlaf/1 [1.9 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.swing.laf.flatlaf [1.8 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.swing.laf.dark/1 [2.10.0.2 2 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.modules.templates/1 [1.22 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.modules.settings/1 [1.64 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.modules.sendopts/2 [2.51 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.modules.progress.ui [1.48 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.modules.print [7.41 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.modules.options.keymap [1.52 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.libs.jna/2 [2.10 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.modules.masterfs/2 [2.70.0.2 2 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.modules.masterfs.windows [1.31 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.modules.masterfs.ui [2.18.0.2 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.modules.masterfs.nio2 [1.30 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.modules.keyring.fallback [1.23 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.modules.keyring.impl [1.39 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.modules.janitor [1.8 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.modules.favorites/1 [1.61 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.modules.autoupdate.services [1.70 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.modules.autoupdate.cli [1.29 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.core.windows/2 [2.100 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.core.ui/1 [1.60 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.libs.osgi [1.37 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.libs.felix [2.30 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.modules.autoupdate.ui [1.61 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.modules.core.kit [1.46 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.libs.jna.platform/2 [2.10 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.core.output2/1 [1.57 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.core.network [1.27 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.core.nativeaccess/1 [1.46 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.core.multitabs/1 [1.27.0.1 1 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.core.io.ui/1 [1.45 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.netbeans.api.progress.compat8 [1.62 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655]
	org.gephi.core.library.wrapper [0.9.3 0.9.3-20220330 202203301045]
	org.gephi.utils.longtask [0.9.3 0.9.3-20220330 202203301045]
	org.gephi.project.api [0.9.3 0.9.3-20220330 202203301046]
	org.gephi.graph.api [0.9.3 0.9.3-20220330 202203301046]
	org.gephi.utils [0.9.3 0.9.3-20220330 202203301046]
	org.gephi.ui.library.wrapper [0.9.3 0.9.3-20220330 202203301045]
	org.gephi.ui.utils [0.9.3 0.9.3-20220330 202203301046]
	org.gephi.ui.components [0.9.3 0.9.3-20220330 202203301047]
	org.gephi.db.drivers [0.9.3 0.9.3-20220330 202203301045]
	org.gephi.io.importer.api [0.9.3 0.9.3-20220330 202203301047]
	org.gephi.mostrecentfiles.api [0.9.3 0.9.3-20220330 202203301045]
	org.gephi.desktop.project [0.9.3 0.9.3-20220330 202203301048]
	org.gephi.welcome.screen [0.9.3 0.9.3-20220330 202203301048]
	org.gephi.datalab.api [0.9.3 0.9.3-20220330 202203301046]
	org.gephi.visualization.api [0.9.3 0.9.3-20220330 202203301047]
	org.gephi.tools.api [0.9.3 0.9.3-20220330 202203301046]
	org.gephi.visualization [0.9.3 0.9.3-20220330 202203301048]
	org.gephi.algorithms.plugin [0.9.3 0.9.3-20220330 202203301046]
	org.gephi.tools.plugin [0.9.3 0.9.3-20220330 202203301049]
	org.gephi.statistics.api [0.9.3 0.9.3-20220330 202203301047]
	org.gephi.statistics.plugin [0.9.3 0.9.3-20220330 202203301049]
	org.gephi.filters.api [0.9.3 0.9.3-20220330 202203301046]
	org.gephi.appearance.api [0.9.3 0.9.3-20220330 202203301046]
	org.gephi.filters.plugin [0.9.3 0.9.3-20220330 202203301049]
	org.gephi.timeline.api [0.9.3 0.9.3-20220330 202203301050]
	org.gephi.statistics.plugin.ui [0.9.3 0.9.3-20220330 202203301049]
	org.gephi.settings.upgrader [0.9.3 0.9.3-20220330 202203301045]
	org.gephi.batik.wrapper [0.9.3 0.9.3-20220330 202203301045]
	org.gephi.preview.api [0.9.3 0.9.3-20220330 202203301046]
	org.gephi.preview.plugin [0.9.3 0.9.3-20220330 202203301048]
	org.gephi.io.exporter.api [0.9.3 0.9.3-20220330 202203301046]
	org.gephi.io.exporter.preview [0.9.3 0.9.3-20220330 202203301047]
	org.gephi.preview.export.ui [0.9.3 0.9.3-20220330 202203301048]
	org.gephi.perspective.api [0.9.3 0.9.3-20220330 202203301046]
	org.gephi.layout.api [0.9.3 0.9.3-20220330 202203301047]
	org.gephi.layout.plugin [0.9.3 0.9.3-20220330 202203301047]
	org.gephi.io.importer.plugin [0.9.3 0.9.3-20220330 202203301048]
	org.gephi.io.generator.api [0.9.3 0.9.3-20220330 202203301048]
	org.gephi.io.generator.plugin [0.9.3 0.9.3-20220330 202203301048]
	org.gephi.io.exporter.plugin [0.9.3 0.9.3-20220330 202203301046]
	org.gephi.import.plugin.ui [0.9.3 0.9.3-20220330 202203301049]
	org.gephi.generator.plugin.ui [0.9.3 0.9.3-20220330 202203301049]
	org.gephi.desktop.window [0.9.3 0.9.3-20220330 202203301047]
	org.gephi.filters.plugin.ui [0.9.3 0.9.3-20220330 202203301050]
	org.gephi.filters.impl [0.9.3 0.9.3-20220330 202203301050]
	org.gephi.export.plugin.ui [0.9.3 0.9.3-20220330 202203301047]
	org.gephi.directory.chooser [0.9.3 0.9.3-20220330 202203301046]
	org.gephi.desktop.tools [0.9.3 0.9.3-20220330 202203301049]
	org.gephi.desktop.timeline [0.9.3 0.9.3-20220330 202203301050]
	org.gephi.desktop.statistics [0.9.3 0.9.3-20220330 202203301047]
	org.gephi.desktop.io.export [0.9.3 0.9.3-20220330 202203301047]
	org.gephi.desktop.preview [0.9.3 0.9.3-20220330 202203301048]
	org.gephi.desktop.layout [0.9.3 0.9.3-20220330 202203301047]
	org.gephi.desktop.import [0.9.3 0.9.3-20220330 202203301048]
	org.gephi.desktop.generate [0.9.3 0.9.3-20220330 202203301049]
	org.gephi.desktop.filters [0.9.3 0.9.3-20220330 202203301047]
	org.gephi.desktop.datalab [0.9.3 0.9.3-20220330 202203301048]
	org.gephi.desktop.context [0.9.3 0.9.3-20220330 202203301047]
	org.gephi.desktop.branding [0.9.3 0.9.3-20220330 202203301049]
	org.gephi.appearance.plugin [0.9.3 0.9.3-20220330 202203301047]
	org.gephi.appearance.plugin.ui [0.9.3 0.9.3-20220330 202203301048]
	org.gephi.desktop.appearance [0.9.3 0.9.3-20220330 202203301048]
	org.gephi.datalab.plugin [0.9.3 0.9.3-20220330 202203301049]
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy resolver: Windows
INFO [org.netbeans.core.network.proxy.windows.WindowsNetworkProxy]: Windows system proxy resolver: auto detect
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy reloading succeeded.
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy - mode: direct
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy: fell to default (correct if direct mode went before)
INFO [org.netbeans.ui.metrics.laf]: USG_LOOK_AND_FEEL
java.lang.IllegalAccessException: class org.netbeans.TopSecurityManager cannot access class sun.awt.AppContext (in module java.desktop) because module java.desktop does not export sun.awt to unnamed module @378bf509
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:394)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.netbeans.TopSecurityManager.makeSwingUseSpecialClipboard(TopSecurityManager.java:714)
	at org.netbeans.core.NbLifecycleManager.advancePolicy(NbLifecycleManager.java:71)
	at org.netbeans.core.GuiRunLevel.run(GuiRunLevel.java:84)
	at org.netbeans.core.startup.Main.start(Main.java:295)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:98)
	at java.base/java.lang.Thread.run(Thread.java:833)
Diagnostic information
Input arguments:
	-Dsun.java2d.metal=true
	-Dsun.java2d.noddraw=true
	-Dsun.awt.noerasebackground=true
	-Dapple.awt.graphics.UseQuartz=true
	-Dnetbeans.indexing.noFileRefresh=true
	-Dplugin.manager.check.interval=EVERY_DAY
	-Dnetbeans.logger.console=true
	-ea
	-Dnetbeans.user.dir=C:\Users\Nik Clayton\GitHub\gephi\modules\application
	-Djdk.home=C:\Program Files\Java\jdk-18
	-Dnetbeans.home=C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\platform
	-Dnetbeans.user=C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\userdir
	-Dnetbeans.default_userdir_root=C:\Users\Nik Clayton\AppData\Roaming\gephi
	-XX:+HeapDumpOnOutOfMemoryError
	-XX:HeapDumpPath=C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\userdir\var\log\heapdump.hprof
	-Dsun.awt.keepWorkingSetOnMinimize=true
	-Djava.security.manager=allow
	-Dnetbeans.dirs=C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\bin;C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\etc;C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\extra;C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\gephi;C:\Users\Nik Clayton\GitHub\gephi\modules\application\target\gephi\platform
Compiler: HotSpot 64-Bit Tiered Compilers
Heap memory usage: initial 508.0MB maximum 8128.0MB
Non heap memory usage: initial 7.3MB maximum -1b
Garbage collector: G1 Young Generation (Collections=7 Total time spent=0s)
Garbage collector: G1 Old Generation (Collections=0 Total time spent=0s)
Classes: loaded=7758 total loaded=7758 unloaded 0
SEVERE [global]
com.jogamp.opengl.GLException: Unable to determine GraphicsConfiguration: WindowsWGLGraphicsConfiguration[DefaultGraphicsScreen[WindowsGraphicsDevice[type .windows, connection decon, unitID 0, handle 0x0, owner false, NullToolkitLock[obj 0x52068b2a]], idx 0], pfdID 37, ARB-Choosen true,
	requested GLCaps[rgba 8/8/8/8, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/0/4, sample-ext default, dbl, mono  , hw, GLProfile[GL2/GL4bc.hw], on-scr[.]],
	chosen    GLCaps[wgl vid 37 arb: rgba 8/8/8/8, opaque, accum-rgba 16/16/16/16, dp/st/ms 16/0/4, sample-ext default, dbl, mono  , hw, GLProfile[GL2/GL4bc.hw], on-scr[.]]]
	at jogamp.opengl.windows.wgl.awt.WindowsAWTWGLGraphicsConfigurationFactory.chooseGraphicsConfigurationImpl(WindowsAWTWGLGraphicsConfigurationFactory.java:182)
	at com.jogamp.nativewindow.GraphicsConfigurationFactory.chooseGraphicsConfiguration(GraphicsConfigurationFactory.java:424)
	at com.jogamp.nativewindow.awt.AWTGraphicsConfiguration.create(AWTGraphicsConfiguration.java:104)
	at com.jogamp.newt.awt.NewtCanvasAWT.addNotify(NewtCanvasAWT.java:600)
	at java.desktop/java.awt.Container.addImpl(Container.java:1150)
	at java.desktop/java.awt.Container.add(Container.java:1001)
	at org.gephi.visualization.component.GraphTopComponent$1$1.run(GraphTopComponent.java:113)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
INFO [org.netbeans.core.ui.warmup.DiagnosticTask]: Total memory 34,075,033,600
INFO [null]: Total physical memory 34,075,033,600
WARNING [org.openide.filesystems.Ordering]: Not all children in Menu/View/ marked with the position attribute: [org-netbeans-core-windows-actions-ToggleFullScreenAction.instance], but some are: [ToggleFullScreenAction.shadow]
```

**Comment by nikclayton** [comment]
This problem does *not* occur using Java 11.0.13. I downloaded the JDK from https://www.oracle.com/java/technologies/javase/jdk11-archive-downloads.html, and with PATH/JAVA_HOME set appropriately Gephi runs correctly, logging:

```
[INFO] >Log Session: Wednesday, March 30, 2022 at 6:21:54 PM Central European Summer Time
[INFO] >System Info:
[INFO]   Product Version         = Gephi 0.9.3-SNAPSHOT 202203301615
[INFO]   Operating System        = Windows 10 version 10.0 running on amd64
[INFO]   Java; VM; Vendor        = 11.0.13; Java HotSpot(TM) 64-Bit Server VM 11.0.13+10-LTS-370; Oracle Corporation
[INFO]   Runtime                 = Java(TM) SE Runtime Environment 11.0.13+10-LTS-370
[INFO]   Java Home               = c:\Program Files\Java\jdk-11.0.13
[INFO]   System Locale; Encoding = en_GB (gephi); Cp1252

...

[INFO] INFO: GL_VENDOR: Intel
[INFO] INFO: GL_RENDERER: Intel(R) UHD Graphics 630
[INFO] INFO: GL_VERSION: 4.6.0 - Build 27.20.100.9664
[INFO] INFO: GL_SURFACE_SCALE: 1
[INFO] WARNING [org.openide.filesystems.Ordering]: Not all children in Menu/View/ marked with the position attribute: [org-netbeans-core-windows-actions-ToggleFullScreenAction.instance], but some are: [ToggleFullScreenAction.shadow]
```

**Comment by mbastian** [comment]
Hi @nikclayton, we have done testing and officially support JRE11 at this point. Until we switch to our new viz engine, we're dependant on [JOGL](https://jogamp.org/jogl/www/), which is barely maintained anymore. It has numerous bugs and instability with newer JREs. That's why we stick to JRE11 as we've done some testing and that's the JRE we found to have the least unexpected issues at this point.

**Comment by nikclayton** [comment]
The build instructions in README.md and the wiki both say version 11 or later. Any objection if I send a PR that updates them?

**Comment by mbastian** [comment]
No objections but let's be precise. You can **build** Gephi with a JRE version later than 11 and it should work. The problem is when you **run** it. This is where you'll potentially encounter issues with JRE > 11. It may work though as it depends on your graphics card, OS etc. so I think it's fair to say that we recommend JRE 11 for running Gephi.

**Comment by nikclayton** [comment]
OK. I think the build instructions should work out of the box -- building with one JRE version and running with another feels like an edge (no pun intended) case.

I suggest two modifications.

1. Replace the build instructions in README.md with a link to the instructions in the wiki. As well as reducing duplication of content (so it can't get out of sync), there's additional useful info in the wiki for developers, so it would be helpful to signpost it.
2. Update the build instructions in the wiki so that the *default* path (i.e., checkout the code, build it, run it, using Maven) makes it clear that JRE 11 is required.

I'm not sufficiently familiar with Maven to write instructions that explain how to build it with one JRE but run it with another. I can either start that section, but leave it marked "[TBD]", or someone else can add those instructions.

WDYT?

**Comment by mbastian** [comment]
Fair point, the simpler the better. I agree that we don't need the build instructions in the README.md so your plan to link to the wiki makes a lot of sense.

If you leave some space in the wiki as [TBD] I'm happy to finish it.

**Comment by benja-ct** [comment]
Found in a forum a solution to run it which is to remove jogamp*.tst* files from the TaskManager. It worked for me in the Gephi 0.9.1 but not in the 0.9.2 version (some conflict)

**Comment by mbastian** [comment]
@nikclayton Hi, any updates? I think you had some plans to update the wiki. Cheers,

**Comment by mbastian** [comment]
Closing as no response
