### ISSUE TITLE
NullPointerException in IndexImpl.values

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#2473]
https://sentry.io/organizations/gephi/issues/3182834826/?referrer=github_plugin

```
NullPointerException: None
    at org.gephi.graph.impl.IndexImpl.values(IndexImpl.java:145)
    at org.gephi.appearance.AttributePartitionImpl.getValues(AttributePartitionImpl.java:75)
    at org.gephi.appearance.PartitionImpl.getSortedValues(PartitionImpl.java:91)
    at org.gephi.ui.appearance.plugin.PartitionColorTransformerPanel.setup(PartitionColorTransformerPanel.java:116)
    at org.gephi.ui.appearance.plugin.PartitionElementColorTransformerUI.getPanel(PartitionElementColorTransformerUI.java:91)
...
(15 additional frame(s) were not displayed)
```

**Comment by mbastian** [comment]
I'm able to reproduce this issue. It appears when columns are removed.
