### ISSUE TITLE
NullPointerException in ProjectControllerUIImpl.openFile

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#2474]
https://sentry.io/organizations/gephi/issues/3174411505/?referrer=github_plugin

```
NullPointerException: None
    at org.gephi.desktop.project.ProjectControllerUIImpl.openFile(ProjectControllerUIImpl.java:568)
    at org.gephi.desktop.project.ProjectControllerUIImpl.openFile(ProjectControllerUIImpl.java:531)
    at org.gephi.desktop.project.ProjectControllerUIImpl.openFile(ProjectControllerUIImpl.java:489)
    at org.gephi.branding.desktop.actions.OpenFile.actionPerformed(OpenFile.java:71)
    at javax.swing.AbstractButton.fireActionPerformed
...
(27 additional frame(s) were not displayed)
```

**Comment by mbastian** [comment]
I checked the code and normally this should not happen for a file that exists. The only explanation is that [this openide method](https://bits.netbeans.org/12.3/javadoc/org-openide-filesystems/org/openide/filesystems/FileUtil.html#toFileObject-java.io.File-) returns `null`. As we don't expect this to be null we don't catch any exception. 

I would need help to reproduce this error. If this happens to you, please let me know what kind of file you were trying to open. Maybe it has to do with some edge cases with files over the network, dropbox or something of that nature.
