### ISSUE TITLE
Deleting nodes results in program freezing and not responding

### ISSUE THREAD

**Issue by edlovesiraq** [gephi/gephi#2485]
Love the initial configuration of my graph but I have to edit things out.  Whenever I try to do that I get one of two results. In the overview a clicking on and deleting a node results in a freeze of the program.  In the data table if I try to delete a node, nothing happens. It isn't deleted. 
## Expected Behavior
Delete button works to delete a node or edge
## Current Behavior
Results in no deletion and the program carsh/freezing
## Steps to Reproduce

1. Load graph
2. Right click on node to delete, selected
3. Watch gephi freeze and become unresponsive
4.

## Context
I'm on a brand new gaming laptop with a

Processor	AMD Ryzen 9 5900HX with Radeon Graphics           3.30 GHz
Installed RAM	64.0 GB (63.4 GB usable)
System type	64-bit operating system, x64-based processor
RTX 3060 GPU

## Your Environment

* Version used: Gephi 0.9.3
* Operating System: Windows 11

Processor	AMD Ryzen 9 5900HX with Radeon Graphics           3.30 GHz
Installed RAM	64.0 GB
System type	64-bit operating system, x64-based processor
RTX 3060 GPU

 (63
[DSDPlus.zip](https://github.com/gephi/gephi/files/8491800/DSDPlus.zip)
.4 GB usable)

**Comment by mbastian** [comment]
Thanks a lot for the report. I can reproduce the issue with the graph you provided. Seems related to updating the time index as I've also got this exception:

```java.lang.NullPointerException
	at org.gephi.graph.impl.TimeIndexImpl.remove(TimeIndexImpl.java:80)
	at org.gephi.graph.impl.TimeIndexStore.clear(TimeIndexStore.java:245)
	at org.gephi.graph.impl.ElementImpl.destroyAttributes(ElementImpl.java:459)
	at org.gephi.graph.impl.EdgeStore.remove(EdgeStore.java:668)
	at org.gephi.graph.impl.EdgeStore$EdgeInOutIterator.remove(EdgeStore.java:1449)
	at org.gephi.graph.impl.GraphStore.removeNode(GraphStore.java:268)
	at org.gephi.datalab.impl.GraphElementsControllerImpl.removeNode(GraphElementsControllerImpl.java:449)
	at org.gephi.datalab.impl.GraphElementsControllerImpl.deleteNodes(GraphElementsControllerImpl.java:187)
	at org.gephi.visualization.apiimpl.contextmenuitems.Delete.execute(Delete.java:69)
[catch] at org.gephi.datalab.api.DataLaboratoryHelper$5.run(DataLaboratoryHelper.java:349)```
