### ISSUE TITLE
GLException: Caught NullPointerException: null on thread DisplayAnimator

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#2497]
https://sentry.io/organizations/gephi/issues/3213011544/?referrer=github_plugin

```
NullPointerException: None
    at org.gephi.visualization.text.UniqueColorMode.textColor(UniqueColorMode.java:97)
    at org.gephi.visualization.text.UniqueColorMode.textNodeColor(UniqueColorMode.java:80)
    at org.gephi.visualization.text.TextManager$Renderer3D.drawTextNode(TextManager.java:382)
    at org.gephi.visualization.opengl.CompatibilityEngine.display(CompatibilityEngine.java:223)
    at org.gephi.visualization.scheduler.CompatibilityScheduler.display(CompatibilityScheduler.java:170)
...
(10 additional frame(s) were not displayed)

GLException: Caught NullPointerException: null on thread DisplayAnimator
    at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
    at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:782)
    at org.gephi.visualization.swing.GLAbstractListener.display(GLAbstractListener.java:327)
...
(2 additional frame(s) were not displayed)
```

**Comment by mbastian** [comment]
I can't reproduce this. If that happens to you, please let me know how to reproduce it.
