### ISSUE TITLE
NullPointerException in ImporterSpreadsheetCSV.autoDetectFieldDelimiter

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#2499]
https://sentry.io/organizations/gephi/issues/3211493836/?referrer=github_plugin

```
NullPointerException: None
    at org.gephi.io.importer.plugin.file.spreadsheet.ImporterSpreadsheetCSV.autoDetectFieldDelimiter(ImporterSpreadsheetCSV.java:120)
    at org.gephi.io.importer.plugin.file.spreadsheet.ImporterSpreadsheetCSV.refreshAutoDetections(ImporterSpreadsheetCSV.java:102)
    at org.gephi.io.importer.plugin.file.spreadsheet.AbstractImporterSpreadsheet.setFile(AbstractImporterSpreadsheet.java:408)
    at org.gephi.desktop.importer.DesktopImportControllerUI.importFiles(DesktopImportControllerUI.java:264)
    at org.gephi.desktop.importer.DesktopImportControllerUI.importFiles(DesktopImportControllerUI.java:175)
...
(39 additional frame(s) were not displayed)
```

**Comment by mbastian** [comment]
I can reproduce this with a CSV file that has zero size.
