### ISSUE TITLE
ClassCastException: class java.lang.Double cannot be cast to class org.gephi.graph.api.Interval (java.lang.Double is ...

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#2501]
https://sentry.io/organizations/gephi/issues/3210299489/?referrer=github_plugin

```
java.lang.ClassCastException: class java.lang.Double cannot be cast to class org.gephi.graph.api.Interval (java.lang.Double is in module java.base of loader 'bootstrap'; org.gephi.graph.api.Interval is in unnamed module of loader org.netbeans.StandardModule$OneModuleClassLoader @534d21ce)
    at org.gephi.graph.impl.IntervalIndexStore.checkK(IntervalIndexStore.java:23)
    at org.gephi.graph.impl.TimeIndexStore.remove(TimeIndexStore.java:136)
    at org.gephi.graph.impl.TimeIndexStore.remove(TimeIndexStore.java:189)
    at org.gephi.graph.impl.ElementImpl.updateIndex(ElementImpl.java:292)
    at org.gephi.graph.impl.ElementImpl.setAttribute(ElementImpl.java:235)
    at org.gephi.graph.impl.IndexStore.index(IndexStore.java:172)
    at org.gephi.graph.impl.ElementImpl.indexAttributes(ElementImpl.java:423)
    at org.gephi.graph.impl.EdgeStore.add(EdgeStore.java:620)
    at org.gephi.graph.impl.GraphStore.addEdge(GraphStore.java:166)
    at org.gephi.io.processor.plugin.DefaultProcessor.process(DefaultProcessor.java:276)
    at org.gephi.io.processor.plugin.AppendProcessor.process(AppendProcessor.java:89)
    at org.gephi.io.importer.impl.ImportControllerImpl.process(ImportControllerImpl.java:334)
    at org.gephi.desktop.importer.DesktopImportControllerUI$FinishImport.run(DesktopImportControllerUI.java:668)
    at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:278)
    at java.util.concurrent.Executors$RunnableAdapter.call
    at java.util.concurrent.FutureTask.run
    at java.util.concurrent.ThreadPoolExecutor.runWorker
    at java.util.concurrent.ThreadPoolExecutor$Worker.run
    at java.lang.Thread.run
```

**Comment by mbastian** [comment]
Closing as this has been fixed via another issue
