### ISSUE TITLE
NullPointerException on StatisticalInferenceClustering

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#2504]
https://sentry.io/organizations/gephi/issues/3215771595/?referrer=github_plugin

```
NullPointerException: None
    at org.gephi.statistics.plugin.StatisticalInferenceClustering.execute(StatisticalInferenceClustering.java:118)
    at org.gephi.statistics.plugin.StatisticalInferenceClustering.execute(StatisticalInferenceClustering.java:104)
    at org.gephi.statistics.StatisticsControllerImpl.execute(StatisticsControllerImpl.java:163)
    at org.gephi.statistics.StatisticsControllerImpl$3.run(StatisticsControllerImpl.java:150)
    at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:278)
...
(5 additional frame(s) were not displayed)
```

**Comment by mbastian** [comment]
@jacomyma Could you take a look at this one? Probably fixed by using `getOrDefault` instead of `get`.

**Comment by psalmuel19** [comment]
I also get this error from the app when trying to move between the overview and preview tabs: "A java.lang.NullPointerException exception has occurred. However, the system should continue working without further problems."
Then the app freezes and I have to force quit the application. Freezes almost every time I launch the app and I have to repeat same process. This is with version 0.9.4 on Mac.
