### ISSUE TITLE
IllegalMonitorStateException: Impossible to acquire a write lock when currently holding a read lock. Use toArray() methods on N...

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#2505]
https://sentry.io/organizations/gephi/issues/3215088528/?referrer=github_plugin

```
IllegalMonitorStateException: Impossible to acquire a write lock when currently holding a read lock. Use toArray() methods on NodeIterable and EdgeIterable to avoid holding a readLock or wrap your loop with a write lock.
    at org.gephi.graph.impl.GraphLockImpl.writeLock(GraphLockImpl.java:56)
    at org.gephi.graph.impl.GraphStore.writeLock(GraphStore.java:677)
    at org.gephi.graph.impl.GraphStore.autoWriteLock(GraphStore.java:710)
    at org.gephi.graph.impl.GraphViewStore.destroyView(GraphViewStore.java:99)
    at org.gephi.graph.impl.GraphModelImpl.destroyView(GraphModelImpl.java:278)
...
(4 additional frame(s) were not displayed)
```

**Comment by mbastian** [comment]
Note: It can only happen when the visibility ratio is less than 100%.

I can't reproduce it however. It could be due to an earlier exception in an item renderer not properly realising the read lock.
