### ISSUE TITLE
IllegalArgumentException: No dynamic intervals could be parsed

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#2506]
https://sentry.io/organizations/gephi/issues/3177754227/?referrer=github_plugin

```
IllegalArgumentException: No dynamic intervals could be parsed
    at org.gephi.graph.impl.IntervalsParser.parseIntervals(IntervalsParser.java:276)
    at org.gephi.graph.impl.IntervalsParser.parseIntervalMap(IntervalsParser.java:169)
    at org.gephi.graph.api.AttributeUtils.parse(AttributeUtils.java:404)
    at org.gephi.graph.api.AttributeUtils.parse(AttributeUtils.java:481)
    at org.gephi.appearance.AppearanceModelPersistenceProvider.readPartitions(AppearanceModelPersistenceProvider.java:253)
...
(11 additional frame(s) were not displayed)
```

**Comment by mbastian** [comment]
I can't reproduce this. If this error happens to you, please help me out and report the exact steps you followed. Thanks
