### ISSUE TITLE
IllegalArgumentException: The object class does not match with the column type (java.lang.Integer)

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#2509]
https://sentry.io/organizations/gephi/issues/2410910135/?referrer=github_plugin

```
IllegalArgumentException: The object class does not match with the column type (java.lang.Integer)
    at org.gephi.graph.impl.ElementImpl.checkType(ElementImpl.java:600)
    at org.gephi.graph.impl.ElementImpl.setAttribute(ElementImpl.java:232)
    at org.gephi.graph.impl.ElementImpl.setAttribute(ElementImpl.java:223)
    at org.gephi.statistics.plugin.GraphDistance.saveCalculatedValues(GraphDistance.java:396)
    at org.gephi.statistics.plugin.GraphDistance.execute(GraphDistance.java:193)
...
(9 additional frame(s) were not displayed)
```

**Comment by mbastian** [comment]
I think I can easily explain this one. When a column with the same id exists but with a different type it fails when saving values.
