### ISSUE TITLE
NullPointerException in org.gephi.ui.filters.plugin.partition.PartitionPanel.refresh

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#2528]
https://sentry.io/organizations/gephi/issues/3238237510/?referrer=github_plugin

```
NullPointerException: None
    at org.gephi.ui.filters.plugin.partition.PartitionPanel.refresh(PartitionPanel.java:191)
    at org.gephi.ui.filters.plugin.partition.PartitionPanel.setup(PartitionPanel.java:180)
    at org.gephi.ui.filters.plugin.partition.PartitionUIImpl.getPanel(PartitionUIImpl.java:59)
    at org.gephi.filters.plugin.partition.PartitionBuilder$PartitionFilterBuilder.getPanel(PartitionBuilder.java:167)
    at org.gephi.desktop.filters.FilterPanelPanel$1.run(FilterPanelPanel.java:121)
...
(14 additional frame(s) were not displayed)
```

**Comment by Cinga1994** [comment]
Hi, I met the same problem above, and want to know how to solve the problem, could you please tell me how to deal with it, thank you very much!
