### ISSUE TITLE
Error connecting to Twitter to import data

### ISSUE THREAD

**Issue by afolivieri** [gephi/gephi#2541]
I get this error when trying to use Twitter Streaming Importer:
```
403:The request is understood, but it has been refused. An accompanying error message will explain why. This code is used when requests are being denied due to update limits (https://support.twitter.com/articles/15364-about-twitter-limits-update-api-dm-and-following).
<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\n<title>Error 403 
Please use V2 filtered and sample volume stream as alternatives
</title>
</head>
<body>
<h2>HTTP ERROR: 403</h2>
<p>Problem accessing '/1.1/statuses/filter.json'. Reason:
<pre>    
Please use V2 filtered and sample volume stream as alternatives
</pre>
</body>
</html>

Relevant discussions can be found on the Internet at:
	http://www.google.co.jp/search?q=1169356e or
	http://www.google.co.jp/search?q=df77bcd3
TwitterException{exceptionCode=[1169356e-df77bcd3], statusCode=403, message=null, code=-1, retryAfter=-1, rateLimitStatus=null, version=4.0.7}
	at twitter4j.HttpClientImpl.handleRequest(HttpClientImpl.java:170)
	at twitter4j.HttpClientBase.request(HttpClientBase.java:57)
	at twitter4j.HttpClientBase.post(HttpClientBase.java:86)
	at twitter4j.TwitterStreamImpl.getFilterStream(TwitterStreamImpl.java:356)
	at twitter4j.TwitterStreamImpl$8.getStream(TwitterStreamImpl.java:330)
	at twitter4j.TwitterStreamImpl$TwitterStreamConsumer.run(TwitterStreamImpl.java:570)
Caused: java.lang.UnsupportedOperationException
	at totetmatt.gephi.twitter.TwitterStreamer$1.accept(TwitterStreamer.java:205)
	at totetmatt.gephi.twitter.TwitterStreamer$1.accept(TwitterStreamer.java:201)
	at twitter4j.TwitterStreamImpl$10.onException(TwitterStreamImpl.java:447)
[catch] at twitter4j.TwitterStreamImpl$TwitterStreamConsumer.run(TwitterStreamImpl.java:612)
```
How can I fix this?

**Comment by totetmatt** [comment]
Solved on the new Twitter Streaming Importer V2.
