### ISSUE TITLE
Gephi won't complete startup on Manjaro Linux

### ISSUE THREAD

**Issue by ngmaclaren** [gephi/gephi#2544]
## Expected Behavior

Normal startup.

## Current Behavior

Startup quits before opening Gephi. Here's the error message:

```
java.lang.InternalError: XXX0 profile[2]: GL2 -> profileImpl GL3bc !!! not mapped 
	at com.jogamp.opengl.GLProfile.computeProfileMap(GLProfile.java:2098)
	at com.jogamp.opengl.GLProfile.initProfilesForDeviceCritical(GLProfile.java:1976)
	at com.jogamp.opengl.GLProfile.initProfilesForDevice(GLProfile.java:1895)
	at com.jogamp.opengl.GLProfile.initProfilesForDefaultDevices(GLProfile.java:1861)
	at com.jogamp.opengl.GLProfile.access$000(GLProfile.java:80)
	at com.jogamp.opengl.GLProfile$1.run(GLProfile.java:239)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.opengl.GLProfile.initSingleton(GLProfile.java:225)
	at org.gephi.visualization.Installer.restored(Installer.java:56)
	at org.netbeans.core.startup.NbInstaller.loadCode(NbInstaller.java:447)
	at org.netbeans.core.startup.NbInstaller.loadImpl(NbInstaller.java:370)
	at org.netbeans.core.startup.NbInstaller.access$000(NbInstaller.java:77)
	at org.netbeans.core.startup.NbInstaller$1.run(NbInstaller.java:322)
	at org.openide.filesystems.FileUtil$2.run(FileUtil.java:418)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:102)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:494)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:402)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:422)
	at org.netbeans.core.startup.NbInstaller.load(NbInstaller.java:319)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1457)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1254)
	at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:315)
	at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:251)
	at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:298)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:156)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:125)
	at org.netbeans.core.startup.Main.start(Main.java:282)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:98)
	at java.base/java.lang.Thread.run(Unknown Source)   
```

## Possible Solution

I'm not sure!

## Steps to Reproduce

1. `sudo pacman -S gephi`
2. `gephi`

## Your Environment

* Version used: Gephi 0.9.5. Same problem with 0.9.3 and the 0.9.6 nightly build.
* Operating System: Manjaro Linux 21.2.6
* JRE: java-11-openjdk , but same message on 8 and 18

Here's the [messages.log](https://www.dropbox.com/s/qvsgsy6jrz3tvpk/messages.log?dl=0) file.

**Comment by totetmatt** [comment]
If it's an acceptable alternative, could you try an install with `snap`  https://snapcraft.io/gephi ? . I remember I used it on a manjaro not a long time ago and it was working via `snap`.

**Comment by ngmaclaren** [comment]
> If it's an acceptable alternative, could you try an install with `snap` https://snapcraft.io/gephi ? . I remember I used it on a manjaro not a long time ago and it was working via `snap`.

Working on it...
