### ISSUE TITLE
Gephi is freezing when using Streaming plugin in a saved/re-opened project

### ISSUE THREAD

**Issue by arpicheck** [gephi/gephi#2560]
Steps to reproduce:

Create a Project
Enable Master in Streaming Plugin (https://github.com/gephi/gephi/wiki/Scripting-Plugin)
Use streaming plugin (add some nodes)
Save Project
Close Gephi
Start Gephi
Re-open saved Project
Enable Master in Streaming Plugin (https://github.com/gephi/gephi/wiki/Scripting-Plugin)
Try to use Streaming Plugin (add some nodes again)

Gephi UI will freeze, or stays partly responsive but mixing UI elements and finally freezes

Observed on Win 8.1

Re-opening the Project and Starting Master the following messages appeared:

[INFO] Registering controller at context /workspace1 
[INFO] Starting StreamingServer... 
[WARNING] use of system property netbeans.user has been obsoleted in favor of InstalledFileLocator/Places at org.eclipse.jetty.util.log.Log$1.run(Log.java:122) 
[INFO] StreamingServer started at 2022. 07. 15. 16:16 
[INFO] 2022-07-15 16:16:36.459:INFO:oejs.Server:jetty-8.y.z-SNAPSHOT
 
[INFO] 2022-07-15 16:16:36.496:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:XXXX

Trying to add a node over Streaming Plugin:

[INFO] The column does not belong to the right column store 
java.lang.IllegalArgumentException: The column does not belong to the right column store
	at org.gephi.graph.impl.ElementImpl.checkColumn(ElementImpl.java:534)
	at org.gephi.graph.impl.ElementImpl.setAttribute(ElementImpl.java:230)
	at org.gephi.graph.impl.ElementImpl.setLabel(ElementImpl.java:90)
	at org.gephi.streaming.api.GraphUpdaterEventHandler.injectNodeProperty(GraphUpdaterEventHandler.java:371)
	at org.gephi.streaming.api.GraphUpdaterEventHandler.addNodeAttribute(GraphUpdaterEventHandler.java:340)
	at org.gephi.streaming.api.GraphUpdaterEventHandler.nodeChanged(GraphUpdaterEventHandler.java:318)
	at org.gephi.streaming.api.GraphUpdaterEventHandler.doHandleGraphEvent(GraphUpdaterEventHandler.java:159)
	at org.gephi.streaming.api.GraphUpdaterEventHandler.handleGraphEvent(GraphUpdaterEventHandler.java:134)
	at org.gephi.streaming.api.CompositeGraphEventHandler.handleGraphEvent(CompositeGraphEventHandler.java:95)
	at org.gephi.streaming.impl.json.JSONStreamReader.parse(JSONStreamReader.java:336)
	at org.gephi.streaming.impl.json.JSONStreamReader.parse(JSONStreamReader.java:220)
	at org.gephi.streaming.impl.json.JSONStreamReader.processStream(JSONStreamReader.java:134)
	at org.gephi.streaming.server.impl.ServerOperationExecutor.executeUpdateGraph(ServerOperationExecutor.java:219)
	at org.gephi.streaming.server.impl.ServerControllerImpl.handle(ServerControllerImpl.java:230)
	at org.gephi.streaming.server.impl.jetty.StreamingServerImpl$ContextContainer.service(StreamingServerImpl.java:307)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.base/java.lang.Thread.run(Unknown Source)

In case I do the node add via the Streaming Plugin with the Output window open, Gephi stays alive until I change window, but repeated add action do not appear anymore in the Output. Clicking Stop on Master in the Streaming Plugin is responsive leading to these messages:

[INFO] External Changes Refresh on focus gain disabled 
[INFO] Unregistering controller at context /workspace1 
[INFO] StreamingServer stopped at 2022. 07. 15. 16:21 
[INFO] 2022-07-15 16:21:44.153:INFO:oejsh.ContextHandler:stopped o.e.j.s.ServletContextHandler{/,null}
 
[INFO] 2022-07-15 16:21:44.253:WARN:oejut.QueuedThreadPool:2 threads could not be stopped

Starting Master back crashes Gephi.

**Comment by mbastian** [comment]
Hi @arpicheck and thanks for the report. The root cause is actually similar to #2557 so I'll mark this one as duplicate.
