### ISSUE TITLE
I can't boot into my PopOS!

### ISSUE THREAD

**Issue by dionatandiego11** [gephi/gephi#2620]
Version Gephi: 0.9.7
openjdk 11.0.16 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)

Command of run: ./gephi-0.9.7/bin/gephi

result:

java.lang.InternalError: XXX0 profile[2]: GL2 -> profileImpl GL3bc !!! not mapped 
	at com.jogamp.opengl.GLProfile.computeProfileMap(GLProfile.java:2098)
	at com.jogamp.opengl.GLProfile.initProfilesForDeviceCritical(GLProfile.java:1976)
	at com.jogamp.opengl.GLProfile.initProfilesForDevice(GLProfile.java:1895)
	at com.jogamp.opengl.GLProfile.initProfilesForDefaultDevices(GLProfile.java:1861)
	at com.jogamp.opengl.GLProfile.access$000(GLProfile.java:80)
	at com.jogamp.opengl.GLProfile$1.run(GLProfile.java:239)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.opengl.GLProfile.initSingleton(GLProfile.java:225)
	at org.gephi.visualization.Installer.restored(Installer.java:56)
	at org.netbeans.core.startup.NbInstaller.loadCode(NbInstaller.java:447)
	at org.netbeans.core.startup.NbInstaller.loadImpl(NbInstaller.java:370)
	at org.netbeans.core.startup.NbInstaller.access$000(NbInstaller.java:77)
	at org.netbeans.core.startup.NbInstaller$1.run(NbInstaller.java:322)
	at org.openide.filesystems.FileUtil$2.run(FileUtil.java:418)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:102)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:494)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:402)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:422)
	at org.netbeans.core.startup.NbInstaller.load(NbInstaller.java:319)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1457)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1254)
	at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:316)
	at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:252)
	at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:298)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:173)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:142)
	at org.netbeans.core.startup.Main.start(Main.java:299)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:98)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by egberts** [comment]
Same thing for Debian 11.
