### ISSUE TITLE
GL2 -> profileImpl GL3bc !!! not mapped

### ISSUE THREAD

**Issue by egberts** [gephi/gephi#2628]
## Expected Behavior

```console
# install JDK-1.11
$ apt install default-jdk
$ maven -T 4 clean install
$ echo $?
0
```

## Current Behavior

```console
# install JDK-1.11
$ apt install default-jdk
$ maven -T 4 clean install
...
[INFO] 
[INFO] --- maven-jar-plugin:3.2.2:jar (default) @ gephi ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: /home/wolfe/work/github/gephi/modules/application/target/gephi-0.10.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ gephi ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ gephi ---
[INFO] Installing /home/wolfe/work/github/gephi/modules/application/target/gephi-0.10.0-SNAPSHOT.jar to /home/wolfe/.m2/repository/org/gephi/gephi/0.10.0-SNAPSHOT/gephi-0.10.0-SNAPSHOT.zip
[INFO] Installing /home/wolfe/work/github/gephi/modules/application/pom.xml to /home/wolfe/.m2/repository/org/gephi/gephi/0.10.0-SNAPSHOT/gephi-0.10.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for gephi 0.10.0-SNAPSHOT:
[INFO] 
[INFO] gephi .............................................. SUCCESS [  0.623 s]
[INFO] LongTaskAPI ........................................ SUCCESS [  2.884 s]
[INFO] ProjectAPI ......................................... SUCCESS [  4.829 s]
[INFO] GraphAPI ........................................... SUCCESS [  5.470 s]
[INFO] ExportAPI .......................................... SUCCESS [  1.494 s]
[INFO] CoreLibraryWrapper ................................. SUCCESS [ 12.867 s]
[INFO] BatikWrapper ....................................... SUCCESS [  3.253 s]
[INFO] Utils .............................................. SUCCESS [  5.930 s]
[INFO] PreviewAPI ......................................... SUCCESS [  7.500 s]
[INFO] DataLaboratoryAPI .................................. SUCCESS [  6.820 s]
[INFO] VisualizationAPI ................................... SUCCESS [  4.397 s]
[INFO] PreviewPlugin ...................................... SUCCESS [  9.746 s]
[INFO] PreviewExport ...................................... SUCCESS [  8.288 s]
[INFO] UILibraryWrapper ................................... SUCCESS [  3.085 s]
[INFO] UIUtils ............................................ SUCCESS [  6.197 s]
[INFO] PreviewExportUI .................................... SUCCESS [  5.629 s]
[INFO] DBDrivers .......................................... SUCCESS [ 13.371 s]
[INFO] ImportAPI .......................................... SUCCESS [ 12.061 s]
[INFO] UIComponents ....................................... SUCCESS [  8.739 s]
[INFO] SettingsUpgrader ................................... SUCCESS [  9.042 s]
[INFO] StatisticsAPI ...................................... SUCCESS [  5.465 s]
[INFO] ExportPlugin ....................................... SUCCESS [  9.473 s]
[INFO] ImportPlugin ....................................... SUCCESS [ 20.307 s]
[INFO] StatisticsPlugin ................................... SUCCESS [ 13.619 s]
[INFO] StatisticsPluginUI ................................. SUCCESS [  6.286 s]
[INFO] FiltersAPI ......................................... SUCCESS [  5.728 s]
[INFO] AppearanceAPI ...................................... SUCCESS [  9.163 s]
[INFO] FiltersPlugin ...................................... SUCCESS [  6.161 s]
[INFO] TimelineAPI ........................................ SUCCESS [  4.115 s]
[INFO] ToolsAPI ........................................... SUCCESS [  3.998 s]
[INFO] AlgorithmsPlugin ................................... SUCCESS [  3.801 s]
[INFO] MostRecentFilesAPI ................................. SUCCESS [  8.794 s]
[INFO] DesktopProject ..................................... SUCCESS [  5.343 s]
[INFO] VisualizationImpl .................................. SUCCESS [ 18.176 s]
[INFO] ToolsPlugin ........................................ SUCCESS [ 10.048 s]
[INFO] WelcomeScreen ...................................... SUCCESS [  5.556 s]
[INFO] DesktopContext ..................................... SUCCESS [  5.609 s]
[INFO] PerspectiveAPI ..................................... SUCCESS [  2.992 s]
[INFO] DesktopWindow ...................................... SUCCESS [  6.190 s]
[INFO] DesktopBranding .................................... SUCCESS [ 13.506 s]
[INFO] LayoutAPI .......................................... SUCCESS [  8.823 s]
[INFO] GeneratorAPI ....................................... SUCCESS [  4.268 s]
[INFO] GeneratorPlugin .................................... SUCCESS [  7.198 s]
[INFO] GeneratorPluginUI .................................. SUCCESS [  4.268 s]
[INFO] DesktopStatistics .................................. SUCCESS [  6.935 s]
[INFO] LayoutPlugin ....................................... SUCCESS [  7.238 s]
[INFO] DesktopGenerate .................................... SUCCESS [  6.869 s]
[INFO] DesktopExport ...................................... SUCCESS [  6.604 s]
[INFO] DesktopDataLaboratory .............................. SUCCESS [ 11.009 s]
[INFO] AppearancePlugin ................................... SUCCESS [  8.271 s]
[INFO] AppearancePluginUI ................................. SUCCESS [  6.915 s]
[INFO] DesktopAppearance .................................. SUCCESS [ 10.252 s]
[INFO] FiltersImpl ........................................ SUCCESS [  8.146 s]
[INFO] ExportPluginUI ..................................... SUCCESS [  8.114 s]
[INFO] ImportPluginUI ..................................... SUCCESS [  9.862 s]
[INFO] DataLaboratoryPlugin ............................... SUCCESS [ 13.007 s]
[INFO] FiltersPluginUI .................................... SUCCESS [  6.255 s]
[INFO] DesktopLayout ...................................... SUCCESS [  6.327 s]
[INFO] DesktopImport ...................................... SUCCESS [ 10.076 s]
[INFO] DesktopPreview ..................................... SUCCESS [  8.110 s]
[INFO] DesktopTools ....................................... SUCCESS [  8.155 s]
[INFO] DesktopTimeline .................................... SUCCESS [  5.703 s]
[INFO] DirectoryChooser ................................... SUCCESS [  4.595 s]
[INFO] DesktopFilters ..................................... SUCCESS [  8.834 s]
[INFO] gephi-app .......................................... SUCCESS [ 33.534 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:45 min (Wall Clock)
[INFO] Finished at: 2022-09-17T12:47:00-05:00
[INFO] ------------------------------------------------------------------------
...
./modules/application/target/gephi/bin
wolfe@circa:~/work/github/gephi$ cd modules/application/target/gephi/bin/
wolfe@circa:~/work/github/gephi/modules/application/target/gephi/bin$ ls
gephi  gephi64.exe  gephi.exe
wolfe@circa:~/work/github/gephi/modules/application/target/gephi/bin$ ./gephi
Detected KDE; adding awt.useSystemAAFontSettings=on
java.lang.InternalError: XXX0 profile[2]: GL2 -> profileImpl GL3bc !!! not mapped 
	at com.jogamp.opengl.GLProfile.computeProfileMap(GLProfile.java:2098)
	at com.jogamp.opengl.GLProfile.initProfilesForDeviceCritical(GLProfile.java:1976)
	at com.jogamp.opengl.GLProfile.initProfilesForDevice(GLProfile.java:1895)
	at com.jogamp.opengl.GLProfile.initProfilesForDefaultDevices(GLProfile.java:1861)
	at com.jogamp.opengl.GLProfile.access$000(GLProfile.java:80)
	at com.jogamp.opengl.GLProfile$1.run(GLProfile.java:239)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.jogamp.opengl.GLProfile.initSingleton(GLProfile.java:225)
	at org.gephi.visualization.Installer.restored(Installer.java:56)
	at org.netbeans.core.startup.NbInstaller.loadCode(NbInstaller.java:447)
	at org.netbeans.core.startup.NbInstaller.loadImpl(NbInstaller.java:370)
	at org.netbeans.core.startup.NbInstaller.access$000(NbInstaller.java:77)
	at org.netbeans.core.startup.NbInstaller$1.run(NbInstaller.java:322)
	at org.openide.filesystems.FileUtil$2.run(FileUtil.java:418)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:102)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:494)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:402)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:422)
	at org.netbeans.core.startup.NbInstaller.load(NbInstaller.java:319)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1457)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1254)
	at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:316)
	at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:252)
	at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:298)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:173)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:142)
	at org.netbeans.core.startup.Main.start(Main.java:299)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:98)
	at java.base/java.lang.Thread.run(Thread.java:833)
$
$ echo $?

```

## Possible Solution

Unknown

## Steps to Reproduce

```console
# install JDK-1.11
$ apt install default-jdk
$ export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
$ git clone https://github.com/gephi/gephi.git
$ cd gephi
$ maven -T 4 clean install
$ cd gephi/modules/application/target/gephi/bin
$ ./gephi 
<error>
```

## Context

Just trying to start the gephi in a close-network

## Your Environment

* Version used: Gephi 0.9.7
* commit c5e3567a49ce4e842ed2a59a6bf5c705bd0c74a2 (HEAD -> master, origin/master, origin/HEAD) Author: Mathieu Bastian <mathieu.bastian@gmail.com> Date:   Wed Sep 14 21:43:20 2022 +0200     Use flatLaf swingX addon #2584
* Operating System: Linux 5.18.0-3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.14-1 (2022-07-23) x86_64 GNU/Linux
* Distro: Debian 11, latest update

**Comment by mbastian** [comment]
Thanks for the report. `GL2 -> profileImpl GL3bc !!! not mapped` comes from the old engine's GLProfile mapping code, which Gephi 0.11 replaced with a new visualization engine implementation.

Could you retry on the latest 0.11.x release? If it still reproduces, please open a fresh issue with your distro/KDE version and driver details. Closing this for now as superseded by the new engine.
