### ISSUE TITLE
gephi-toolkit fails on saveProject() in Java 18

### ISSUE THREAD

**Issue by j-hap** [gephi/gephi#2660]
## Expected Behavior

Using this code snippet
```
ProjectController pc = Lookup.getDefault().lookup(ProjectController.class);
pc.saveProject(pc.getCurrentProject(), new File("headless_simple.gephi")).run();
```
the gephi-toolkit should stores the project as .gephi file, that can be opened in the GUI

## Current Behavior

In a modified demo from the [gephi-toolkit-demos](https://github.com/gephi/gephi-toolkit-demos) I get this error message when importing and trying to save as .gephi when compiling with OpenJDK-18.0.2
I have another test (Java 15) with my actual data, that exports a corrupted .gephi file, that the GUI cannot open. I will probably open a different issue for that, if I can reproduce it with a demo.

```
SEVERE: No way to find original stream handler for jar protocol
java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.net.URLStreamHandler java.net.URL.handler accessible: module java.base does not "opens java.net" to unnamed module @68e965f5
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
	at org.netbeans.ProxyURLStreamHandlerFactory.register(ProxyURLStreamHandlerFactory.java:59)
	at org.netbeans.core.startup.Main.initializeURLFactory(Main.java:80)
	at org.netbeans.core.startup.NbRepository.<clinit>(NbRepository.java:47)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:236)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:546)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:496)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:341)
	at java.base/java.lang.Class.newInstance(Class.java:677)
	at org.openide.util.lookup.implspi.SharedClassObjectBridge.newInstance(SharedClassObjectBridge.java:41)
	at org.openide.util.lookup.MetaInfServicesLookup$Item.getInstance(MetaInfServicesLookup.java:489)
	at org.openide.util.lookup.AbstractLookup.lookup(AbstractLookup.java:397)
	at org.openide.util.lookup.ProxyLookup.lookup(ProxyLookup.java:281)
	at org.openide.filesystems.Repository$3.call(Repository.java:359)
	at org.openide.filesystems.Repository$3.call(Repository.java:357)
	at org.openide.filesystems.Repository.delayFileSystemAttachImpl(Repository.java:1007)
	at org.openide.filesystems.Repository.getDefault(Repository.java:357)
	at org.openide.filesystems.Repository$4.getRepository(Repository.java:454)
	at org.openide.filesystems.Repository.getLocalRepository(Repository.java:435)
	at org.openide.filesystems.FileUtil.getConfigFile(FileUtil.java:2173)
	at org.openide.filesystems.FileUtil.getConfigRoot(FileUtil.java:2257)
	at org.netbeans.core.startup.preferences.NbPreferences$UserPreferences.getFileStorage(NbPreferences.java:365)
	at org.netbeans.core.startup.preferences.NbPreferences.<init>(NbPreferences.java:90)
	at org.netbeans.core.startup.preferences.NbPreferences.<init>(NbPreferences.java:42)
	at org.netbeans.core.startup.preferences.NbPreferences$UserPreferences.<init>(NbPreferences.java:349)
	at org.netbeans.core.startup.preferences.NbPreferences.userRootImpl(NbPreferences.java:74)
	at org.netbeans.core.startup.preferences.PreferencesProviderImpl.preferencesRoot(PreferencesProviderImpl.java:49)
	at org.netbeans.core.startup.preferences.PreferencesProviderImpl.preferencesForModule(PreferencesProviderImpl.java:45)
	at org.openide.util.NbPreferences.forModule(NbPreferences.java:51)
	at org.gephi.project.io.SaveTask.run(SaveTask.java:128)
	at org.gephi.toolkit.demos.HeadlessSimple.script(HeadlessSimple.java:104)
	at org.gephi.toolkit.demos.HeadlessSimple.main(HeadlessSimple.java:108)
```

## Possible Solution

In Java 15 the demo code produces a valid .gephi file.

## Steps to Reproduce

Build and run this:
```
import org.gephi.graph.api.GraphController;
import org.gephi.graph.api.GraphModel;
import org.gephi.io.importer.api.Container;
import org.gephi.io.importer.api.EdgeDirectionDefault;
import org.gephi.io.importer.api.ImportController;
import org.gephi.io.processor.plugin.DefaultProcessor;
import org.gephi.preview.api.PreviewController;
import org.gephi.preview.api.PreviewModel;
import org.gephi.project.api.ProjectController;
import org.gephi.project.api.Workspace;
import org.openide.util.Lookup;

import java.io.File;

public class HeadlessSimple {

  public void script() {
    //Init a project - and therefore a workspace
    ProjectController pc = Lookup.getDefault().lookup(ProjectController.class);
    pc.newProject();
    Workspace workspace = pc.getCurrentWorkspace();

    //Get models and controllers for this new workspace - will be useful later
    GraphModel graphModel = Lookup.getDefault().lookup(GraphController.class).getGraphModel();
    PreviewModel model = Lookup.getDefault().lookup(PreviewController.class).getModel();
    ImportController importController = Lookup.getDefault().lookup(ImportController.class);

    //Import file
    Container container;
    try {
      File file = new File(getClass().getResource("/org/gephi/toolkit/demos/lesmiserables.gml").toURI());
      container = importController.importFile(file);
      container.getLoader().setEdgeDefault(EdgeDirectionDefault.DIRECTED);   //Force DIRECTED
      container.getLoader().setAllowAutoNode(false);  //Don't create missing nodes
    } catch (Exception ex) {
      ex.printStackTrace();
      return;
    }

    //Append imported data to GraphAPI
    importController.process(container, new DefaultProcessor(), workspace);

    pc.saveProject(pc.getCurrentProject(), new File("headless_simple.gephi")).run();
  }

  public static void main(String[] args) {
    new HeadlessSimple().script();
  }
}
```

## Context

I'm using the toolkit to have all steps reproducible when creating a graph visualization and I want to check out an intermediate state in the GUI to try some stuff out, that is easier when done interactively

## Your Environment

I use a maven project with the toolkit dependency.
```
        <dependency>
            <groupId>org.gephi</groupId>
            <artifactId>gephi-toolkit</artifactId>
            <version>0.9.7</version>
        </dependency>
```
* Version used: Gephi 0.9.7
* Operating System: Windows 10 21H2
* JDK: OpenJDK-18.0.2

**Comment by j-hap** [comment]
sorry, should have opened this in the gephi-toolkit repo

**Comment by mbastian** [comment]
Hi @j-hap, we currently officially support JDK 11. We plan to support JDK 19 at some point soon but it's not immediately planned. The stack trace does seem to originate in Netbeans Platform code. I could find [this issue](https://github.com/apache/netbeans/issues/4242) over there that looks similar. The fix could be adding some JDK params to your program.

**Comment by j-hap** [comment]
Thanks, @mbastian. I'm fine with Java 11 for now, so no rush. Thanks for Gephi :)
