### ISSUE TITLE
NoClassDefFoundError jogamp.opengl.GLProfile is back

### ISSUE THREAD

**Issue by doej1367** [gephi/gephi#2707]
## Expected Behavior

A graph to show

## Current Behavior

Graph view getting stuck on `Initialization...` and an Exception (see at bottom of this report)

![grafik](https://user-images.githubusercontent.com/19228364/204520077-d2db44d6-83e8-478a-8c6c-1f7776449bcd.png)

## Things I've tried

* removing Avira as suggested by #1356; using Windows Defender for now but didn't change anything
* applied all updates (Help > Check for updates) as suggested in #1374

## Steps to Reproduce

1. Open Gephi
2. See that the Graph view gets stuck on `Initialization...`

## Context

Want to use the app for its main purpouse aka 'generating a graph' but can't.

## Your Environment

* Version used: Gephi 0.9.7
* Operating System: Windows 10
* Java Version:
```
java version "19.0.1" 2022-10-18
Java(TM) SE Runtime Environment (build 19.0.1+10-21)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.1+10-21, mixed mode, sharing)
```

## Exception
```
lang.NoClassDefFoundError: Could not initialize class com.jogamp.opengl.GLProfile
	at org.gephi.visualization.swing.GLAbstractListener.getCaps(GLAbstractListener.java:175)
	at org.gephi.visualization.swing.NewtGraphCanvas.<init>(NewtGraphCanvas.java:67)
	at org.gephi.visualization.VizController.createNewtCanvas(VizController.java:357)
	at org.gephi.visualization.VizController.initInstances(VizController.java:127)
	at org.gephi.visualization.VizController.getInstance(VizController.java:104)
	at org.gephi.visualization.component.VizBarController.createDefaultGroups(VizBarController.java:99)
	at org.gephi.visualization.component.VizBarController.<init>(VizBarController.java:88)
	at org.gephi.visualization.component.GraphTopComponent.initCollapsePanel(GraphTopComponent.java:126)
	at org.gephi.visualization.component.GraphTopComponent$1$1.run(GraphTopComponent.java:107)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
[catch] at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by mbastian** [comment]
Hi @doej1367 it seems that you're using a custom JRE version, as opposed to the one packaged with Gephi. Use JRE 11 for executing Gephi and this should fix your issue.

**Comment by doej1367** [comment]
> Hi @doej1367 it seems that you're using a custom JRE version, as opposed to the one packaged with Gephi. Use JRE 11 for executing Gephi and this should fix your issue.

Thanks for the quick reply.

Tried setting java to version 11, but sadly still nothing. Here is what the Info tab now says:
```
Produktversion: Gephi 0.9.7 202208031831
Java: 11.0.16.1; Java HotSpot(TM) 64-Bit Server VM 11.0.16.1+1-LTS-1
System: Windows 10 Version 10.0 wird auf amd64 ausgeführt; Cp1252; de_DE (gephi)
Benutzerverzeichnis: C:\Users\User\AppData\Roaming\gephi\0.9
Cacheverzeichnis: C:\Users\User\AppData\Local\gephi\Cache\0.9
```

Oh, and when just I open one of the new gephy snapshots I get the same propt, I got at the very beginning of this problem:

![grafik](https://user-images.githubusercontent.com/19228364/205192911-6d55a3f1-9591-4562-bd51-432417d96f33.png)
