### ISSUE TITLE
Problems with Gephi installation

### ISSUE THREAD

**Issue by jeremi1504** [gephi/gephi#2752]
## Expected Behavior
Gephi can be installed without problems from  https://gephi.org/users/install/.

## Current Behavior
When I install Gephi from https://gephi.org/users/install/ the initialization of the Overview tab takes forever and I cannot view any graphs (including the test ones like Les Miserables.gexf). A little 'no entry' sign in the lower right corner says 'Unexpected Exception' and 'java.lang.reflect.InvocationTargetException'. The error message is enclosed below.

## Context
The solutions proposed e.g. here (https://github.com/gephi/gephi/issues/2189) did not work for me, nor did reinstalling Gephi. However, when I installed Gephi from https://github.com/gephi/gephi/wiki/How-to-build-Gephi (rather than downloading it directly) it partially solved the problem. Currently, I am able to run the graph overview, but unable to use other vital functions such as 'Import spreadsheet'. 

## Your Environment

* Version used: Gephi 0.10.1 & Gephi 0.10.2-SNAPSHOT
* Operating System: 
`' java.lang.UnsatisfiedLinkError: Cant load library: C:\Program Files\Gephi-0.10.1\natives\windows-amd64\\gluegen_rt.dll
    at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
    at java.base/java.lang.Runtime.load0(Unknown Source)
    at java.base/java.lang.System.load(Unknown Source)
    at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:625)
    at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:64)
    at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:107)
    at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:488)
    at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:427)
    at com.jogamp.common.os.Platform$1.run(Platform.java:321)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at com.jogamp.common.os.Platform.<clinit>(Platform.java:290)
    at com.jogamp.opengl.GLProfile.<clinit>(GLProfile.java:154)
    at org.gephi.visualization.swing.GLAbstractListener.getCaps(GLAbstractListener.java:179)
    at org.gephi.visualization.swing.NewtGraphCanvas.initDrawable(NewtGraphCanvas.java:68)
    at org.gephi.visualization.swing.GLAbstractListener.getGraphComponent(GLAbstractListener.java:548)
    at org.gephi.visualization.component.GraphTopComponent$1.lambda$run$1(GraphTopComponent.java:131)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
    at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
    at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused: java.lang.reflect.InvocationTargetException
    at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
    at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
    at java.desktop/javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
    at org.gephi.visualization.component.GraphTopComponent$1.lambda$run$2(GraphTopComponent.java:128)
Caused: java.lang.RuntimeException
    at org.gephi.visualization.component.GraphTopComponent$1.lambda$run$2(GraphTopComponent.java:136)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[catch] at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by seinecle** [comment]
Hi, what is your computer : MacOS, Windows? Which version please?

**Comment by jeremi1504** [comment]
Hi, I'm using Windows 10 Home, v. 21H2, OS build 19044.2728.

**Comment by CnaRoshandel** [comment]
Hi, I have the same problem, any fixes suggested ?

**Comment by mons1220** [comment]
I have the same problem too. Is there a possibility that the double backslash '\\' in the middle of the path is the problem?

> Cant load library: C:\Program Files\Gephi-0.10.1\natives\windows-amd64\\gluegen_rt.dll at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)

**Comment by mbastian** [comment]
Thanks for the detailed report. This is coming from the old native-library loader (`UnsatisfiedLinkError` on `gluegen_rt.dll`, via the old `visualization.Installer` → `NewtGraphCanvas.initDrawable()` path), code that Gephi 0.11 replaced entirely with a new visualization engine implementation. That changes how native graphics libraries are located and loaded on Windows.

Could you retry on the latest 0.11.x release? If the problem still reproduces, please open a fresh issue with your Windows version, GPU/driver details, and a fresh log, and we'll treat it as a live 0.11 regression. Closing this for now as superseded by the new engine.
