### ISSUE TITLE
Preview window does not show

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#442]
Using the 0.8beta version (Sun JDK 1.6.027, W7 64b, pt_br translation) I could not visualize the Preview window, even deleting the .gephi folder. The exception I got is:

java.lang.NullPointerException
	at org.gephi.desktop.preview.PreviewNode.createSheet(PreviewNode.java:84)
	at org.openide.nodes.AbstractNode.getSheet(AbstractNode.java:441)
	at org.openide.nodes.AbstractNode.getPropertySets(AbstractNode.java:457)
	at org.openide.explorer.propertysheet.PropertySheet$2.run(PropertySheet.java:594)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1424)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:1968)

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2011-10-06T14:53:47Z
 * owner: celiofariajr
 * the launchpad url was https://bugs.launchpad.net/bugs/869242

**Comment by mbastian** [comment]
Old issue, closing.
