### ISSUE TITLE
Preview failing on Mac OS X

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#443]
Some reports of Preview failure on OS X.

Stack trace:

java.lang.NullPointerException
 at org.gephi.desktop.preview.PreviewTopComponent.initTarget(PreviewTopComponent.java:183)
 at org.gephi.desktop.preview.PreviewTopComponent.&lt;init&gt;(PreviewTopComponent.java:138)
 at org.gephi.desktop.preview.PreviewTopComponent.getDefault(PreviewTopComponent.java:405)
 at org.gephi.desktop.preview.PreviewTopComponent$ResolvableHelper.readResolve(PreviewTopComponent.java:460)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
 at java.lang.reflect.Method.invoke(Method.java:597)
 at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1061)
 at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1761)
 at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
 at java.io.ObjectInputStream.readObject(ObjectInputStream.java:350)
 at org.netbeans.modules.settings.convertors.XMLSettingsSupport$SettingsRecognizer.readSerial(XMLSettingsSupport.java:549)
 at org.netbeans.modules.settings.convertors.XMLSettingsSupport$SettingsRecognizer.instanceCreate(XMLSettingsSupport.java:581)
 at org.netbeans.modules.settings.convertors.SerialDataConvertor$SettingsInstance.instanceCreate(SerialDataConvertor.java:424)
 at org.netbeans.core.windows.persistence.PersistenceManager.getTopComponentPersistentForID(PersistenceManager.java:545)
 at org.netbeans.core.windows.persistence.PersistenceManager.getTopComponentForID(PersistenceManager.java:655)

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2011-10-13T03:50:15Z
 * owner: mathieu.bastian
 * the launchpad url was https://bugs.launchpad.net/bugs/873148

**Comment by mbastian** [comment]
Closing, although unrelated to #748. This was related to a migration issue, which isn't relevant anymore.
