### ISSUE TITLE
Applying an edge ranking and then clearing the dropdown results in NullPointerException when saving

### ISSUE THREAD

**Issue by andygarcia** [gephi/gephi#706]
1. Generate a random graph.
2. In Data Laboratory edit one of the edge's WEIGHT attribute to something other than 1.0.
3.  In Overview, apply an edge ranking using WEIGHT.
4. Now clear the dropdown in the edge ranking (i.e. click "Choose a rank parameter").
5. Try to save the file as a gephi resulting in a NullPointerException.

While this seems an odd use case, I believe running into this problem where I import two previously edge ranked gexf files into a new gephi project into separate workspaces and then try to save the project as a gephi file.

Clipped from messages.log:

```
java.lang.NullPointerException
	at org.gephi.desktop.ranking.RankingPersistenceProvider.writeXML(RankingPersistenceProvider.java:139)
	at org.gephi.desktop.ranking.RankingPersistenceProvider.writeXML(RankingPersistenceProvider.java:73)
	at org.gephi.project.io.GephiWriter.writeWorkspaceChildren(GephiWriter.java:171)
	at org.gephi.project.io.GephiWriter.writeWorkspace(GephiWriter.java:162)
	at org.gephi.project.io.GephiWriter.writeProject(GephiWriter.java:143)
	at org.gephi.project.io.GephiWriter.writeAll(GephiWriter.java:88)
	at org.gephi.project.io.SaveTask.run(SaveTask.java:111)
	at org.gephi.desktop.project.ProjectControllerUIImpl$3.run(ProjectControllerUIImpl.java:139)
	at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:251)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
