### ISSUE TITLE
Modularity Calculation Throws Exception On Empty Graph

### ISSUE THREAD

**Issue by thallium205** [gephi/gephi#713]
When calculating an empty graph, the modularity calculation throw this error:

java.lang.ArithmeticException: / by zero
	at org.gephi.statistics.plugin.Modularity.execute(Modularity.java:477)
	at org.gephi.statistics.plugin.Modularity.execute(Modularity.java:454)
	at bitcoinvisualizer.GraphExporter.Export(GraphExporter.java:529)
	at bitcoinvisualizer.GraphExporter.ExportBetweenTwoDates(GraphExporter.java:188)
	at bitcoinvisualizer.GraphExporter.ExportOwnersAndDaysToMysql(GraphExporter.java:165)
	at bitcoinvisualizer.Main.main(Main.java:83)

Modularity was invoked using this method:
```java
// Modularity
LOG.info("Begin Modularity...");
Modularity modularity = new Modularity();
modularity.setRandom(true);
modularity.setUseWeight(true);
modularity.setResolution(1.0);
modularity.execute(graphModel, attributeModel);
LOG.info("Modularity Complete.");
```

**Comment by mbastian** [comment]
This is still happening in Gephi 0.9.1.
