### ISSUE TITLE
java.util.MissingResourceException after upgrade to 0.8.2 

### ISSUE THREAD

**Issue by suthers** [gephi/gephi#722]
Downloaded 0.8.2 (OS X 10.6.8, same configuration as 0.8.1 was running under). Got the following error and a blank application. Same error after re-download under different browser and removing 0.8.1 from Applications.  Sticking with 0.8.1 until fix comes out in 0.8.3. 
----------------------------------------------
Annotation: Offending classloader: SystemClassLoader[49 modules]
Annotation: Offending classloader: SystemClassLoader[49 modules]
Offending classloader: SystemClassLoader[49 modules]
Offending classloader: SystemClassLoader[49 modules]
Caused: java.util.MissingResourceException: No such bundle org.gephi.branding.Bundle
	at org.openide.util.NbBundle.getBundle(NbBundle.java:451)
	at org.openide.util.NbBundle.getBundle(NbBundle.java:383)
	at org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogFactory.createUpdateProvider(AutoupdateCatalogFactory.java:99)
[catch] at org.netbeans.modules.autoupdate.services.UpdateUnitProviderImpl.getUpdateUnitProviders(UpdateUnitProviderImpl.java:259)
	at org.netbeans.api.autoupdate.UpdateUnitProviderFactory.getUpdateUnitProviders(UpdateUnitProviderFactory.java:86)
	at org.netbeans.modules.autoupdate.ui.actions.AutoupdateCheckScheduler$7.run(AutoupdateCheckScheduler.java:471)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
