### ISSUE TITLE
Exception on Dynamic degree

### ISSUE THREAD

**Issue by sheymann** [gephi/gephi#788]
see https://forum.gephi.org/viewtopic.php?f=32&t=2776&p=8849#p8849

file: https://www.dropbox.com/s/zkshjfmgpqq3r4z/dynamic4.gephi

I'm having the following Exception when running the dynamic degree, which is obviously a bug:

java.lang.ArrayIndexOutOfBoundsException: 2
at org.gephi.data.attributes.AttributeRowImpl.setValue(AttributeRowImpl.java:149)
at org.gephi.data.attributes.AttributeRowImpl.setValue(AttributeRowImpl.java:141)
at org.gephi.data.attributes.AttributeRowImpl.setValue(AttributeRowImpl.java:128)
at org.gephi.data.attributes.AttributeRowImpl.setValue(AttributeRowImpl.java:98)
at org.gephi.statistics.plugin.dynamic.DynamicDegree.end(DynamicDegree.java:238)
at org.gephi.statistics.StatisticsControllerImpl.executeDynamic(StatisticsControllerImpl.java:215)
at org.gephi.statistics.StatisticsControllerImpl.access$100(StatisticsControllerImpl.java:77)
at org.gephi.statistics.StatisticsControllerImpl$2.run(StatisticsControllerImpl.java:133)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:251)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
at java.util.concurrent.FutureTask.run(FutureTask.java:166)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:722)

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
