### ISSUE TITLE
Loading GEXF files fails

### ISSUE THREAD

**Issue by vtudose** [gephi/gephi#899]
Using trunk commit 2ce8a3378c66ffa99dd065b5988e7f83aa3de8aa
Loading simple gexf file fails with exception:

```Java
[INFO] java.lang.IllegalArgumentException: The type id is org.gephi.io.importer.api.EdgeDirection but must be a primitive type (int, string, long...)
[INFO] 	at org.gephi.graph.store.EdgeTypeStore.checkType(EdgeTypeStore.java:186)
[INFO] 	at org.gephi.graph.store.EdgeTypeStore.addType(EdgeTypeStore.java:76)
[INFO] 	at org.gephi.graph.store.GraphModelImpl.addEdgeType(GraphModelImpl.java:125)
[INFO] 	at org.gephi.io.processor.plugin.DefaultProcessor.process(DefaultProcessor.java:123)
[INFO] 	at org.gephi.io.importer.impl.ImportControllerImpl.process(ImportControllerImpl.java:279)
[INFO] 	at org.gephi.desktop.importer.DesktopImportControllerUI.finishImport(DesktopImportControllerUI.java:520)
[INFO] 	at org.gephi.desktop.importer.DesktopImportControllerUI.access$100(DesktopImportControllerUI.java:97)
[INFO] 	at org.gephi.desktop.importer.DesktopImportControllerUI$3.run(DesktopImportControllerUI.java:180)
```

Glancing at the code:
ImporterGEXF.java:609 sets type to edge.setType(EdgeDirection.UNDIRECTED) but EdgeTypeStore:174 checks for a primitive data types

**Comment by mbastian** [comment]
This is fixed in trunk now, sorry about that.
