### ISSUE TITLE
gephi 8.0.2-beta java error

### ISSUE THREAD

**Issue by impaktor** [gephi/gephi#940]
Main menu only has option "Exit". I get the red warningsign in lower right corner.

Since I'm new to gephi, I assume the error might be something on my side, but I just tried the last version from the 0.7 ans that works.

    Annotation: Offending classloader: SystemClassLoader[48 modules]
    Annotation: Offending classloader: SystemClassLoader[48 modules]
    Offending classloader: SystemClassLoader[48 modules]
    Offending classloader: SystemClassLoader[48 modules]
    Caused: java.util.MissingResourceException: No such bundle org.gephi.branding.Bundle
    	at org.openide.util.NbBundle.getBundle(NbBundle.java:451)
    	at org.openide.util.NbBundle.getBundle(NbBundle.java:383)
    	at org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogFactory.createUpdateProvider(AutoupdateCatalogFactory.java:99)
    [catch] at org.netbeans.modules.autoupdate.services.UpdateU    Annotation: Offending classloader: SystemClassLoader[48 modules]
    Annotation: Offending classloader: SystemClassLoader[48 modules]
    Offending classloader: SystemClassLoader[48 modules]
    Offending classloader: SystemClassLoader[48 modules]
    Caused: java.util.MissingResourceException: No such bundle org.gephi.branding.Bundle
    	at org.openide.util.NbBundle.getBundle(NbBundle.java:451)
    	at org.openide.util.NbBundle.getBundle(NbBundle.java:383)
    	at org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogFactory.createUpdateProvider(AutoupdateCatalogFactory.java:99)
    [catch] at org.netbeans.modules.autoupdate.services.UpdateUnitProviderImpl.getUpdateUnitProviders(UpdateUnitProviderImpl.java:259)
    	at org.netbeans.api.autoupdate.UpdateUnitProviderFactory.getUpdateUnitProviders(UpdateUnitProviderFactory.java:86)
    	at org.netbeans.modules.autoupdate.ui.actions.AutoupdateCheckScheduler$7.run(AutoupdateCheckScheduler.java:471)
    	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
    	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)nitProviderImpl.getUpdateUnitProviders(UpdateUnitProviderImpl.java:259)
    	at org.netbeans.api.autoupdate.UpdateUnitProviderFactory.getUpdateUnitProviders(UpdateUnitProviderFactory.java:86)
    	at org.netbeans.modules.autoupdate.ui.actions.AutoupdateCheckScheduler$7.run(AutoupdateCheckScheduler.java:471)
    	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
    	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
